# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:sophia"
data modify storage animated_java:temp entry.data.rig_hash set value "c930a047d043d319bbfee3d8a23d7bcc218f85dc6166cf8b50765526c40ebed2"
tp @s ~ ~ ~ ~ ~
summon minecraft:item_display ^0 ^0 ^0 {Tags:["aj.display","aj.global.camera","aj.global.entity","aj.global.node","aj.global.node.camera1","aj.global.root.child","aj.global.root.child.camera","aj.new","aj.sophia.camera","aj.sophia.camera.camera1","aj.sophia.entity","aj.sophia.node","aj.sophia.node.camera1"], teleport_duration: 2}
execute as @n[ type=minecraft:item_display, tag=aj.sophia.camera.camera1, tag=aj.new, distance=..9 ] run function aj:sophia/zzz/summon/as_camera/camera1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.camera1 set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.cameras.camera1.uuid set from storage animated_java:gu out
summon minecraft:item_display ^0 ^0 ^0 {Tags:["aj.display","aj.global.camera","aj.global.entity","aj.global.node","aj.global.node.camera3","aj.global.root.child","aj.global.root.child.camera","aj.new","aj.sophia.camera","aj.sophia.camera.camera3","aj.sophia.entity","aj.sophia.node","aj.sophia.node.camera3"], teleport_duration: 2}
execute as @n[ type=minecraft:item_display, tag=aj.sophia.camera.camera3, tag=aj.new, distance=..6 ] run function aj:sophia/zzz/summon/as_camera/camera3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.camera3 set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.cameras.camera3.uuid set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide16] run function aj:sophia/zzz/summon/as_node/guide16
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide16 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide13] run function aj:sophia/zzz/summon/as_node/guide13
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide13 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide14] run function aj:sophia/zzz/summon/as_node/guide14
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide14 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide8] run function aj:sophia/zzz/summon/as_node/guide8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide9] run function aj:sophia/zzz/summon/as_node/guide9
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide9 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide10] run function aj:sophia/zzz/summon/as_node/guide10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide18] run function aj:sophia/zzz/summon/as_node/guide18
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide18 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide21] run function aj:sophia/zzz/summon/as_node/guide21
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide21 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide22] run function aj:sophia/zzz/summon/as_node/guide22
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide22 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide23] run function aj:sophia/zzz/summon/as_node/guide23
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide23 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide24] run function aj:sophia/zzz/summon/as_node/guide24
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide24 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide25] run function aj:sophia/zzz/summon/as_node/guide25
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide25 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide26] run function aj:sophia/zzz/summon/as_node/guide26
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide26 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide27] run function aj:sophia/zzz/summon/as_node/guide27
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide27 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide28] run function aj:sophia/zzz/summon/as_node/guide28
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide28 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide29] run function aj:sophia/zzz/summon/as_node/guide29
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide29 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide30] run function aj:sophia/zzz/summon/as_node/guide30
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide30 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide46] run function aj:sophia/zzz/summon/as_node/guide46
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide46 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide94] run function aj:sophia/zzz/summon/as_node/guide94
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide94 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide15] run function aj:sophia/zzz/summon/as_node/guide15
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide15 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide19] run function aj:sophia/zzz/summon/as_node/guide19
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide19 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide43] run function aj:sophia/zzz/summon/as_node/guide43
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide43 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide44] run function aj:sophia/zzz/summon/as_node/guide44
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide44 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide45] run function aj:sophia/zzz/summon/as_node/guide45
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide45 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide47] run function aj:sophia/zzz/summon/as_node/guide47
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide47 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide48] run function aj:sophia/zzz/summon/as_node/guide48
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide48 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide42] run function aj:sophia/zzz/summon/as_node/guide42
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide42 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide41] run function aj:sophia/zzz/summon/as_node/guide41
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide41 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide40] run function aj:sophia/zzz/summon/as_node/guide40
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide40 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide91] run function aj:sophia/zzz/summon/as_node/guide91
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide91 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide61] run function aj:sophia/zzz/summon/as_node/guide61
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide61 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide90] run function aj:sophia/zzz/summon/as_node/guide90
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide90 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide92] run function aj:sophia/zzz/summon/as_node/guide92
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide92 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide93] run function aj:sophia/zzz/summon/as_node/guide93
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide93 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide56] run function aj:sophia/zzz/summon/as_node/guide56
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide56 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide57] run function aj:sophia/zzz/summon/as_node/guide57
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide57 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide58] run function aj:sophia/zzz/summon/as_node/guide58
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide58 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide59] run function aj:sophia/zzz/summon/as_node/guide59
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide59 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide17] run function aj:sophia/zzz/summon/as_node/guide17
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide17 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide89] run function aj:sophia/zzz/summon/as_node/guide89
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide89 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide11] run function aj:sophia/zzz/summon/as_node/guide11
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide11 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide60] run function aj:sophia/zzz/summon/as_node/guide60
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide60 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide12] run function aj:sophia/zzz/summon/as_node/guide12
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide12 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide124] run function aj:sophia/zzz/summon/as_node/guide124
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide124 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide5] run function aj:sophia/zzz/summon/as_node/guide5
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide5 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide7] run function aj:sophia/zzz/summon/as_node/guide7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide6] run function aj:sophia/zzz/summon/as_node/guide6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide31] run function aj:sophia/zzz/summon/as_node/guide31
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide31 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide32] run function aj:sophia/zzz/summon/as_node/guide32
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide32 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide4] run function aj:sophia/zzz/summon/as_node/guide4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide33] run function aj:sophia/zzz/summon/as_node/guide33
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide33 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide3] run function aj:sophia/zzz/summon/as_node/guide3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide116] run function aj:sophia/zzz/summon/as_node/guide116
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide116 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide2] run function aj:sophia/zzz/summon/as_node/guide2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide117] run function aj:sophia/zzz/summon/as_node/guide117
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide117 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide118] run function aj:sophia/zzz/summon/as_node/guide118
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide118 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide49] run function aj:sophia/zzz/summon/as_node/guide49
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide49 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide50] run function aj:sophia/zzz/summon/as_node/guide50
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide50 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide39] run function aj:sophia/zzz/summon/as_node/guide39
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide39 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide51] run function aj:sophia/zzz/summon/as_node/guide51
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide51 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide52] run function aj:sophia/zzz/summon/as_node/guide52
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide52 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide38] run function aj:sophia/zzz/summon/as_node/guide38
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide38 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide34] run function aj:sophia/zzz/summon/as_node/guide34
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide34 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide37] run function aj:sophia/zzz/summon/as_node/guide37
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide37 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide95] run function aj:sophia/zzz/summon/as_node/guide95
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide95 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide36] run function aj:sophia/zzz/summon/as_node/guide36
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide36 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide35] run function aj:sophia/zzz/summon/as_node/guide35
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide35 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide53] run function aj:sophia/zzz/summon/as_node/guide53
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide53 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide54] run function aj:sophia/zzz/summon/as_node/guide54
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide54 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide55] run function aj:sophia/zzz/summon/as_node/guide55
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide55 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide119] run function aj:sophia/zzz/summon/as_node/guide119
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide119 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide20] run function aj:sophia/zzz/summon/as_node/guide20
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide20 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide96] run function aj:sophia/zzz/summon/as_node/guide96
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide96 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.guide97] run function aj:sophia/zzz/summon/as_node/guide97
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.guide97 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.layer] run function aj:sophia/zzz/summon/as_node/layer
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.layer set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.l_1] run function aj:sophia/zzz/summon/as_node/l_1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.l_1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.eye_l] run function aj:sophia/zzz/summon/as_node/eye_l
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_l set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.r_1] run function aj:sophia/zzz/summon/as_node/r_1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.r_1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.eye_r] run function aj:sophia/zzz/summon/as_node/eye_r
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eye_r set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.eyes_up] run function aj:sophia/zzz/summon/as_node/eyes_up
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyes_up set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.bone] run function aj:sophia/zzz/summon/as_node/bone
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.bone set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.l] run function aj:sophia/zzz/summon/as_node/l
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.l set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.r] run function aj:sophia/zzz/summon/as_node/r
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.r set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.eyes_down] run function aj:sophia/zzz/summon/as_node/eyes_down
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.eyes_down set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.up] run function aj:sophia/zzz/summon/as_node/up
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.up set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.down] run function aj:sophia/zzz/summon/as_node/down
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.down set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.mowse] run function aj:sophia/zzz/summon/as_node/mowse
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mowse set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.mouse_r] run function aj:sophia/zzz/summon/as_node/mouse_r
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mouse_r set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.mouse_l] run function aj:sophia/zzz/summon/as_node/mouse_l
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.mouse_l set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.head] run function aj:sophia/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.6] run function aj:sophia/zzz/summon/as_node/6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.12] run function aj:sophia/zzz/summon/as_node/12
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.12 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.10] run function aj:sophia/zzz/summon/as_node/10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.9] run function aj:sophia/zzz/summon/as_node/9
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.9 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.item_display] run function aj:sophia/zzz/summon/as_node/item_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.item_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.2] run function aj:sophia/zzz/summon/as_node/2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.1] run function aj:sophia/zzz/summon/as_node/1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.4] run function aj:sophia/zzz/summon/as_node/4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.3] run function aj:sophia/zzz/summon/as_node/3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.8] run function aj:sophia/zzz/summon/as_node/8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.7] run function aj:sophia/zzz/summon/as_node/7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.7 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.sophia.node.item_display1] run function aj:sophia/zzz/summon/as_node/item_display1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.item_display1 set from storage animated_java:gu out
function aj:sophia/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:sophia/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:sophia/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
function aj:sophia/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 5
execute on passengers run data modify entity @s teleport_duration set value 5
execute on passengers if entity @s[tag=aj.sophia.node.item_display1] run function aj:sophia/zzz/summon/on_summon/item_display_item_display1
execute at @s run function aj:sophia/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new