# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.stellar.animation.idle.playing
tag @s remove aj.stellar.animation.sit_down.playing
tag @s remove aj.stellar.animation.walk.playing
tag @s remove aj.stellar.animation.cutscene_world_tree_0.playing
tag @s remove aj.stellar.animation.cutscene_world_tree_1.playing
tag @s remove aj.stellar.animation.cutscene_world_tree_2.playing
tag @s remove aj.stellar.animation.earthquake_axe.playing
tag @s remove aj.stellar.animation.boots_of_the_black_hole.playing
tag @s remove aj.stellar.animation.earthquake_axe2.playing