# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:segrina rig_hash set value 'a5f2d390d21ead48140496afffc4685c35afb4a6916c6fbe0d7674b373992b48'
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.attack_1.frame dummy
scoreboard objectives add aj.attack_2.frame dummy
scoreboard objectives add aj.idle.frame dummy