# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.

execute on passengers \
    if entity @s[nbt={item: {id: "minecraft:iron_sword"}},type=minecraft:item_display] run data merge entity @s {brightness: {block: 15, sky: 15}, item: {components: {"minecraft:custom_model_data": {flags: [1b]}, "minecraft:item_model": "minecraft:sword/light_of_water_mirror/1"}, count: 1, id: "minecraft:iron_sword"}}
rotate @s ~ 0