# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle minecraft:flash ~ ~2 ~-0.5
particle minecraft:flash ~ ~2 ~-0.5
particle minecraft:sonic_boom ~ ~2 ~
particle end_rod ~ ~ ~ 0 0 0 1 50 normal @a
playsound minecraft:item.totem.use master @a ~ ~ ~ 1 0
playsound minecraft:block.chorus_flower.grow master @a ~ ~ ~ 1 0.75
playsound minecraft:block.chorus_flower.grow master @a ~ ~ ~ 1 0.75
playsound minecraft:block.chorus_flower.grow master @a ~ ~ ~ 1 0.75