# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:oceanid/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '153c4df8145567b9f4b14901784ef7de3de65f29271a6a9dc8fb8a0cca42c569'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack