# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(item_display) {transformation: [0.0134f,0.1137f,1.9967f,0.0967f,0.0542f,1.996f,-0.114f,0.6787f,-1.9992f,0.0548f,0.0103f,-1.042f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":1.6882235711730003,"py":0.3641759255495,"pz":-2.09232580964025,"ry":47.110720000000015,"rx":-10.5248}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities