# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [0.9945f,-0.0406f,0.0961f,0.0826f,-0.0313f,0.763f,0.6457f,1.0819f,-0.0995f,-0.6452f,0.7575f,-0.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [0.9945f,-0.0406f,0.0961f,0.1622f,-0.0313f,0.763f,0.6457f,1.0182f,-0.0995f,-0.6452f,0.7575f,-0.7798f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [0.9945f,-0.0406f,0.0961f,0.0826f,-0.0313f,0.763f,0.6457f,1.0819f,-0.0995f,-0.6452f,0.7575f,-0.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [0.9945f,-0.0406f,0.0961f,-0.0554f,-0.0313f,0.763f,0.6457f,1.0251f,-0.0995f,-0.6452f,0.7575f,-0.758f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [0.9945f,-0.0406f,0.0961f,-0.0701f,-0.0313f,0.763f,0.6457f,1.0248f,-0.0995f,-0.6452f,0.7575f,-0.7477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [0.9945f,-0.0406f,0.0961f,0.0754f,-0.0313f,0.763f,0.6457f,1.2178f,-0.0995f,-0.6452f,0.7575f,-0.611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [0.9945f,-0.0406f,0.0961f,0.0826f,-0.0313f,0.763f,0.6457f,1.0819f,-0.0995f,-0.6452f,0.7575f,-0.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [0.9945f,-0.0406f,0.0961f,0.1739f,-0.0313f,0.763f,0.6457f,1.0324f,-0.0995f,-0.6452f,0.7575f,-0.8243f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [0.9945f,-0.0406f,0.0961f,-0.0748f,-0.0313f,0.763f,0.6457f,1.0402f,-0.0995f,-0.6452f,0.7575f,-0.7994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [0.9945f,-0.0406f,0.0961f,0.0804f,-0.0313f,0.763f,0.6457f,1.1225f,-0.0995f,-0.6452f,0.7575f,-0.5303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [0.9945f,-0.0406f,0.0961f,0.0818f,-0.0313f,0.763f,0.6457f,1.0962f,-0.0995f,-0.6452f,0.7575f,-0.5082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [0.9945f,-0.0406f,0.0961f,0.0807f,-0.0313f,0.763f,0.6457f,1.1177f,-0.0995f,-0.6452f,0.7575f,-0.5263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [0.9945f,-0.0406f,0.0961f,0.0813f,-0.0313f,0.763f,0.6457f,1.1057f,-0.0995f,-0.6452f,0.7575f,-0.5163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [0.9945f,-0.0406f,0.0961f,0.0304f,-0.0313f,0.763f,0.6457f,0.9619f,-0.0995f,-0.6452f,0.7575f,-0.6347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [0.9945f,-0.0406f,0.0961f,0.0428f,-0.0313f,0.763f,0.6457f,0.9615f,-0.0995f,-0.6452f,0.7575f,-0.6359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [0.9945f,-0.0406f,0.0961f,0.0826f,-0.0313f,0.763f,0.6457f,1.0819f,-0.0995f,-0.6452f,0.7575f,-0.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.9945f,-0.0406f,0.0961f,0.0826f,-0.0313f,0.763f,0.6457f,1.0819f,-0.0995f,-0.6452f,0.7575f,-0.4961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9971f,-0.0635f,-0.0413f,0.1762f,-0.0655f,0.9968f,0.0466f,0.3401f,0.0382f,0.0492f,-0.9981f,-0.4626f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9971f,-0.0344f,-0.0676f,0.1656f,-0.0755f,0.5323f,0.8432f,0.5061f,0.007f,0.8459f,-0.5334f,-0.187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9998f,0.0204f,-0.0047f,0.0719f,0.0204f,0.9006f,-0.4341f,0.9073f,-0.0046f,-0.4341f,-0.9008f,-0.2828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-1f,-0.0054f,0.0042f,0.0703f,-0.0067f,0.6314f,-0.7754f,1.0961f,0.0016f,-0.7754f,-0.6314f,-0.4998f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9073f,-0.4178f,-0.0247f,-0.2051f,0.2443f,0.5776f,-0.7789f,0.7489f,0.3393f,0.7013f,0.6267f,-0.4307f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9269f,-0.2728f,-0.2579f,-0.2845f,0.1878f,0.9318f,-0.3106f,1.0341f,0.325f,0.2395f,0.9149f,-0.3814f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7963f,0.4785f,-0.1923f,0.3959f,0.0629f,0.4741f,0.8779f,0.7267f,0.4752f,0.7391f,-0.4386f,-0.4573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.8555f,0.2766f,-0.4377f,0.476f,0.0846f,0.9087f,0.4088f,1.0303f,0.5108f,0.3127f,-0.8008f,-0.3859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9924f,0.0032f,-0.1231f,-0.0877f,0.1055f,0.5386f,-0.8359f,0.3397f,0.0636f,-0.8426f,-0.5348f,0.0311f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9924f,0.055f,-0.1102f,-0.0713f,0.0928f,0.922f,-0.3759f,0.6347f,0.0809f,-0.3833f,-0.9201f,-0.105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,2f,0.0313f,-1.774f,0.9235f,0f,0.3281f,-0.9235f,-1.774f,0f,-1.1094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":2.3737987020941342,"py":0.852505674869615,"pz":-0.808055501145375,"ry":82.76749999999998,"rx":-0.6201388888888885}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities