# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [0.9921f,-0.0549f,0.1127f,0.0776f,-0.0363f,0.7345f,0.6776f,1.0544f,-0.12f,-0.6764f,0.7267f,-0.5315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [0.9921f,-0.0549f,0.1127f,0.1509f,-0.0363f,0.7345f,0.6776f,0.9784f,-0.12f,-0.6764f,0.7267f,-0.814f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [0.9921f,-0.0549f,0.1127f,0.0776f,-0.0363f,0.7345f,0.6776f,1.0544f,-0.12f,-0.6764f,0.7267f,-0.5315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [0.9921f,-0.0549f,0.1127f,-0.0661f,-0.0363f,0.7345f,0.6776f,0.9864f,-0.12f,-0.6764f,0.7267f,-0.7877f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [0.9921f,-0.0549f,0.1127f,-0.0806f,-0.0363f,0.7345f,0.6776f,0.9866f,-0.12f,-0.6764f,0.7267f,-0.7771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [0.9921f,-0.0549f,0.1127f,0.0678f,-0.0363f,0.7345f,0.6776f,1.1852f,-0.12f,-0.6764f,0.7267f,-0.652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [0.9921f,-0.0549f,0.1127f,0.0776f,-0.0363f,0.7345f,0.6776f,1.0544f,-0.12f,-0.6764f,0.7267f,-0.5315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [0.9921f,-0.0549f,0.1127f,0.1616f,-0.0363f,0.7345f,0.6776f,0.9907f,-0.12f,-0.6764f,0.7267f,-0.8593f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [0.9921f,-0.0549f,0.1127f,-0.0864f,-0.0363f,0.7345f,0.6776f,0.9998f,-0.12f,-0.6764f,0.7267f,-0.8293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [0.9921f,-0.0549f,0.1127f,0.0747f,-0.0363f,0.7345f,0.6776f,1.0934f,-0.12f,-0.6764f,0.7267f,-0.5674f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [0.9921f,-0.0549f,0.1127f,0.0765f,-0.0363f,0.7345f,0.6776f,1.0681f,-0.12f,-0.6764f,0.7267f,-0.5442f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [0.9921f,-0.0549f,0.1127f,0.075f,-0.0363f,0.7345f,0.6776f,1.0887f,-0.12f,-0.6764f,0.7267f,-0.5633f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [0.9921f,-0.0549f,0.1127f,0.0758f,-0.0363f,0.7345f,0.6776f,1.0773f,-0.12f,-0.6764f,0.7267f,-0.5527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [0.9921f,-0.0549f,0.1127f,0.0223f,-0.0363f,0.7345f,0.6776f,0.9286f,-0.12f,-0.6764f,0.7267f,-0.6637f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [0.9921f,-0.0549f,0.1127f,0.0347f,-0.0363f,0.7345f,0.6776f,0.9281f,-0.12f,-0.6764f,0.7267f,-0.6652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [0.9921f,-0.0549f,0.1127f,0.0776f,-0.0363f,0.7345f,0.6776f,1.0544f,-0.12f,-0.6764f,0.7267f,-0.5315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [0.9921f,-0.0549f,0.1127f,0.0776f,-0.0363f,0.7345f,0.6776f,1.0544f,-0.12f,-0.6764f,0.7267f,-0.5315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9966f,-0.0623f,-0.0546f,0.1719f,-0.0643f,0.9973f,0.0349f,0.3194f,0.0523f,0.0383f,-0.9979f,-0.4639f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.997f,-0.0232f,-0.0737f,0.1649f,-0.0738f,0.5664f,0.8208f,0.4966f,0.0227f,0.8238f,-0.5664f,-0.1952f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9998f,0.0144f,-0.0168f,0.0703f,0.0205f,0.885f,-0.4652f,0.8945f,0.0081f,-0.4654f,-0.885f,-0.308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9999f,-0.0148f,-0.0045f,0.0662f,-0.0053f,0.598f,-0.8015f,1.0729f,0.0145f,-0.8013f,-0.598f,-0.5315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9122f,-0.4067f,-0.0277f,-0.2084f,0.2552f,0.6239f,-0.7386f,0.7263f,0.3174f,0.6673f,0.6736f,-0.4388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9301f,-0.2661f,-0.2534f,-0.2861f,0.2014f,0.9459f,-0.2542f,1.0143f,0.3073f,0.1854f,0.9334f,-0.4044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7924f,0.4859f,-0.2171f,0.3941f,0.0779f,0.5237f,0.8478f,0.7013f,0.492f,0.6997f,-0.4838f,-0.4729f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.8457f,0.2683f,-0.4613f,0.4699f,0.0992f,0.9284f,0.3581f,1.0078f,0.5243f,0.2571f,-0.8118f,-0.4201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9912f,-0.0035f,-0.1325f,-0.0869f,0.1111f,0.5233f,-0.8448f,0.3355f,0.0723f,-0.8521f,-0.5183f,0.0241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.991f,0.0549f,-0.1217f,-0.0706f,0.0982f,0.9171f,-0.3863f,0.6288f,0.0904f,-0.3948f,-0.9143f,-0.1156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,2f,0.0308f,-1.7569f,0.9556f,0f,0.2885f,-0.9556f,-1.7569f,0f,-1.1326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
execute unless entity @s[tag=aj.transforms_only] positioned ^0 ^0 ^-1.25 rotated ~0 ~0 positioned ~ ~-0.5 ~ rotated ~ 0 run function aj:stellar/animations/earthquake_axe/zzz/frames/14_locator_locator_guide
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":2.40625,"py":0.875,"pz":-0.8124999999999997,"ry":84.99999999999994,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities