# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute store result storage aj:temp frame int 1 run scoreboard players set @s aj.skills.frame $(frame)

execute at @s run function animated_java:ruins_of_the_finality_skill/animations/skills/zzz/apply_frame with storage aj:temp