# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(hair1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(hair4) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(hair2) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(hair3) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(layer) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(head) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(6) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(12) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(10) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(9) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(2) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(1) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(item_display) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(4) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(3) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(8) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i
$execute as $(7) store result entity @s interpolation_duration int 1 run scoreboard players get #this aj.i