# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.10] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_10 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.9] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_9 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.item_display] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.item_display_item_display set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.4] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_4 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.3] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_3 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.6] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_6 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.5] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_5 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.8] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_8 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.boss_1.node.7] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_7 set from storage aj:uuid main.out