# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
playsound minecraft:entity.player.attack.knockback voice @a ~ ~1 ~ 1 0.5
playsound minecraft:entity.player.attack.sweep voice @a ~ ~1 ~ 1 0.5