# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=animated_java.portal.animation.spawn.playing] run function animated_java:portal/animations/spawn/zzz/on_tick
execute if entity @s[tag=animated_java.portal.animation.idle.playing] run function animated_java:portal/animations/idle/zzz/on_tick