# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9976f,-0.0772f,0.0304f,-0.0536f,-0.083f,0.9284f,-0.3649f,1.3498f,0f,-0.3661f,-0.9316f,-0.3071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9866f,-0.0772f,0.0303f,-0.1815f,-0.0821f,0.9275f,-0.3645f,1.5386f,0f,-0.3658f,-0.9307f,-0.1233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9866f,-0.0772f,0.0303f,-0.0535f,-0.0821f,0.9275f,-0.3645f,1.3481f,0f,-0.3658f,-0.9307f,-0.3115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9866f,-0.0772f,0.0303f,0.0356f,-0.0821f,0.9275f,-0.3645f,1.5557f,0f,-0.3658f,-0.9307f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9866f,-0.0772f,0.0303f,0.0528f,-0.0821f,0.9275f,-0.3645f,1.5625f,0f,-0.3658f,-0.9307f,-0.1318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9866f,-0.0772f,0.0304f,-0.0668f,-0.0821f,0.9275f,-0.3649f,1.5085f,0f,-0.3658f,-0.9316f,-0.3697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9866f,-0.0772f,0.0303f,-0.0536f,-0.0821f,0.9275f,-0.3645f,1.3498f,0f,-0.3658f,-0.9307f,-0.3071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9866f,-0.0617f,0.0303f,-0.1975f,-0.0821f,0.742f,-0.3645f,1.5864f,0f,-0.2926f,-0.9307f,-0.1124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.985f,-0.0831f,0.0303f,0.0491f,-0.0981f,0.74f,-0.3645f,1.607f,0.0063f,-0.2926f,-0.9307f,-0.1124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9866f,-0.0772f,0.0303f,-0.0572f,-0.0821f,0.9275f,-0.3645f,1.3929f,0f,-0.3658f,-0.9307f,-0.3241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9866f,-0.0772f,0.0303f,-0.0551f,-0.0821f,0.9275f,-0.3645f,1.3672f,0f,-0.3658f,-0.9307f,-0.3139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9866f,-0.0772f,0.0303f,-0.0573f,-0.0821f,0.9275f,-0.3645f,1.3933f,0f,-0.3658f,-0.9307f,-0.3242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9866f,-0.0772f,0.0303f,-0.056f,-0.0821f,0.9275f,-0.3645f,1.3788f,0f,-0.3658f,-0.9307f,-0.3185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9866f,-0.0918f,0.0303f,-0.0251f,-0.0821f,1.1037f,-0.3645f,1.4173f,0f,-0.4353f,-0.9307f,-0.1312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9866f,-0.0918f,0.0303f,-0.0374f,-0.0821f,1.1037f,-0.3645f,1.4163f,0f,-0.4353f,-0.9307f,-0.1312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9866f,-0.0772f,0.0303f,-0.0536f,-0.0821f,0.9275f,-0.3645f,1.3498f,0f,-0.3658f,-0.9307f,-0.3071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9966f,-0.0772f,0.0303f,-0.0536f,-0.0829f,0.9275f,-0.3645f,1.3498f,0f,-0.3658f,-0.9307f,-0.3071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.8861f,-0.4408f,-0.1371f,0.2117f,-0.3225f,0.8039f,-0.4981f,0.8209f,0.3299f,-0.3985f,-0.8554f,0.3832f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.92f,-0.3706f,0.1206f,0.0881f,-0.2872f,0.4368f,-0.8515f,0.9444f,0.2629f,-0.8197f,-0.5083f,0.0855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9864f,-0.026f,0.0683f,-0.0398f,-0.0714f,0.4995f,-0.8624f,1.1154f,-0.0116f,-0.8659f,-0.4995f,-0.1872f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9873f,-0.0478f,0.0554f,-0.057f,-0.0715f,0.7646f,-0.6404f,1.3902f,-0.0116f,-0.6427f,-0.766f,-0.4182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7728f,0.2351f,0.3877f,-0.5391f,-0.3767f,0.1572f,0.8778f,1.0782f,0.1291f,-0.9484f,0.2406f,-0.1009f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8568f,0.4521f,0.2f,-0.3812f,-0.4594f,0.5821f,0.6549f,1.2865f,0.1815f,-0.661f,0.7136f,-0.3192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7505f,-0.1992f,0.4919f,0.4115f,-0.449f,-0.0156f,-0.857f,1.2207f,0.1654f,-0.9765f,-0.0782f,-0.0441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.8676f,-0.3592f,0.3112f,0.2902f,-0.4611f,0.4816f,-0.7346f,1.4015f,0.1182f,-0.7986f,-0.5846f,-0.2948f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9626f,0.2566f,0.0764f,-0.1993f,0.1155f,0.6561f,-0.7446f,0.873f,-0.241f,-0.7095f,-0.6619f,0.4087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9806f,0.1763f,-0.075f,-0.1485f,0.1029f,0.1563f,-0.9814f,0.9066f,-0.161f,-0.9718f,-0.1711f,0.1211f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":204.5096023758546,"rx":14.76531720349205},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.67108980604985,"rx":12.779930663608498}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities