# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.0006f,0.0263f,-0.0061f,0.0158f,0.027f,0.9751f,-0.2245f,1.2911f,0f,-0.2245f,-0.9755f,-0.3652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9896f,0.0263f,-0.006f,-0.0873f,0.0267f,0.9742f,-0.2242f,1.4576f,0f,-0.2243f,-0.9745f,-0.1527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9896f,0.0263f,-0.006f,0.0158f,0.0267f,0.9742f,-0.2242f,1.2901f,0f,-0.2243f,-0.9745f,-0.3697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9896f,0.0263f,-0.006f,0.1292f,0.0267f,0.9742f,-0.2242f,1.4514f,0f,-0.2243f,-0.9745f,-0.1545f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9896f,0.0263f,-0.006f,0.1442f,0.0267f,0.9742f,-0.2242f,1.4628f,0f,-0.2243f,-0.9745f,-0.1618f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9896f,0.0263f,-0.0061f,0.0205f,0.0267f,0.9742f,-0.2245f,1.4662f,0f,-0.2243f,-0.9755f,-0.4055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9896f,0.0263f,-0.006f,0.0158f,0.0267f,0.9742f,-0.2242f,1.2911f,0f,-0.2243f,-0.9745f,-0.3652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9896f,0.021f,-0.006f,-0.1021f,0.0267f,0.7793f,-0.2242f,1.5107f,0f,-0.1795f,-0.9745f,-0.136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,0.0013f,-0.006f,0.1453f,0.0112f,0.7797f,-0.2242f,1.504f,0.0036f,-0.1794f,-0.9745f,-0.136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9896f,0.0263f,-0.006f,0.0171f,0.0267f,0.9742f,-0.2242f,1.3406f,0f,-0.2243f,-0.9745f,-0.3766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9896f,0.0263f,-0.006f,0.0163f,0.0267f,0.9742f,-0.2242f,1.3094f,0f,-0.2243f,-0.9745f,-0.3693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9896f,0.0263f,-0.006f,0.017f,0.0267f,0.9742f,-0.2242f,1.3368f,0f,-0.2243f,-0.9745f,-0.3756f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9896f,0.0263f,-0.006f,0.0166f,0.0267f,0.9742f,-0.2242f,1.3216f,0f,-0.2243f,-0.9745f,-0.3721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9896f,0.0313f,-0.006f,0.0509f,0.0267f,1.1593f,-0.2242f,1.3285f,0f,-0.2669f,-0.9745f,-0.1816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9896f,0.0313f,-0.006f,0.0385f,0.0267f,1.1593f,-0.2242f,1.3288f,0f,-0.2669f,-0.9745f,-0.1816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9896f,0.0263f,-0.006f,0.0158f,0.0267f,0.9742f,-0.2242f,1.2911f,0f,-0.2243f,-0.9745f,-0.3652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9996f,0.0263f,-0.006f,0.0158f,0.027f,0.9742f,-0.2242f,1.2911f,0f,-0.2243f,-0.9745f,-0.3652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9803f,-0.1765f,-0.0774f,0.194f,-0.0799f,0.7381f,-0.6686f,0.811f,0.1751f,-0.6508f,-0.7385f,0.3966f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9747f,-0.2187f,0.0113f,0.1192f,-0.0894f,0.3513f,-0.931f,0.9026f,0.1997f,-0.9104f,-0.362f,0.0724f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.988f,0.036f,-0.0261f,0.0013f,0.0402f,0.4991f,-0.8648f,1.0461f,-0.0179f,-0.8658f,-0.4995f,-0.2487f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.989f,0.0427f,-0.0122f,0.0166f,0.0402f,0.765f,-0.6427f,1.3211f,-0.0179f,-0.6426f,-0.766f,-0.4796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7656f,0.1669f,0.4381f,-0.4637f,-0.4f,0.0816f,0.8746f,1.0768f,0.0978f,-0.9721f,0.1478f,-0.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8503f,0.4214f,0.2792f,-0.3153f,-0.4825f,0.5155f,0.6929f,1.2626f,0.1496f,-0.7327f,0.6481f,-0.3738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8481f,-0.0134f,0.2967f,0.4305f,-0.2683f,0.0409f,-0.9464f,1.0638f,0.0036f,-0.9953f,-0.0331f,-0.1061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9379f,-0.2183f,0.2258f,0.3584f,-0.3148f,0.6058f,-0.7212f,1.2845f,0.0246f,-0.7642f,-0.638f,-0.3435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9988f,-0.0128f,-0.0164f,-0.1281f,0.0018f,0.7285f,-0.6839f,0.8257f,0.021f,-0.6848f,-0.7282f,0.3855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.999f,0.0078f,-0.0081f,-0.126f,0.01f,0.3042f,-0.9517f,0.9032f,-0.0047f,-0.9525f,-0.3037f,0.1019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.9100377949032,"rx":11.908301660118209},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.67454850851692,"rx":14.254927883595462}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities