# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6085f,-0.7948f,1.2661f,0f,-0.7948f,-0.6085f,-0.3398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.8045f,0.0004f,-0.0006f,-0.1084f,0.0007f,0.494f,-0.6452f,1.5368f,0f,-0.6452f,-0.494f,-0.2923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6079f,-0.794f,1.2623f,0f,-0.794f,-0.6079f,-0.3427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.8045f,0.0004f,-0.0006f,0.115f,0.0007f,0.494f,-0.6452f,1.5363f,0f,-0.6452f,-0.494f,-0.2926f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0.0005f,-0.0007f,0.1245f,0.0009f,0.6079f,-0.794f,1.5305f,0f,-0.794f,-0.6079f,-0.2947f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0.0004f,-0.0007f,0.0006f,0.0009f,0.4418f,-0.7909f,1.3852f,0f,-0.577f,-0.6056f,-0.4954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6079f,-0.794f,1.2661f,0f,-0.794f,-0.6079f,-0.3398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,-0.0054f,-0.0007f,-0.1229f,-0.002f,0.4863f,-0.794f,1.6086f,0.0037f,-0.6352f,-0.6079f,-0.3398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.99f,0.0068f,-0.0007f,0.1246f,0.004f,0.4863f,-0.794f,1.6084f,-0.0041f,-0.6352f,-0.6079f,-0.3398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6079f,-0.794f,1.2843f,0f,-0.794f,-0.6079f,-0.3636f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6079f,-0.794f,1.2785f,0f,-0.794f,-0.6079f,-0.356f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6079f,-0.794f,1.2946f,0f,-0.794f,-0.6079f,-0.377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6079f,-0.794f,1.2851f,0f,-0.794f,-0.6079f,-0.3646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0.0006f,-0.0007f,0.0347f,0.0009f,0.7238f,-0.794f,1.4126f,0f,-0.9452f,-0.6079f,-0.2228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0.0006f,-0.0007f,0.0223f,0.0009f,0.7238f,-0.794f,1.424f,0f,-0.9452f,-0.6079f,-0.2376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6079f,-0.794f,1.2661f,0f,-0.794f,-0.6079f,-0.3398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0.0005f,-0.0007f,0.0005f,0.0009f,0.6079f,-0.794f,1.2661f,0f,-0.794f,-0.6079f,-0.3398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9779f,-0.1957f,-0.06f,0.1912f,-0.099f,0.709f,-0.6969f,0.8192f,0.1788f,-0.6772f,-0.7135f,0.439f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9721f,-0.2278f,0.0355f,0.114f,-0.1074f,0.3119f,-0.9431f,0.8969f,0.2038f,-0.9224f,-0.3277f,0.1117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9887f,0.0229f,-0.0036f,-0.0077f,0.0137f,0.4678f,-0.8828f,1.0255f,-0.0184f,-0.8835f,-0.4675f,-0.2142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9897f,0.0228f,0.0045f,0.0005f,0.0137f,0.7419f,-0.6704f,1.2921f,-0.0184f,-0.6702f,-0.742f,-0.4551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7829f,0.1743f,0.3934f,-0.4922f,-0.3633f,0.0986f,0.8934f,1.0405f,0.1038f,-0.9692f,0.1607f,-0.1335f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8708f,0.4046f,0.2375f,-0.3502f,-0.4421f,0.542f,0.6996f,1.2356f,0.1559f,-0.7229f,0.6575f,-0.3738f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8298f,-0.1015f,0.3407f,0.4464f,-0.3196f,0.1872f,-0.91f,1.0252f,0.0287f,-0.9731f,-0.2008f,-0.1445f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9227f,-0.289f,0.2082f,0.3512f,-0.3562f,0.703f,-0.6071f,1.2754f,0.0325f,-0.6488f,-0.7526f,-0.3408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9985f,-0.0318f,0.0014f,-0.1312f,-0.0235f,0.7024f,-0.7103f,0.8251f,0.0219f,-0.7109f,-0.7026f,0.4277f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9989f,-0.0001f,0.0167f,-0.1311f,-0.0162f,0.2693f,-0.9621f,0.8922f,-0.0041f,-0.963f,-0.2687f,0.1415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.9100377949032,"rx":11.908301660118209},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.67454850851692,"rx":14.254927883595462}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities