# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9972f,-0.0853f,0.0183f,-0.052f,-0.0872f,0.975f,-0.2094f,1.2989f,0f,-0.2102f,-0.9787f,-0.3565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.1726f,-0.0863f,0.974f,-0.2092f,1.4489f,0f,-0.21f,-0.9777f,-0.1415f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.0519f,-0.0863f,0.974f,-0.2092f,1.2979f,0f,-0.21f,-0.9777f,-0.3611f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9862f,-0.0852f,0.0183f,0.0432f,-0.0863f,0.974f,-0.2092f,1.4674f,0f,-0.21f,-0.9777f,-0.1434f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9862f,-0.0852f,0.0183f,0.0563f,-0.0863f,0.974f,-0.2092f,1.4811f,0f,-0.21f,-0.9777f,-0.1505f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.0673f,-0.0863f,0.974f,-0.2094f,1.4747f,0f,-0.21f,-0.9787f,-0.3944f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.052f,-0.0863f,0.974f,-0.2092f,1.2989f,0f,-0.21f,-0.9777f,-0.3565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9862f,-0.0682f,0.0183f,-0.1938f,-0.0863f,0.7792f,-0.2092f,1.5002f,0f,-0.168f,-0.9777f,-0.1241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.986f,-0.0718f,0.0183f,0.0528f,-0.0892f,0.7789f,-0.2092f,1.5218f,0.0006f,-0.168f,-0.9777f,-0.1241f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.0563f,-0.0863f,0.974f,-0.2092f,1.3488f,0f,-0.21f,-0.9777f,-0.3672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.0536f,-0.0863f,0.974f,-0.2092f,1.3172f,0f,-0.21f,-0.9777f,-0.3604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.056f,-0.0863f,0.974f,-0.2092f,1.3446f,0f,-0.21f,-0.9777f,-0.3663f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.0546f,-0.0863f,0.974f,-0.2092f,1.3293f,0f,-0.21f,-0.9777f,-0.363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9862f,-0.1014f,0.0183f,-0.0212f,-0.0863f,1.159f,-0.2092f,1.3373f,0f,-0.2499f,-0.9777f,-0.1723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9862f,-0.1014f,0.0183f,-0.0335f,-0.0863f,1.159f,-0.2092f,1.3362f,0f,-0.2499f,-0.9777f,-0.1723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9862f,-0.0852f,0.0183f,-0.052f,-0.0863f,0.974f,-0.2092f,1.2989f,0f,-0.21f,-0.9777f,-0.3565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9962f,-0.0852f,0.0183f,-0.052f,-0.0872f,0.974f,-0.2092f,1.2989f,0f,-0.21f,-0.9777f,-0.3565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.8831f,-0.457f,-0.0974f,0.2119f,-0.3035f,0.7198f,-0.623f,0.8273f,0.3549f,-0.5221f,-0.7752f,0.3742f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.919f,-0.3708f,0.1276f,0.0884f,-0.2723f,0.3701f,-0.8872f,0.9268f,0.2818f,-0.8518f,-0.441f,0.0676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9864f,-0.0117f,0.071f,-0.042f,-0.0666f,0.5006f,-0.8622f,1.0553f,-0.0252f,-0.8656f,-0.4996f,-0.2396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9874f,-0.0353f,0.0628f,-0.0547f,-0.0667f,0.7656f,-0.6398f,1.3304f,-0.0252f,-0.6424f,-0.766f,-0.4704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7706f,0.2536f,0.3817f,-0.5416f,-0.371f,0.1285f,0.8855f,1.0292f,0.1558f,-0.948f,0.2212f,-0.1424f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8537f,0.4643f,0.185f,-0.3797f,-0.452f,0.5625f,0.6768f,1.231f,0.2123f,-0.6694f,0.697f,-0.3638f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7471f,-0.1925f,0.501f,0.4198f,-0.4616f,0.0153f,-0.8496f,1.1338f,0.145f,-0.9773f,-0.1031f,-0.1006f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.8667f,-0.3709f,0.2999f,0.2948f,-0.4679f,0.5427f,-0.6872f,1.3337f,0.0961f,-0.7527f,-0.645f,-0.3344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9911f,0.0365f,0.1198f,-0.1517f,-0.0499f,0.7622f,-0.6442f,0.8194f,-0.1147f,-0.6461f,-0.7543f,0.3901f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9957f,0.0091f,0.0806f,-0.148f,-0.0749f,0.2829f,-0.9554f,0.8905f,-0.0312f,-0.959f,-0.2807f,0.1048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":204.11708597282617,"rx":10.13667630108597},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.84337466869218,"rx":13.571993768097776}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities