# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,-0.009f,0.0016f,-0.0056f,-0.0091f,0.9853f,-0.1765f,1.3236f,0f,-0.1765f,-0.9853f,-0.3357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.99f,-0.009f,0.0016f,-0.1138f,-0.009f,0.9843f,-0.1763f,1.4747f,0f,-0.1763f,-0.9843f,-0.1153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,-0.009f,0.0016f,-0.0056f,-0.009f,0.9843f,-0.1763f,1.3227f,0f,-0.1763f,-0.9843f,-0.3403f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.99f,-0.009f,0.0016f,0.1028f,-0.009f,0.9843f,-0.1763f,1.4763f,0f,-0.1763f,-0.9843f,-0.1171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,-0.009f,0.0016f,0.1166f,-0.009f,0.9843f,-0.1763f,1.4896f,0f,-0.1763f,-0.9843f,-0.1239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,-0.009f,0.0016f,-0.0073f,-0.009f,0.9843f,-0.1765f,1.5019f,0f,-0.1763f,-0.9853f,-0.3676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,-0.009f,0.0016f,-0.0056f,-0.009f,0.9843f,-0.1763f,1.3236f,0f,-0.1763f,-0.9843f,-0.3357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,-0.0072f,0.0016f,-0.1313f,-0.009f,0.7874f,-0.1763f,1.5273f,0f,-0.1411f,-0.9843f,-0.0961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.99f,-0.0029f,0.0016f,0.1162f,-0.0056f,0.7875f,-0.1763f,1.5295f,-0.0006f,-0.1411f,-0.9843f,-0.0961f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,-0.009f,0.0016f,-0.0061f,-0.009f,0.9843f,-0.1763f,1.3743f,0f,-0.1763f,-0.9843f,-0.3447f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,-0.009f,0.0016f,-0.0058f,-0.009f,0.9843f,-0.1763f,1.342f,0f,-0.1763f,-0.9843f,-0.3389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,-0.009f,0.0016f,-0.0061f,-0.009f,0.9843f,-0.1763f,1.3697f,0f,-0.1763f,-0.9843f,-0.3439f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,-0.009f,0.0016f,-0.0059f,-0.009f,0.9843f,-0.1763f,1.3543f,0f,-0.1763f,-0.9843f,-0.3411f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,-0.0107f,0.0016f,0.0281f,-0.009f,1.1713f,-0.1763f,1.3531f,0f,-0.2099f,-0.9843f,-0.1504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,-0.0107f,0.0016f,0.0157f,-0.009f,1.1713f,-0.1763f,1.353f,0f,-0.2099f,-0.9843f,-0.1504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,-0.009f,0.0016f,-0.0056f,-0.009f,0.9843f,-0.1763f,1.3236f,0f,-0.1763f,-0.9843f,-0.3357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,-0.009f,0.0016f,-0.0056f,-0.0091f,0.9843f,-0.1763f,1.3236f,0f,-0.1763f,-0.9843f,-0.3357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9591f,-0.2637f,-0.093f,0.2001f,-0.1618f,0.795f,-0.5831f,0.8114f,0.2278f,-0.5457f,-0.8061f,0.3947f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9616f,-0.2663f,0.0505f,0.1101f,-0.1582f,0.4009f,-0.9014f,0.921f,0.2198f,-0.8766f,-0.4276f,0.08f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9886f,0.0298f,0.0019f,-0.0158f,0.0131f,0.4999f,-0.8651f,1.0838f,-0.0265f,-0.8656f,-0.4996f,-0.2176f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9896f,0.0274f,0.012f,-0.006f,0.0131f,0.7659f,-0.6428f,1.3591f,-0.0265f,-0.6423f,-0.766f,-0.4485f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7682f,0.1931f,0.4211f,-0.4886f,-0.3942f,0.1305f,0.8721f,1.0841f,0.1006f,-0.9619f,0.2019f,-0.1156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8526f,0.4344f,0.2509f,-0.3361f,-0.478f,0.5556f,0.6645f,1.2834f,0.1508f,-0.6948f,0.6882f,-0.3458f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8237f,-0.0759f,0.3646f,0.4278f,-0.3303f,0.0114f,-0.9221f,1.1357f,0.063f,-0.9934f,-0.0291f,-0.0733f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9188f,-0.2675f,0.2502f,0.3387f,-0.3624f,0.555f,-0.7389f,1.3403f,0.0629f,-0.7868f,-0.608f,-0.3191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9911f,0.1252f,0.0128f,-0.1634f,0.0767f,0.683f,-0.7252f,0.8546f,-0.0993f,-0.7194f,-0.6872f,0.3992f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9921f,0.1055f,-0.0521f,-0.1331f,0.0746f,0.2243f,-0.9708f,0.9084f,-0.0904f,-0.9687f,-0.2301f,0.1117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":203.36417411561902,"rx":13.902151103594614},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.19673288550956,"rx":12.818151127667953}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities