# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9972f,0.086f,-0.0117f,0.0559f,0.0868f,0.9881f,-0.1348f,1.3474f,0f,-0.1353f,-0.9918f,-0.3093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9863f,0.0859f,-0.0117f,-0.0377f,0.0858f,0.9871f,-0.1347f,1.4984f,0f,-0.1352f,-0.9908f,-0.0828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9863f,0.0859f,-0.0117f,0.0558f,0.0858f,0.9871f,-0.1347f,1.3468f,0f,-0.1352f,-0.9908f,-0.314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9863f,0.0859f,-0.0117f,0.178f,0.0858f,0.9871f,-0.1347f,1.4794f,0f,-0.1352f,-0.9908f,-0.0846f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9863f,0.0859f,-0.0117f,0.1927f,0.0858f,0.9871f,-0.1347f,1.4921f,0f,-0.1352f,-0.9908f,-0.0909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9863f,0.0859f,-0.0117f,0.0715f,0.0858f,0.9871f,-0.1348f,1.5271f,0f,-0.1352f,-0.9918f,-0.3339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9863f,0.0859f,-0.0117f,0.0559f,0.0858f,0.9871f,-0.1347f,1.3474f,0f,-0.1352f,-0.9908f,-0.3093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9863f,0.0687f,-0.0117f,-0.0505f,0.0858f,0.7897f,-0.1347f,1.5521f,0f,-0.1082f,-0.9908f,-0.0615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9866f,0.0641f,-0.0117f,0.1961f,0.0821f,0.7901f,-0.1347f,1.5307f,0.0005f,-0.1082f,-0.9908f,-0.0615f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9863f,0.0859f,-0.0117f,0.0604f,0.0858f,0.9871f,-0.1347f,1.3987f,0f,-0.1352f,-0.9908f,-0.3164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9863f,0.0859f,-0.0117f,0.0575f,0.0858f,0.9871f,-0.1347f,1.366f,0f,-0.1352f,-0.9908f,-0.3118f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9863f,0.0859f,-0.0117f,0.0599f,0.0858f,0.9871f,-0.1347f,1.3937f,0f,-0.1352f,-0.9908f,-0.3156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9863f,0.0859f,-0.0117f,0.0586f,0.0858f,0.9871f,-0.1347f,1.3783f,0f,-0.1352f,-0.9908f,-0.3135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9863f,0.1022f,-0.0117f,0.0917f,0.0858f,1.1746f,-0.1347f,1.3659f,0f,-0.1609f,-0.9908f,-0.123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9863f,0.1022f,-0.0117f,0.0793f,0.0858f,1.1746f,-0.1347f,1.367f,0f,-0.1609f,-0.9908f,-0.123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9863f,0.0859f,-0.0117f,0.0559f,0.0858f,0.9871f,-0.1347f,1.3474f,0f,-0.1352f,-0.9908f,-0.3093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9962f,0.0859f,-0.0117f,0.0559f,0.0867f,0.9871f,-0.1347f,1.3474f,0f,-0.1352f,-0.9908f,-0.3093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9962f,-0.012f,-0.0736f,0.1827f,0.0305f,0.835f,-0.5479f,0.796f,0.0679f,-0.5495f,-0.8325f,0.4178f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9882f,-0.1356f,-0.0559f,0.1344f,-0.0055f,0.4153f,-0.9088f,0.9104f,0.1464f,-0.8995f,-0.4111f,0.0957f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9829f,0.0744f,-0.0817f,0.0242f,0.1068f,0.4951f,-0.8612f,1.1143f,-0.0233f,-0.8657f,-0.4996f,-0.1897f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9839f,0.0978f,-0.0514f,0.0594f,0.1069f,0.7601f,-0.6408f,1.3875f,-0.0234f,-0.6424f,-0.766f,-0.4206f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7627f,0.1161f,0.4606f,-0.4132f,-0.4154f,0.1206f,0.8607f,1.1489f,0.0393f,-0.9755f,0.1603f,-0.0803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8485f,0.3905f,0.3256f,-0.2749f,-0.5013f,0.5399f,0.6602f,1.3427f,0.0829f,-0.7322f,0.6605f,-0.3237f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8748f,0.0526f,0.1698f,0.443f,-0.1547f,-0.0096f,-0.9771f,1.1394f,-0.0424f,-0.9952f,0.0281f,-0.0412f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9644f,-0.1415f,0.1682f,0.398f,-0.2206f,0.55f,-0.7957f,1.3428f,0.0242f,-0.8223f,-0.5628f,-0.2997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9654f,0.2052f,-0.1557f,-0.1668f,0.2472f,0.5707f,-0.7819f,0.9016f,-0.0711f,-0.795f,-0.6021f,0.4081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.952f,0.1953f,-0.2319f,-0.1123f,0.2595f,0.1312f,-0.9558f,0.9282f,-0.156f,-0.9719f,-0.1753f,0.1204f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":201.83695139219466,"rx":18.403944489800935},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.60481228707715,"rx":12.157376935773096}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities