# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.0008f,0.018f,-0.0022f,0.0118f,0.0182f,0.9933f,-0.1223f,1.3578f,0f,-0.1223f,-0.9935f,-0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9898f,0.018f,-0.0022f,-0.0917f,0.018f,0.9923f,-0.1221f,1.4987f,0f,-0.1222f,-0.9925f,-0.0723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9898f,0.018f,-0.0022f,0.0118f,0.018f,0.9923f,-0.1221f,1.3573f,0f,-0.1222f,-0.9925f,-0.3055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9898f,0.018f,-0.0022f,0.1248f,0.018f,0.9923f,-0.1221f,1.4946f,0f,-0.1222f,-0.9925f,-0.0742f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9898f,0.018f,-0.0022f,0.1384f,0.018f,0.9923f,-0.1221f,1.5086f,0f,-0.1222f,-0.9925f,-0.0803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9898f,0.018f,-0.0022f,0.0151f,0.018f,0.9923f,-0.1223f,1.539f,0f,-0.1222f,-0.9935f,-0.3231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9898f,0.018f,-0.0022f,0.0118f,0.018f,0.9923f,-0.1221f,1.3578f,0f,-0.1222f,-0.9925f,-0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9898f,0.0144f,-0.0022f,-0.1084f,0.018f,0.7939f,-0.1221f,1.5514f,0f,-0.0977f,-0.9925f,-0.0504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,-0.0018f,-0.0022f,0.139f,0.0049f,0.7941f,-0.1221f,1.5469f,0.0016f,-0.0977f,-0.9925f,-0.0504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9898f,0.018f,-0.0022f,0.0128f,0.018f,0.9923f,-0.1221f,1.4096f,0f,-0.1222f,-0.9925f,-0.3072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9898f,0.018f,-0.0022f,0.0122f,0.018f,0.9923f,-0.1221f,1.3764f,0f,-0.1222f,-0.9925f,-0.303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9898f,0.018f,-0.0022f,0.0127f,0.018f,0.9923f,-0.1221f,1.4044f,0f,-0.1222f,-0.9925f,-0.3065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9898f,0.018f,-0.0022f,0.0124f,0.018f,0.9923f,-0.1221f,1.3889f,0f,-0.1222f,-0.9925f,-0.3046f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9898f,0.0214f,-0.0022f,0.0462f,0.018f,1.1809f,-0.1221f,1.3763f,0f,-0.1454f,-0.9925f,-0.1142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9898f,0.0214f,-0.0022f,0.0338f,0.018f,1.1809f,-0.1221f,1.3765f,0f,-0.1454f,-0.9925f,-0.1142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9898f,0.018f,-0.0022f,0.0118f,0.018f,0.9923f,-0.1221f,1.3578f,0f,-0.1222f,-0.9925f,-0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9998f,0.018f,-0.0022f,0.0118f,0.0181f,0.9923f,-0.1221f,1.3578f,0f,-0.1222f,-0.9925f,-0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9763f,-0.1888f,-0.0964f,0.1954f,-0.1163f,0.8575f,-0.4995f,0.8024f,0.1769f,-0.4779f,-0.8601f,0.4059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9723f,-0.2285f,0.0219f,0.1175f,-0.1244f,0.4452f,-0.8858f,0.9278f,0.1927f,-0.8658f,-0.4613f,0.0939f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9882f,0.0343f,-0.0215f,-0.0016f,0.0354f,0.4992f,-0.8649f,1.1245f,-0.0188f,-0.8658f,-0.4996f,-0.1806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9892f,0.0396f,-0.0085f,0.0126f,0.0355f,0.7652f,-0.6428f,1.3995f,-0.0188f,-0.6425f,-0.766f,-0.4115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7701f,0.1569f,0.4316f,-0.4628f,-0.3955f,0.1102f,0.8742f,1.1374f,0.0795f,-0.971f,0.168f,-0.0761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.856f,0.4098f,0.2791f,-0.3185f,-0.4786f,0.5395f,0.6772f,1.3313f,0.1282f,-0.7219f,0.6646f,-0.3159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8434f,-0.0348f,0.3113f,0.4326f,-0.279f,-0.0497f,-0.941f,1.1843f,0.0468f,-0.9945f,0.0457f,-0.0333f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9341f,-0.2322f,0.2276f,0.3558f,-0.3199f,0.5214f,-0.7811f,1.3786f,0.0669f,-0.8203f,-0.5625f,-0.2914f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9614f,0.2604f,-0.0789f,-0.1853f,0.2214f,0.5813f,-0.7818f,0.8995f,-0.1574f,-0.7707f,-0.6171f,0.4105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9578f,0.2056f,-0.1965f,-0.1273f,0.2236f,0.119f,-0.9664f,0.9224f,-0.175f,-0.9713f,-0.1597f,0.1232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.99263447629653,"rx":17.657724678430455},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.74199277911725,"rx":12.16032047920951}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities