# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,-0.0089f,0.0021f,-0.0053f,-0.0091f,0.9753f,-0.2251f,1.2909f,0f,-0.2251f,-0.9754f,-0.3655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.99f,-0.0089f,0.0021f,-0.1092f,-0.009f,0.9743f,-0.2249f,1.4487f,0f,-0.2249f,-0.9744f,-0.152f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,-0.0089f,0.0021f,-0.0053f,-0.009f,0.9743f,-0.2249f,1.2899f,0f,-0.2249f,-0.9744f,-0.3701f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.99f,-0.0089f,0.0021f,0.1073f,-0.009f,0.9743f,-0.2249f,1.4503f,0f,-0.2249f,-0.9744f,-0.1538f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,-0.0089f,0.0021f,0.1168f,-0.009f,0.9743f,-0.2249f,1.4673f,0f,-0.2249f,-0.9744f,-0.1622f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,-0.0089f,0.0021f,-0.007f,-0.009f,0.9743f,-0.2251f,1.476f,0f,-0.2249f,-0.9754f,-0.4082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,-0.0089f,0.0021f,-0.0053f,-0.009f,0.9743f,-0.2249f,1.2909f,0f,-0.2249f,-0.9744f,-0.3655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,-0.0071f,0.0021f,-0.1311f,-0.009f,0.7795f,-0.2249f,1.5062f,0f,-0.1799f,-0.9744f,-0.1364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9897f,-0.0242f,0.0021f,0.1164f,-0.0225f,0.7792f,-0.2249f,1.5085f,0.0031f,-0.1799f,-0.9744f,-0.1364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,-0.0089f,0.0021f,-0.0058f,-0.009f,0.9743f,-0.2249f,1.3454f,0f,-0.2249f,-0.9744f,-0.3781f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,-0.0089f,0.0021f,-0.0055f,-0.009f,0.9743f,-0.2249f,1.3092f,0f,-0.2249f,-0.9744f,-0.3697f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,-0.0089f,0.0021f,-0.0058f,-0.009f,0.9743f,-0.2249f,1.3366f,0f,-0.2249f,-0.9744f,-0.376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,-0.0089f,0.0021f,-0.0056f,-0.009f,0.9743f,-0.2249f,1.3214f,0f,-0.2249f,-0.9744f,-0.3725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,-0.0106f,0.0021f,0.0283f,-0.009f,1.1595f,-0.2249f,1.3296f,0f,-0.2676f,-0.9744f,-0.1819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,-0.0106f,0.0021f,0.016f,-0.009f,1.1595f,-0.2249f,1.3295f,0f,-0.2676f,-0.9744f,-0.1819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,-0.0089f,0.0021f,-0.0053f,-0.009f,0.9743f,-0.2249f,1.2909f,0f,-0.2249f,-0.9744f,-0.3655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,-0.0089f,0.0021f,-0.0053f,-0.0091f,0.9743f,-0.2249f,1.2909f,0f,-0.2249f,-0.9744f,-0.3655f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9592f,-0.2678f,-0.0795f,0.2f,-0.1504f,0.7353f,-0.6596f,0.8155f,0.2351f,-0.6223f,-0.7464f,0.3894f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9617f,-0.2659f,0.0507f,0.1102f,-0.1471f,0.357f,-0.9215f,0.9095f,0.2269f,-0.8955f,-0.3824f,0.0696f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9888f,0.0206f,0.0048f,-0.012f,0.0061f,0.5f,-0.8651f,1.0455f,-0.02f,-0.8658f,-0.4995f,-0.249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9898f,0.0177f,0.0116f,-0.0056f,0.0061f,0.766f,-0.6428f,1.3208f,-0.02f,-0.6425f,-0.766f,-0.4799f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.769f,0.1894f,0.421f,-0.4871f,-0.386f,0.0655f,0.884f,1.0677f,0.1241f,-0.9692f,0.1411f,-0.1308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8536f,0.4313f,0.2527f,-0.3356f,-0.4662f,0.5078f,0.7096f,1.2512f,0.1795f,-0.7323f,0.6409f,-0.3745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8239f,-0.0899f,0.361f,0.4284f,-0.3326f,0.0939f,-0.9169f,1.0795f,0.0473f,-0.9882f,-0.111f,-0.1077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9189f,-0.2679f,0.2492f,0.3392f,-0.3645f,0.5934f,-0.708f,1.296f,0.0457f,-0.7581f,-0.6441f,-0.343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9987f,-0.0096f,0.0256f,-0.132f,-0.0244f,0.7437f,-0.6669f,0.8207f,-0.0123f,-0.6682f,-0.7435f,0.3854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9987f,-0.0045f,0.027f,-0.133f,-0.0272f,0.3052f,-0.9511f,0.8984f,-0.0036f,-0.9522f,-0.3046f,0.1018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":203.2963372966837,"rx":11.064042925571293},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.67125005108946,"rx":14.151621532883631}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities