# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.0005f,-0.0249f,0.0214f,-0.02f,-0.0329f,0.7586f,-0.6523f,1.3138f,0f,-0.6526f,-0.759f,-0.3408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9895f,-0.0249f,0.0214f,-0.1411f,-0.0325f,0.7578f,-0.6516f,1.5595f,0f,-0.652f,-0.7582f,-0.234f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9895f,-0.0249f,0.0214f,-0.0199f,-0.0325f,0.7578f,-0.6516f,1.3107f,0f,-0.652f,-0.7582f,-0.3444f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9895f,-0.0249f,0.0214f,0.083f,-0.0325f,0.7578f,-0.6516f,1.5648f,0f,-0.652f,-0.7582f,-0.2346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9895f,-0.0249f,0.0214f,0.0955f,-0.0325f,0.7578f,-0.6516f,1.5673f,0f,-0.652f,-0.7582f,-0.2423f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9895f,-0.0215f,0.0214f,-0.0241f,-0.0325f,0.6562f,-0.6507f,1.4404f,0f,-0.5645f,-0.7572f,-0.4498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9895f,-0.0249f,0.0214f,-0.02f,-0.0325f,0.7578f,-0.6516f,1.3138f,0f,-0.652f,-0.7582f,-0.3408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9895f,-0.0199f,0.0214f,-0.1535f,-0.0325f,0.6063f,-0.6516f,1.6094f,0f,-0.5216f,-0.7582f,-0.2401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9895f,-0.0191f,0.0214f,0.0939f,-0.032f,0.6063f,-0.6516f,1.6175f,-0.0004f,-0.5216f,-0.7582f,-0.2401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9895f,-0.0249f,0.0214f,-0.0211f,-0.0325f,0.7578f,-0.6516f,1.3481f,0f,-0.652f,-0.7582f,-0.3704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9895f,-0.0249f,0.0214f,-0.0205f,-0.0325f,0.7578f,-0.6516f,1.3279f,0f,-0.652f,-0.7582f,-0.3529f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9895f,-0.0249f,0.0214f,-0.0212f,-0.0325f,0.7578f,-0.6516f,1.3493f,0f,-0.652f,-0.7582f,-0.3713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9895f,-0.0249f,0.0214f,-0.0208f,-0.0325f,0.7578f,-0.6516f,1.3375f,0f,-0.652f,-0.7582f,-0.3612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9895f,-0.0296f,0.0214f,0.0101f,-0.0325f,0.9021f,-0.6516f,1.4342f,0f,-0.7761f,-0.7582f,-0.1962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9895f,-0.0296f,0.0214f,-0.0024f,-0.0325f,0.9021f,-0.6516f,1.4369f,0f,-0.7761f,-0.7582f,-0.1988f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9895f,-0.0249f,0.0214f,-0.02f,-0.0325f,0.7578f,-0.6516f,1.3138f,0f,-0.652f,-0.7582f,-0.3408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9995f,-0.0249f,0.0214f,-0.02f,-0.0328f,0.7578f,-0.6516f,1.3138f,0f,-0.652f,-0.7582f,-0.3408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9385f,-0.3283f,-0.0985f,0.2046f,-0.2084f,0.7751f,-0.5951f,0.8161f,0.2717f,-0.5394f,-0.7967f,0.3914f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9497f,-0.3008f,0.0752f,0.1036f,-0.1947f,0.3907f,-0.8988f,0.9223f,0.241f,-0.87f,-0.4296f,0.079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9886f,0.018f,0.0228f,-0.0244f,-0.0108f,0.4951f,-0.8679f,1.0738f,-0.0267f,-0.8687f,-0.4942f,-0.2215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9896f,0.0091f,0.0276f,-0.0211f,-0.0108f,0.7623f,-0.6471f,1.3478f,-0.0267f,-0.6471f,-0.7619f,-0.454f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7692f,0.209f,0.4112f,-0.5047f,-0.3853f,0.105f,0.8807f,1.0723f,0.125f,-0.9617f,0.1846f,-0.1175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8533f,0.4425f,0.2339f,-0.3497f,-0.467f,0.5393f,0.6854f,1.2663f,0.1789f,-0.7025f,0.6735f,-0.3506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.803f,-0.0912f,0.4149f,0.4258f,-0.372f,-0.0389f,-0.9014f,1.1352f,0.0925f,-0.9909f,0.0069f,-0.0788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9036f,-0.3008f,0.2672f,0.3251f,-0.3961f,0.5457f,-0.7284f,1.3367f,0.0773f,-0.7813f,-0.6134f,-0.3228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9919f,0.1086f,0.0494f,-0.1621f,0.0414f,0.7024f,-0.7094f,0.8456f,-0.1115f,-0.7033f,-0.7018f,0.4001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9955f,0.0832f,-0.0141f,-0.1378f,0.0331f,0.2343f,-0.9707f,0.9023f,-0.0772f,-0.9685f,-0.2357f,0.1126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":203.67623506829278,"rx":12.832641680599949},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.11491411914335,"rx":12.97879833442093}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities