# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9978f,0.0781f,-0.0161f,0.0479f,0.0797f,0.9773f,-0.2012f,1.3049f,0f,-0.2019f,-0.9804f,-0.3514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9869f,0.078f,-0.0161f,-0.0405f,0.0788f,0.9763f,-0.201f,1.4657f,0f,-0.2017f,-0.9795f,-0.1341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9869f,0.078f,-0.0161f,0.0479f,0.0788f,0.9763f,-0.201f,1.3039f,0f,-0.2017f,-0.9795f,-0.356f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9869f,0.078f,-0.0161f,0.1754f,0.0788f,0.9763f,-0.201f,1.448f,0f,-0.2017f,-0.9795f,-0.1359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9869f,0.078f,-0.0161f,0.1848f,0.0788f,0.9763f,-0.201f,1.4648f,0f,-0.2017f,-0.9795f,-0.144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9869f,0.078f,-0.0161f,0.063f,0.0788f,0.9763f,-0.2012f,1.4933f,0f,-0.2017f,-0.9804f,-0.3903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9869f,0.078f,-0.0161f,0.0479f,0.0788f,0.9763f,-0.201f,1.3049f,0f,-0.2017f,-0.9795f,-0.3514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9869f,0.0624f,-0.0161f,-0.0586f,0.0788f,0.7811f,-0.201f,1.525f,0f,-0.1613f,-0.9795f,-0.1172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9868f,0.0636f,-0.0161f,0.1881f,0.0798f,0.781f,-0.201f,1.5053f,-0.0002f,-0.1613f,-0.9795f,-0.1172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9869f,0.078f,-0.0161f,0.0524f,0.0788f,0.9763f,-0.201f,1.361f,0f,-0.2017f,-0.9795f,-0.363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9869f,0.078f,-0.0161f,0.0494f,0.0788f,0.9763f,-0.201f,1.3232f,0f,-0.2017f,-0.9795f,-0.3551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9869f,0.078f,-0.0161f,0.0516f,0.0788f,0.9763f,-0.201f,1.3507f,0f,-0.2017f,-0.9795f,-0.3608f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9869f,0.078f,-0.0161f,0.0504f,0.0788f,0.9763f,-0.201f,1.3354f,0f,-0.2017f,-0.9795f,-0.3576f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9869f,0.0928f,-0.0161f,0.0846f,0.0788f,1.1619f,-0.201f,1.3361f,0f,-0.24f,-0.9795f,-0.167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9869f,0.0928f,-0.0161f,0.0722f,0.0788f,1.1619f,-0.201f,1.3371f,0f,-0.24f,-0.9795f,-0.167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9869f,0.078f,-0.0161f,0.0479f,0.0788f,0.9763f,-0.201f,1.3049f,0f,-0.2017f,-0.9795f,-0.3514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9968f,0.078f,-0.0161f,0.0479f,0.0796f,0.9763f,-0.201f,1.3049f,0f,-0.2017f,-0.9795f,-0.3514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9953f,-0.0388f,-0.0773f,0.1846f,0.0212f,0.7568f,-0.652f,0.8037f,0.0836f,-0.6522f,-0.7532f,0.4091f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9865f,-0.1498f,-0.0496f,0.1316f,-0.0072f,0.3567f,-0.9333f,0.8971f,0.1575f,-0.9221f,-0.3529f,0.0811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9863f,0.03f,-0.0675f,0.0321f,0.0727f,0.4992f,-0.8625f,1.0627f,0.0077f,-0.866f,-0.4995f,-0.2341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9873f,0.0513f,-0.0532f,0.0505f,0.0728f,0.7644f,-0.6406f,1.3374f,0.0077f,-0.6427f,-0.766f,-0.4651f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.761f,0.1267f,0.4613f,-0.4247f,-0.4161f,0.0937f,0.8636f,1.1081f,0.0587f,-0.9771f,0.1417f,-0.1146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8462f,0.3997f,0.3205f,-0.2833f,-0.501f,0.5188f,0.6772f,1.2949f,0.1055f,-0.7424f,0.6457f,-0.3617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8712f,0.0376f,0.1948f,0.4348f,-0.1706f,0.1372f,-0.9648f,1.0673f,-0.0543f,-0.9872f,-0.1178f,-0.0889f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9605f,-0.146f,0.186f,0.3878f,-0.2384f,0.6012f,-0.7533f,1.2867f,0.0021f,-0.7848f,-0.6133f,-0.3336f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9947f,0.0378f,-0.0848f,-0.1355f,0.0876f,0.6787f,-0.728f,0.8493f,0.0305f,-0.7332f,-0.679f,0.3925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.992f,0.074f,-0.0926f,-0.1149f,0.1088f,0.2621f,-0.958f,0.9143f,-0.0463f,-0.9621f,-0.2678f,0.1065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.2087704188187,"rx":14.396878939913183},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.91870948070783,"rx":15.225807752326324}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities