# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.0004f,-0.0349f,0.0065f,-0.0218f,-0.0355f,0.9832f,-0.1844f,1.3179f,0f,-0.1845f,-0.9838f,-0.3407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.1274f,-0.0351f,0.9822f,-0.1842f,1.4638f,0f,-0.1844f,-0.9829f,-0.1207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.0217f,-0.0351f,0.9822f,-0.1842f,1.3171f,0f,-0.1844f,-0.9829f,-0.3453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9894f,-0.0349f,0.0065f,0.089f,-0.0351f,0.9822f,-0.1842f,1.4712f,0f,-0.1844f,-0.9829f,-0.1226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9894f,-0.0349f,0.0065f,0.096f,-0.0351f,0.9822f,-0.1842f,1.4889f,0f,-0.1844f,-0.9829f,-0.1303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.0285f,-0.0351f,0.9822f,-0.1844f,1.5086f,0f,-0.1844f,-0.9838f,-0.3765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.0218f,-0.0351f,0.9822f,-0.1842f,1.3179f,0f,-0.1844f,-0.9829f,-0.3407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9894f,-0.0279f,0.0065f,-0.1528f,-0.0351f,0.7858f,-0.1842f,1.5202f,0f,-0.1475f,-0.9829f,-0.1028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9886f,-0.0488f,0.0065f,0.0946f,-0.0518f,0.7849f,-0.1842f,1.529f,0.0031f,-0.1475f,-0.9829f,-0.1028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.0238f,-0.0351f,0.9822f,-0.1842f,1.3749f,0f,-0.1844f,-0.9829f,-0.3514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.0224f,-0.0351f,0.9822f,-0.1842f,1.3364f,0f,-0.1844f,-0.9829f,-0.3441f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.0234f,-0.0351f,0.9822f,-0.1842f,1.364f,0f,-0.1844f,-0.9829f,-0.3493f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.0229f,-0.0351f,0.9822f,-0.1842f,1.3487f,0f,-0.1844f,-0.9829f,-0.3464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9894f,-0.0415f,0.0065f,0.0112f,-0.0351f,1.1689f,-0.1842f,1.3499f,0f,-0.2194f,-0.9829f,-0.1557f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9894f,-0.0415f,0.0065f,-0.0012f,-0.0351f,1.1689f,-0.1842f,1.3495f,0f,-0.2194f,-0.9829f,-0.1557f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9894f,-0.0349f,0.0065f,-0.0218f,-0.0351f,0.9822f,-0.1842f,1.3179f,0f,-0.1844f,-0.9829f,-0.3407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9994f,-0.0349f,0.0065f,-0.0218f,-0.0355f,0.9822f,-0.1842f,1.3179f,0f,-0.1844f,-0.9829f,-0.3407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9379f,-0.3304f,-0.0971f,0.2043f,-0.2126f,0.7776f,-0.5903f,0.8162f,0.2706f,-0.5345f,-0.8004f,0.3883f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9492f,-0.3021f,0.0775f,0.1029f,-0.1987f,0.3953f,-0.8959f,0.9241f,0.24f,-0.8675f,-0.4352f,0.0765f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.987f,-0.052f,0.0363f,-0.001f,-0.0568f,0.4981f,-0.8644f,1.078f,0.0265f,-0.8656f,-0.4996f,-0.2229f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.988f,-0.0613f,0.0164f,-0.023f,-0.0569f,0.764f,-0.6427f,1.3525f,0.0266f,-0.6423f,-0.766f,-0.4538f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7723f,0.1977f,0.4093f,-0.5024f,-0.3765f,0.0641f,0.8894f,1.0876f,0.1328f,-0.9676f,0.1416f,-0.1098f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8572f,0.4322f,0.2384f,-0.3509f,-0.4555f,0.5101f,0.7149f,1.2719f,0.1893f,-0.7301f,0.6405f,-0.3528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8012f,-0.0926f,0.4189f,0.4245f,-0.376f,-0.0351f,-0.8996f,1.1388f,0.0922f,-0.9909f,0.0023f,-0.08f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9025f,-0.3024f,0.269f,0.3233f,-0.399f,0.5498f,-0.7239f,1.3415f,0.0751f,-0.7778f,-0.618f,-0.3227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.992f,0.1066f,0.0511f,-0.1624f,0.0395f,0.707f,-0.7049f,0.8447f,-0.111f,-0.6989f,-0.7063f,0.3972f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9956f,0.0824f,-0.0116f,-0.1384f,0.031f,0.2405f,-0.9693f,0.9032f,-0.0767f,-0.9671f,-0.2417f,0.1101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":203.67623506829278,"rx":12.832641680599938},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.13411816502156,"rx":15.962306090351502}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities