# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9974f,-0.0846f,0.0114f,-0.0551f,-0.0853f,0.9884f,-0.1331f,1.3486f,0f,-0.1336f,-0.992f,-0.3082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.1664f,-0.0844f,0.9874f,-0.133f,1.478f,0f,-0.1334f,-0.9911f,-0.0809f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.055f,-0.0844f,0.9874f,-0.133f,1.348f,0f,-0.1334f,-0.9911f,-0.3128f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9864f,-0.0845f,0.0114f,0.0494f,-0.0844f,0.9874f,-0.133f,1.4962f,0f,-0.1334f,-0.9911f,-0.0827f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9864f,-0.0845f,0.0114f,0.055f,-0.0844f,0.9874f,-0.133f,1.5142f,0f,-0.1334f,-0.9911f,-0.0895f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.0716f,-0.0844f,0.9874f,-0.1331f,1.5412f,0f,-0.1334f,-0.992f,-0.3342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.0551f,-0.0844f,0.9874f,-0.133f,1.3486f,0f,-0.1334f,-0.9911f,-0.3082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9864f,-0.0676f,0.0114f,-0.1949f,-0.0844f,0.79f,-0.133f,1.5316f,0f,-0.1068f,-0.9911f,-0.06f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9867f,-0.0636f,0.0114f,0.0517f,-0.0812f,0.7903f,-0.133f,1.5527f,-0.0004f,-0.1068f,-0.9911f,-0.06f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.06f,-0.0844f,0.9874f,-0.133f,1.4063f,0f,-0.1334f,-0.9911f,-0.316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.0567f,-0.0844f,0.9874f,-0.133f,1.3671f,0f,-0.1334f,-0.9911f,-0.3106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.059f,-0.0844f,0.9874f,-0.133f,1.3949f,0f,-0.1334f,-0.9911f,-0.3144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.0577f,-0.0844f,0.9874f,-0.133f,1.3795f,0f,-0.1334f,-0.9911f,-0.3123f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9864f,-0.1005f,0.0114f,-0.023f,-0.0844f,1.1751f,-0.133f,1.3726f,0f,-0.1588f,-0.9911f,-0.1219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9864f,-0.1005f,0.0114f,-0.0353f,-0.0844f,1.1751f,-0.133f,1.3716f,0f,-0.1588f,-0.9911f,-0.1219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9864f,-0.0845f,0.0114f,-0.0551f,-0.0844f,0.9874f,-0.133f,1.3486f,0f,-0.1334f,-0.9911f,-0.3082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9964f,-0.0845f,0.0114f,-0.0551f,-0.0853f,0.9874f,-0.133f,1.3486f,0f,-0.1334f,-0.9911f,-0.3082f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.8832f,-0.4465f,-0.1373f,0.2121f,-0.3265f,0.8006f,-0.5007f,0.8215f,0.3337f,-0.3988f,-0.8538f,0.3825f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9184f,-0.3738f,0.1228f,0.0874f,-0.2905f,0.4351f,-0.8513f,0.9444f,0.2648f,-0.8191f,-0.5082f,0.085f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9844f,-0.0572f,0.077f,-0.0297f,-0.0943f,0.4969f,-0.8617f,1.115f,0.011f,-0.8659f,-0.4995f,-0.1884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9854f,-0.0801f,0.0528f,-0.0585f,-0.0944f,0.7619f,-0.6406f,1.3889f,0.011f,-0.6427f,-0.766f,-0.4194f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7716f,0.2448f,0.3847f,-0.5429f,-0.3814f,0.195f,0.8675f,1.0655f,0.1219f,-0.9389f,0.2795f,-0.1107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8552f,0.4585f,0.1923f,-0.3829f,-0.4662f,0.6082f,0.6259f,1.2824f,0.1718f,-0.6324f,0.7412f,-0.3188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7478f,-0.1946f,0.499f,0.4111f,-0.4528f,-0.0293f,-0.8542f,1.22f,0.1676f,-0.9769f,-0.0651f,-0.0454f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.8658f,-0.3622f,0.3127f,0.2887f,-0.4643f,0.4815f,-0.7326f,1.4007f,0.1189f,-0.7972f,-0.5863f,-0.2956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9633f,0.2524f,0.0815f,-0.1989f,0.11f,0.6602f,-0.7418f,0.8713f,-0.2409f,-0.7072f,-0.6644f,0.4084f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9816f,0.1731f,-0.0688f,-0.1489f,0.0967f,0.1596f,-0.9815f,0.906f,-0.1586f,-0.9718f,-0.1731f,0.1208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":204.5325398144147,"rx":14.613916797013173},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.7184477460871,"rx":14.137204449711259}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities