# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:amysis/animations/cutscene_chapter_2_safe_zone_1/zzz/apply_frame {frame: 80}
scoreboard players add @s aj.cutscene_chapter_2_safe_zone_1.frame 1