# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute store result score @s aj.id run scoreboard players add aj.last_id aj.id 1
# Data Manager: Initalize per-entity storage
function animated_java:global/gu/get_entity_uuid_string
data modify storage animated_java:temp args.uuid set from storage animated_java:gu out
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
function animated_java:global/data_manager/create_entry with storage animated_java:temp args
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Read
function animated_java:global/data_manager/read with storage animated_java:temp args
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.root_uuid set from storage animated_java:gu out
data modify storage animated_java:temp entry.data.blueprint_id set value "aj:amysis"
data modify storage animated_java:temp entry.data.rig_hash set value "82a8e8abfb25ff882895246f6c6a3b422571cef65c035a62e53e0a79697096d0"
tp @s ~ ~ ~ ~ ~
execute on passengers if entity @s[tag=aj.amysis.node.hair1] run function aj:amysis/zzz/summon/as_node/hair1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hair1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.hair4] run function aj:amysis/zzz/summon/as_node/hair4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hair4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.hair2] run function aj:amysis/zzz/summon/as_node/hair2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hair2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.hair3] run function aj:amysis/zzz/summon/as_node/hair3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.hair3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.layer] run function aj:amysis/zzz/summon/as_node/layer
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.layer set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.head] run function aj:amysis/zzz/summon/as_node/head
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.head set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.6] run function aj:amysis/zzz/summon/as_node/6
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.6 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.12] run function aj:amysis/zzz/summon/as_node/12
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.12 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.10] run function aj:amysis/zzz/summon/as_node/10
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.10 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.9] run function aj:amysis/zzz/summon/as_node/9
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.9 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.2] run function aj:amysis/zzz/summon/as_node/2
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.2 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.1] run function aj:amysis/zzz/summon/as_node/1
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.1 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.item_display] run function aj:amysis/zzz/summon/as_node/item_display
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.item_display set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.4] run function aj:amysis/zzz/summon/as_node/4
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.4 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.3] run function aj:amysis/zzz/summon/as_node/3
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.3 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.8] run function aj:amysis/zzz/summon/as_node/8
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.8 set from storage animated_java:gu out
execute on passengers if entity @s[tag=aj.amysis.node.7] run function aj:amysis/zzz/summon/as_node/7
data modify storage animated_java:temp entry.data.uuids append from storage animated_java:gu out
data modify storage animated_java:temp entry.data.uuids_by_name.7 set from storage animated_java:gu out
function aj:amysis/zzz/set_default_pose
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
execute if data storage animated_java:temp args.variant run function aj:amysis/zzz/summon/zzz/variant_arg/no_variants_warning
execute if score #success aj.i matches 0 run return fail
execute if data storage animated_java:temp args.animation run function aj:amysis/zzz/summon/animation_arg/process with storage animated_java:temp args
execute if score #success aj.i matches 0 run return fail
execute on passengers run rotate @s ~ ~
data modify entity @s teleport_duration set value 5
execute on passengers run data modify entity @s teleport_duration set value 5
execute on passengers if entity @s[tag=aj.amysis.node.item_display] run function aj:amysis/zzz/summon/on_summon/item_display_item_display
execute at @s run function aj:amysis/zzz/summon/on_summon/rig
tag @s remove aj.new
execute on passengers run tag @s remove aj.new