# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.spawn_loop.frame dummy
scoreboard objectives add aj.spawn.frame dummy
scoreboard objectives add aj.heavy_attack_1.frame dummy
scoreboard objectives add aj.attack_1.frame dummy
scoreboard objectives add aj.attack_2.frame dummy
scoreboard objectives add aj.back.frame dummy
scoreboard objectives add aj.idle.frame dummy