# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.

execute \
    if score @s aj.ruins_of_the_end_2.frame matches 16.. run scoreboard players set @s aj.ruins_of_the_end_2.frame 1
data remove storage aj:temp args

execute \
    store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.ruins_of_the_end_2.frame

execute at @s run function animated_java:ruins_of_the_end_2/animations/ruins_of_the_end_2/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.ruins_of_the_end_2.frame 1