# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.l_ear] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_ear set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.r_ear] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_ear set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide204] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide204 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide205] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide205 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide206] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide206 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide207] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide207 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide235] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide235 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide236] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide236 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide237] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide237 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide238] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide238 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide239] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide239 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide240] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide240 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide241] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide241 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide242] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide242 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide243] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide243 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide244] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide244 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide245] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide245 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide246] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide246 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide247] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide247 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide248] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide248 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide249] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide249 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide250] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide250 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide251] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide251 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide252] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide252 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide253] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide253 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide254] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide254 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide255] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide255 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide256] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide256 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide257] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide257 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide258] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide258 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide259] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide259 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide260] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide260 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide261] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide261 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide262] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide262 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide263] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide263 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide264] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide264 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide265] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide265 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide266] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide266 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide267] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide267 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide268] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide268 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide269] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide269 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide270] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide270 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide271] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide271 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide272] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide272 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide273] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide273 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide274] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide274 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide275] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide275 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide276] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide276 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide277] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide277 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide278] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide278 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide279] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide279 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide280] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide280 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide281] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide281 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide282] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide282 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide284] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide284 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide283] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide283 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide285] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide285 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide286] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide286 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide287] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide287 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide288] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide288 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide289] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide289 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide290] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide290 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide291] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide291 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide292] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide292 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide293] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide293 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide294] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide294 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide296] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide296 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide295] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide295 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide297] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide297 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide298] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide298 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide299] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide299 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide300] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide300 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide301] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide301 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide302] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide302 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide303] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide303 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.guide304] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide304 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.layer] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_layer set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.l_3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l_3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.eye_l] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eye_l set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.r_3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r_3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.eye_r] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eye_r set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.l] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_l set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.r] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_r set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.up] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_up set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.down] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_down set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.mowse] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_mowse set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.mouse_r] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_mouse_r set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.mouse_l] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_mouse_l set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.eyes_down] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eyes_down set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.eyes_up] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_eyes_up set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.6] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_6 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.12] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_12 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.10] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_10 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.9] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_9 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone28] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone28 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone23] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone23 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone22] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone22 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone21] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone21 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone20] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone20 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone19] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone19 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone8] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone8 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone10] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone10 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone12] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone12 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone11] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone11 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone9] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone9 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone5] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone5 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone14] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone14 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone16] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone16 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone18] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone18 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone17] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone17 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone15] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone15 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone13] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone13 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone27] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone27 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone26] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone26 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone25] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone25 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone24] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone24 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.bone] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_bone set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.8] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_8 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.elina.node.7] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_7 set from storage animated_java:gu out