# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function weapons:type/scythe/ruins_of_the_finality/rc/animation/1/damage
function weapons:type/scythe/ruins_of_the_finality/rc/animation/1/fx