# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(l_1) {transformation: [-0.99f,0f,0f,-0.1081f,0f,1f,0f,1.5278f,0f,0f,-1f,0.2107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.99f,0f,0f,0.1081f,0f,1f,0f,1.5278f,0f,0f,-1f,0.2106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.5723f,0f,0f,-1.001f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,0.0019f,0f,-0.1238f,0.0015f,0.8f,0f,1.5656f,0f,0f,-1f,0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.99f,-0.0019f,0f,0.1237f,-0.0015f,0.8f,0f,1.5656f,0f,0f,-1f,0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4502f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4272f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4542f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.0333f,0f,1f,0f,1.4063f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1f,0f,1.4055f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,0.999f,0.0436f,1.163f,0f,0.0436f,-0.998f,-0.1018f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.9848f,0.1736f,1.517f,0f,0.1736f,-0.9848f,-0.0394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9739f,0.1539f,0.0637f,-0.3719f,-0.163f,0.9579f,0.1888f,1.1062f,-0.0323f,-0.196f,0.9689f,-0.0996f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9749f,0.1664f,-0.0073f,-0.3148f,-0.1632f,0.948f,-0.2337f,1.4291f,-0.0323f,0.2318f,0.961f,-0.0079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9666f,-0.0811f,0.1891f,0.4015f,-0.1338f,0.9541f,-0.2668f,1.1058f,-0.1592f,-0.2811f,-0.9349f,-0.1264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9675f,-0.1534f,0.1371f,0.3473f,-0.1339f,0.9775f,0.1614f,1.4255f,-0.1594f,0.1403f,-0.9661f,-0.0558f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}