# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(l_1) {transformation: [-0.99f,0f,0f,-0.1082f,0f,1f,0f,1.528f,0f,0f,-1f,0.2107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.99f,0f,0f,0.1082f,0f,1f,0f,1.528f,0f,0f,-1f,0.2106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.572f,0f,0f,-1.001f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,-0.0033f,0f,-0.1238f,-0.0027f,0.8f,0f,1.5656f,0f,0f,-1f,0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.99f,0.0033f,0f,0.1237f,0.0027f,0.8f,0f,1.5656f,0f,0f,-1f,0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4501f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4278f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4535f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.0338f,0f,1f,0f,1.4063f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1f,0f,1.406f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,0.999f,0.0436f,1.1623f,0f,0.0436f,-0.998f,-0.1007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.9848f,0.1736f,1.5162f,0f,0.1736f,-0.9848f,-0.0383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9739f,0.1539f,0.0637f,-0.3719f,-0.163f,0.9579f,0.1888f,1.1063f,-0.0323f,-0.196f,0.9689f,-0.1001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9749f,0.1664f,-0.0073f,-0.3148f,-0.1632f,0.948f,-0.2337f,1.4292f,-0.0323f,0.2318f,0.961f,-0.0083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9709f,-0.0855f,0.1628f,0.4015f,-0.1301f,0.9554f,-0.2638f,1.1056f,-0.1335f,-0.2752f,-0.9407f,-0.1282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9719f,-0.1463f,0.1114f,0.3502f,-0.1303f,0.9774f,0.1647f,1.4252f,-0.1336f,0.1481f,-0.9689f,-0.055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}