# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(l_1) {transformation: [-0.99f,0f,0f,-0.1083f,0f,1f,0f,1.5281f,0f,0f,-1f,0.2106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.99f,0f,0f,0.1083f,0f,1f,0f,1.5281f,0f,0f,-1f,0.2106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.5719f,0f,0f,-1.001f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,-0.0043f,0f,-0.1238f,-0.0035f,0.8f,0f,1.5656f,0f,0f,-1f,0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.99f,0.0043f,0f,0.1237f,0.0035f,0.8f,0f,1.5656f,0f,0f,-1f,0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.45f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4281f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4532f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.034f,0f,1f,0f,1.4063f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1f,0f,1.4062f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,0.999f,0.0436f,1.1618f,0f,0.0436f,-0.998f,-0.1001f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.9848f,0.1736f,1.5158f,0f,0.1736f,-0.9848f,-0.0377f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9739f,0.1539f,0.0637f,-0.3719f,-0.163f,0.9579f,0.1888f,1.1063f,-0.0323f,-0.196f,0.9689f,-0.1003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9749f,0.1664f,-0.0073f,-0.3148f,-0.1632f,0.948f,-0.2337f,1.4293f,-0.0323f,0.2318f,0.961f,-0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9733f,-0.0882f,0.1464f,0.4014f,-0.1279f,0.9562f,-0.2619f,1.1054f,-0.1174f,-0.2715f,-0.9439f,-0.1294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9743f,-0.1418f,0.0954f,0.352f,-0.128f,0.9773f,0.1668f,1.425f,-0.1175f,0.1529f,-0.9702f,-0.0545f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}