# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(hair1) {transformation: [-2f,0f,0f,-0.75f,0f,0.9175f,0.348f,1.3181f,0f,0.3977f,-0.8028f,-0.4576f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hair4) {transformation: [-2f,0f,0f,-0.75f,0f,0.9175f,0.348f,1.4383f,0f,0.3977f,-0.8028f,-0.4233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hair2) {transformation: [1.5f,0f,0f,0.5625f,0f,1.0722f,-0.4498f,1.0005f,0f,0.6426f,0.7505f,-0.5971f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(hair3) {transformation: [1.125f,0f,0f,0.4375f,0f,1.0722f,-0.4498f,0.657f,0f,0.6426f,0.7505f,-0.7602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(layer) {transformation: [-1f,0f,0f,0f,0f,0.9616f,0.2746f,1.5156f,0f,0.2746f,-0.9616f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9616f,0.2746f,1.5156f,0f,0.2746f,-0.9616f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9989f,-0.0463f,-0.0021f,0.1361f,-0.0463f,0.9979f,0.0463f,0.3914f,0f,0.0463f,-0.9989f,-0.1076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9989f,-0.0463f,0.0021f,0.1188f,-0.0463f,0.9979f,-0.0463f,0.7656f,0f,-0.0463f,-0.9989f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.8402f,-0.4818f,0.2488f,-0.361f,-0.3835f,-0.2036f,0.9008f,1.2165f,-0.3834f,-0.8523f,-0.3559f,0.0895f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8402f,-0.0358f,0.541f,-0.3584f,-0.3835f,0.6662f,0.6396f,1.4365f,-0.3834f,-0.7449f,0.5461f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.75f,0f,0f,-0.0438f,0f,-0.75f,0f,0.8216f,0f,0f,-0.75f,0.625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.828f,0.4659f,0.312f,0.3553f,-0.4564f,-0.2369f,-0.8577f,1.2368f,-0.3257f,-0.8526f,0.4088f,0.1104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.828f,-0.0334f,0.5597f,0.3418f,-0.4564f,0.62f,-0.6382f,1.4658f,-0.3257f,-0.7839f,-0.5286f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9989f,0.0463f,0.0021f,-0.1486f,0.0463f,0.9979f,0.0463f,0.3914f,0f,0.0463f,-0.9989f,-0.1076f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9989f,0.0463f,-0.0021f,-0.1312f,0.0463f,0.9979f,-0.0463f,0.7656f,0f,-0.0463f,-0.9989f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}