# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.0008f,0.0168f,-0.0056f,0.011f,0.0177f,0.9504f,-0.3137f,1.3262f,0f,-0.3137f,-0.9506f,-0.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-1.0116f,0.0172f,-0.0057f,-0.1046f,0.0179f,0.9703f,-0.3203f,1.5421f,0f,-0.3203f,-0.9705f,-0.149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9898f,0.0168f,-0.0056f,0.011f,0.0175f,0.9495f,-0.3134f,1.3252f,0f,-0.3134f,-0.9496f,-0.3395f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-1.0116f,0.0172f,-0.0057f,0.1339f,0.0179f,0.9703f,-0.3203f,1.5374f,0f,-0.3203f,-0.9705f,-0.1504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9898f,0.0168f,-0.0056f,0.1382f,0.0175f,0.9495f,-0.3134f,1.5176f,0f,-0.3134f,-0.9496f,-0.1487f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9898f,0.0574f,-0.0058f,0.014f,0.0175f,3.2351f,-0.3272f,1.4968f,0f,-1.0679f,-0.9916f,-0.3929f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9898f,0.0168f,-0.0056f,0.011f,0.0175f,0.9495f,-0.3134f,1.3262f,0f,-0.3134f,-0.9496f,-0.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9897f,0.0233f,-0.0056f,-0.1091f,0.0251f,0.7594f,-0.3134f,1.5298f,-0.0025f,-0.2507f,-0.9496f,-0.1168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,0.0036f,-0.0056f,0.1383f,0.01f,0.7597f,-0.3134f,1.5254f,0.0025f,-0.2507f,-0.9496f,-0.1168f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9898f,0.0168f,-0.0056f,0.0118f,0.0175f,0.9495f,-0.3134f,1.3687f,0f,-0.3134f,-0.9496f,-0.3506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9898f,0.0168f,-0.0056f,0.0114f,0.0175f,0.9495f,-0.3134f,1.3473f,0f,-0.3134f,-0.9496f,-0.3435f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9898f,0.0168f,-0.0056f,0.0118f,0.0175f,0.9495f,-0.3134f,1.3707f,0f,-0.3134f,-0.9496f,-0.3512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9898f,0.0168f,-0.0056f,0.0115f,0.0175f,0.9495f,-0.3134f,1.3559f,0f,-0.3134f,-0.9496f,-0.3463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9898f,0.02f,-0.0056f,0.046f,0.0175f,1.1257f,-0.3134f,1.3802f,0f,-0.3716f,-0.9496f,-0.1572f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9898f,0.02f,-0.0056f,0.0339f,0.0175f,1.1257f,-0.3134f,1.3958f,0f,-0.3716f,-0.9496f,-0.1623f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9898f,0.0168f,-0.0056f,0.011f,0.0175f,0.9495f,-0.3134f,1.3262f,0f,-0.3134f,-0.9496f,-0.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9998f,0.0168f,-0.0056f,0.011f,0.0177f,0.9495f,-0.3134f,1.3262f,0f,-0.3134f,-0.9496f,-0.3366f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.996f,-0.0717f,-0.0305f,0.176f,-0.035f,0.7626f,-0.6446f,0.8128f,0.0693f,-0.6426f,-0.7629f,0.4102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9854f,-0.1641f,0.0066f,0.1198f,-0.0674f,0.3682f,-0.9264f,0.9104f,0.1496f,-0.9152f,-0.3738f,0.0839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9886f,0.0226f,-0.0168f,0.0019f,0.026f,0.5302f,-0.8466f,1.0768f,-0.0101f,-0.8476f,-0.53f,-0.2299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9896f,0.027f,-0.0081f,0.0116f,0.026f,0.7881f,-0.615f,1.36f,-0.0101f,-0.615f,-0.7884f,-0.4509f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7637f,0.1249f,0.4561f,-0.4938f,-0.4029f,-0.0093f,0.8766f,1.1234f,0.1009f,-0.9817f,0.0487f,-0.1474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8522f,0.4186f,0.2775f,-0.3464f,-0.4804f,0.5221f,0.6894f,1.3115f,0.1452f,-0.7296f,0.6526f,-0.39f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8458f,-0.031f,0.3037f,0.4251f,-0.2753f,0.0447f,-0.9432f,1.1475f,0.0174f,-0.9952f,-0.0426f,-0.129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9371f,-0.2155f,0.2316f,0.3538f,-0.3163f,0.5698f,-0.7488f,1.357f,0.0334f,-0.7922f,-0.6033f,-0.3766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9977f,-0.0336f,-0.0393f,-0.1389f,0.0035f,0.7118f,-0.7012f,0.8316f,0.052f,-0.7013f,-0.7106f,0.3912f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9981f,0.0393f,-0.0198f,-0.1276f,0.031f,0.3144f,-0.948f,0.9121f,-0.0308f,-0.9484f,-0.3147f,0.1087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.13958999641454,"rx":14.073634433716132},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.83129551658885,"rx":14.383703292494154}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities