# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9993f,-0.0577f,0.0091f,-0.0369f,-0.0584f,0.9872f,-0.155f,1.3362f,0f,-0.1553f,-0.9889f,-0.3222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.1538f,-0.0578f,0.9862f,-0.1549f,1.479f,0f,-0.1551f,-0.9879f,-0.0989f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.0369f,-0.0578f,0.9862f,-0.1549f,1.3355f,0f,-0.1551f,-0.9879f,-0.3268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9883f,-0.0577f,0.0091f,0.0624f,-0.0578f,0.9862f,-0.1549f,1.4914f,0f,-0.1551f,-0.9879f,-0.1008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9883f,-0.0577f,0.0091f,0.0773f,-0.0578f,0.9862f,-0.1549f,1.5035f,0f,-0.1551f,-0.9879f,-0.107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.0472f,-0.0578f,0.9862f,-0.155f,1.5118f,0f,-0.1551f,-0.9889f,-0.3498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.0369f,-0.0578f,0.9862f,-0.1549f,1.3362f,0f,-0.1551f,-0.9879f,-0.3222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9883f,-0.0461f,0.0091f,-0.1721f,-0.0578f,0.789f,-0.1549f,1.5283f,0f,-0.1241f,-0.9879f,-0.0783f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9882f,-0.048f,0.0091f,0.075f,-0.0593f,0.7889f,-0.1549f,1.5427f,0.0002f,-0.1241f,-0.9879f,-0.0783f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.0398f,-0.0578f,0.9862f,-0.1549f,1.3855f,0f,-0.1551f,-0.9879f,-0.33f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.038f,-0.0578f,0.9862f,-0.1549f,1.3547f,0f,-0.1551f,-0.9879f,-0.3251f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.0396f,-0.0578f,0.9862f,-0.1549f,1.3825f,0f,-0.1551f,-0.9879f,-0.3294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.0387f,-0.0578f,0.9862f,-0.1549f,1.367f,0f,-0.1551f,-0.9879f,-0.327f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9883f,-0.0686f,0.0091f,-0.0044f,-0.0578f,1.1736f,-0.1549f,1.3634f,0f,-0.1846f,-0.9879f,-0.1364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9883f,-0.0686f,0.0091f,-0.0168f,-0.0578f,1.1736f,-0.1549f,1.3627f,0f,-0.1846f,-0.9879f,-0.1364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9883f,-0.0577f,0.0091f,-0.0369f,-0.0578f,0.9862f,-0.1549f,1.3362f,0f,-0.1551f,-0.9879f,-0.3222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9983f,-0.0577f,0.0091f,-0.0369f,-0.0584f,0.9862f,-0.1549f,1.3362f,0f,-0.1551f,-0.9879f,-0.3222f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.915f,-0.3842f,-0.1159f,0.208f,-0.2665f,0.798f,-0.5391f,0.8178f,0.2997f,-0.4638f,-0.8334f,0.3864f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9361f,-0.3348f,0.0991f,0.096f,-0.2424f,0.4201f,-0.8736f,0.9349f,0.2509f,-0.8435f,-0.4744f,0.0816f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9871f,-0.0354f,0.0517f,-0.0208f,-0.0618f,0.4988f,-0.8636f,1.0994f,0.0047f,-0.866f,-0.4995f,-0.2032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9881f,-0.051f,0.0365f,-0.0391f,-0.0619f,0.7644f,-0.6418f,1.3741f,0.0047f,-0.6428f,-0.766f,-0.4342f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7737f,0.2094f,0.3998f,-0.518f,-0.372f,0.0804f,0.8906f,1.0944f,0.137f,-0.964f,0.1602f,-0.0975f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8587f,0.437f,0.2241f,-0.365f,-0.451f,0.5247f,0.7071f,1.2836f,0.1934f,-0.7168f,0.6542f,-0.3357f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7783f,-0.1071f,0.4665f,0.419f,-0.412f,-0.0958f,-0.875f,1.1829f,0.129f,-0.9851f,0.044f,-0.06f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.8865f,-0.3306f,0.2887f,0.3078f,-0.4289f,0.5146f,-0.7321f,1.3743f,0.0975f,-0.7903f,-0.5991f,-0.3074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9787f,0.1903f,0.0636f,-0.1831f,0.0843f,0.6781f,-0.7289f,0.8612f,-0.1817f,-0.7097f,-0.6804f,0.404f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9885f,0.1377f,-0.0469f,-0.1432f,0.0731f,0.1933f,-0.9775f,0.9057f,-0.1252f,-0.9714f,-0.2008f,0.1162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":204.06577724422226,"rx":13.997655854006185},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.46163931949934,"rx":14.18403838486638}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities