# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9997f,-0.05f,0.0114f,-0.0301f,-0.0513f,0.9746f,-0.2224f,1.2919f,0f,-0.2227f,-0.9759f,-0.364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9887f,-0.05f,0.0114f,-0.1456f,-0.0508f,0.9737f,-0.2222f,1.4491f,0f,-0.2225f,-0.9749f,-0.1512f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9887f,-0.05f,0.0114f,-0.0301f,-0.0508f,0.9737f,-0.2222f,1.2908f,0f,-0.2225f,-0.9749f,-0.3686f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9887f,-0.05f,0.0114f,0.0707f,-0.0508f,0.9737f,-0.2222f,1.4598f,0f,-0.2225f,-0.9749f,-0.153f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9887f,-0.05f,0.0114f,0.0845f,-0.0508f,0.9737f,-0.2222f,1.4727f,0f,-0.2225f,-0.9749f,-0.1603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9887f,-0.05f,0.0114f,-0.0391f,-0.0508f,0.9737f,-0.2224f,1.4672f,0f,-0.2225f,-0.9759f,-0.4041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9887f,-0.05f,0.0114f,-0.0301f,-0.0508f,0.9737f,-0.2222f,1.2919f,0f,-0.2225f,-0.9749f,-0.364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9887f,-0.04f,0.0114f,-0.1648f,-0.0508f,0.7789f,-0.2222f,1.5011f,0f,-0.178f,-0.9749f,-0.1344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9881f,-0.0526f,0.0114f,0.0824f,-0.0607f,0.7782f,-0.2222f,1.5138f,0.0023f,-0.1779f,-0.9749f,-0.1344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9887f,-0.05f,0.0114f,-0.0327f,-0.0508f,0.9737f,-0.2222f,1.3415f,0f,-0.2225f,-0.9749f,-0.3754f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9887f,-0.05f,0.0114f,-0.0311f,-0.0508f,0.9737f,-0.2222f,1.3101f,0f,-0.2225f,-0.9749f,-0.3682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9887f,-0.05f,0.0114f,-0.0325f,-0.0508f,0.9737f,-0.2222f,1.3375f,0f,-0.2225f,-0.9749f,-0.3744f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9887f,-0.05f,0.0114f,-0.0317f,-0.0508f,0.9737f,-0.2222f,1.3223f,0f,-0.2225f,-0.9749f,-0.3709f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9887f,-0.0595f,0.0114f,0.0019f,-0.0508f,1.1587f,-0.2222f,1.3315f,0f,-0.2647f,-0.9749f,-0.1804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9887f,-0.0595f,0.0114f,-0.0104f,-0.0508f,1.1587f,-0.2222f,1.3309f,0f,-0.2647f,-0.9749f,-0.1804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9887f,-0.05f,0.0114f,-0.0301f,-0.0508f,0.9737f,-0.2222f,1.2919f,0f,-0.2225f,-0.9749f,-0.364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9987f,-0.05f,0.0114f,-0.0301f,-0.0513f,0.9737f,-0.2222f,1.2919f,0f,-0.2225f,-0.9749f,-0.364f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9234f,-0.3718f,-0.0852f,0.2066f,-0.2321f,0.7251f,-0.647f,0.8218f,0.3024f,-0.5792f,-0.7567f,0.3808f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9412f,-0.3219f,0.0939f,0.0989f,-0.2138f,0.3615f,-0.9066f,0.9177f,0.2579f,-0.875f,-0.4091f,0.0672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9882f,0.0024f,0.0409f,-0.0274f,-0.0338f,0.5005f,-0.8642f,1.0466f,-0.0223f,-0.8657f,-0.4995f,-0.2475f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9892f,-0.0118f,0.0392f,-0.0317f,-0.0339f,0.7662f,-0.6417f,1.322f,-0.0223f,-0.6425f,-0.766f,-0.4784f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7695f,0.2282f,0.4001f,-0.5177f,-0.3791f,0.1073f,0.8839f,1.0408f,0.1409f,-0.957f,0.1936f,-0.1417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8531f,0.4527f,0.2141f,-0.3594f,-0.4602f,0.5433f,0.6869f,1.2361f,0.1966f,-0.6928f,0.6786f,-0.3713f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7866f,-0.1807f,0.4246f,0.425f,-0.4044f,0.1257f,-0.8764f,1.102f,0.0986f,-0.9725f,-0.184f,-0.1077f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.8927f,-0.3246f,0.2758f,0.3161f,-0.4211f,0.5724f,-0.6937f,1.3116f,0.0712f,-0.7521f,-0.6488f,-0.3411f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9962f,0.0003f,0.0752f,-0.1386f,-0.0489f,0.7589f,-0.6482f,0.8166f,-0.0571f,-0.651f,-0.7566f,0.3862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9969f,-0.0113f,0.0638f,-0.1411f,-0.0644f,0.3011f,-0.9506f,0.8931f,-0.0082f,-0.9535f,-0.3006f,0.1023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":203.7194311750855,"rx":10.242735765239459},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.7020446707938,"rx":13.980327181822291}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities