# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.0008f,-0.018f,0.0022f,-0.0118f,-0.0182f,0.9933f,-0.1223f,1.3578f,0f,-0.1223f,-0.9935f,-0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9898f,-0.018f,0.0022f,-0.1203f,-0.018f,0.9923f,-0.1221f,1.4948f,0f,-0.1222f,-0.9925f,-0.0723f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9898f,-0.018f,0.0022f,-0.0118f,-0.018f,0.9923f,-0.1221f,1.3573f,0f,-0.1222f,-0.9925f,-0.3055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9898f,-0.018f,0.0022f,0.0962f,-0.018f,0.9923f,-0.1221f,1.4985f,0f,-0.1222f,-0.9925f,-0.0742f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9898f,-0.018f,0.0022f,0.1091f,-0.018f,0.9923f,-0.1221f,1.5131f,0f,-0.1222f,-0.9925f,-0.0803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9898f,-0.018f,0.0022f,-0.0151f,-0.018f,0.9923f,-0.1223f,1.5392f,0f,-0.1222f,-0.9935f,-0.3231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9898f,-0.018f,0.0022f,-0.0118f,-0.018f,0.9923f,-0.1221f,1.3578f,0f,-0.1222f,-0.9925f,-0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9898f,-0.0144f,0.0022f,-0.139f,-0.018f,0.7939f,-0.1221f,1.5469f,0f,-0.0977f,-0.9925f,-0.0504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9894f,-0.0335f,0.0022f,0.1084f,-0.0333f,0.7934f,-0.1221f,1.5514f,0.0019f,-0.0977f,-0.9925f,-0.0504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9898f,-0.018f,0.0022f,-0.0128f,-0.018f,0.9923f,-0.1221f,1.4097f,0f,-0.1222f,-0.9925f,-0.3072f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9898f,-0.018f,0.0022f,-0.0122f,-0.018f,0.9923f,-0.1221f,1.3764f,0f,-0.1222f,-0.9925f,-0.303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9898f,-0.018f,0.0022f,-0.0127f,-0.018f,0.9923f,-0.1221f,1.4044f,0f,-0.1222f,-0.9925f,-0.3065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9898f,-0.018f,0.0022f,-0.0124f,-0.018f,0.9923f,-0.1221f,1.3889f,0f,-0.1222f,-0.9925f,-0.3046f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9898f,-0.0214f,0.0022f,0.0218f,-0.018f,1.1809f,-0.1221f,1.3775f,0f,-0.1454f,-0.9925f,-0.1142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9898f,-0.0214f,0.0022f,0.0095f,-0.018f,1.1809f,-0.1221f,1.3773f,0f,-0.1454f,-0.9925f,-0.1142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9898f,-0.018f,0.0022f,-0.0118f,-0.018f,0.9923f,-0.1221f,1.3578f,0f,-0.1222f,-0.9925f,-0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9998f,-0.018f,0.0022f,-0.0118f,-0.0181f,0.9923f,-0.1221f,1.3578f,0f,-0.1222f,-0.9925f,-0.3008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9521f,-0.2813f,-0.1117f,0.2017f,-0.1931f,0.8491f,-0.4901f,0.808f,0.2328f,-0.4465f,-0.8636f,0.3984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9574f,-0.2795f,0.0594f,0.1075f,-0.185f,0.4488f,-0.8734f,0.9349f,0.2174f,-0.8488f,-0.4814f,0.0916f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9889f,0.0137f,0.0105f,-0.0159f,-0.0022f,0.5001f,-0.8651f,1.1241f,-0.0169f,-0.8658f,-0.4995f,-0.1806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9899f,0.0093f,0.0145f,-0.0126f,-0.0022f,0.7662f,-0.6427f,1.3995f,-0.0169f,-0.6426f,-0.766f,-0.4115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7724f,0.1807f,0.4168f,-0.4896f,-0.3861f,0.1091f,0.8797f,1.1243f,0.1007f,-0.967f,0.1762f,-0.0791f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8579f,0.4219f,0.2539f,-0.3414f,-0.4681f,0.5421f,0.6825f,1.3192f,0.1518f,-0.7129f,0.6693f,-0.3157f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8162f,-0.1065f,0.3778f,0.4253f,-0.3424f,0.0021f,-0.9161f,1.201f,0.0911f,-0.9911f,-0.0337f,-0.0345f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9131f,-0.2784f,0.259f,0.3323f,-0.3717f,0.5071f,-0.7674f,1.3904f,0.0866f,-0.8149f,-0.5676f,-0.2907f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9615f,0.2703f,-0.0274f,-0.1922f,0.191f,0.6014f,-0.7746f,0.8927f,-0.1926f,-0.7516f,-0.6305f,0.4105f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9653f,0.2011f,-0.1613f,-0.1351f,0.1887f,0.1264f,-0.9729f,0.9176f,-0.175f,-0.9713f,-0.1597f,0.1232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":203.5855624088703,"rx":16.83561556475884},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.7483019794582,"rx":12.271170430094449}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities