# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.0005f,0.0262f,-0.015f,0.0187f,0.0301f,0.8686f,-0.4967f,1.3251f,0f,-0.4969f,-0.869f,-0.3354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-1.0117f,0.0267f,-0.0153f,-0.0874f,0.0305f,0.8871f,-0.5073f,1.5659f,0f,-0.5075f,-0.8875f,-0.1898f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9896f,0.0261f,-0.0149f,0.0186f,0.0298f,0.8677f,-0.4962f,1.3235f,0f,-0.4964f,-0.8681f,-0.3381f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-1.0117f,0.0267f,-0.0153f,0.1399f,0.0305f,0.8871f,-0.5073f,1.5587f,0f,-0.5075f,-0.8875f,-0.1905f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9896f,0.0261f,-0.0149f,0.1492f,0.0298f,0.8677f,-0.4962f,1.5484f,0f,-0.4964f,-0.8681f,-0.1899f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9896f,0.0894f,-0.0156f,0.0232f,0.0298f,2.9702f,-0.5183f,1.4742f,0f,-1.6993f,-0.9067f,-0.4207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9896f,0.0261f,-0.0149f,0.0187f,0.0298f,0.8677f,-0.4962f,1.3251f,0f,-0.4964f,-0.8681f,-0.3354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9893f,0.0308f,-0.0149f,-0.0978f,0.0367f,0.6938f,-0.4962f,1.5693f,-0.004f,-0.3971f,-0.8681f,-0.1598f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9897f,0.011f,-0.0149f,0.1496f,0.0229f,0.6944f,-0.4962f,1.5618f,0.004f,-0.3971f,-0.8681f,-0.1598f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9896f,0.0261f,-0.0149f,0.0198f,0.0298f,0.8677f,-0.4962f,1.3637f,0f,-0.4964f,-0.8681f,-0.3575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9896f,0.0261f,-0.0149f,0.0193f,0.0298f,0.8677f,-0.4962f,1.3462f,0f,-0.4964f,-0.8681f,-0.3474f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9896f,0.0261f,-0.0149f,0.0199f,0.0298f,0.8677f,-0.4962f,1.3658f,0f,-0.4964f,-0.8681f,-0.3586f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9896f,0.0261f,-0.0149f,0.0195f,0.0298f,0.8677f,-0.4962f,1.3522f,0f,-0.4964f,-0.8681f,-0.3508f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9896f,0.0308f,-0.0149f,0.0553f,0.0298f,1.022f,-0.4962f,1.4125f,0f,-0.5847f,-0.8681f,-0.17f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9896f,0.0308f,-0.0149f,0.0431f,0.0298f,1.022f,-0.4962f,1.4172f,0f,-0.5847f,-0.8681f,-0.1725f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9896f,0.0261f,-0.0149f,0.0187f,0.0298f,0.8677f,-0.4962f,1.3251f,0f,-0.4964f,-0.8681f,-0.3354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9995f,0.0261f,-0.0149f,0.0187f,0.0301f,0.8677f,-0.4962f,1.3251f,0f,-0.4964f,-0.8681f,-0.3354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9838f,-0.1548f,-0.0789f,0.1919f,-0.0755f,0.7901f,-0.6069f,0.807f,0.1562f,-0.5927f,-0.7899f,0.4023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.977f,-0.2084f,0.0072f,0.1205f,-0.0893f,0.3879f,-0.9165f,0.9117f,0.1882f,-0.8979f,-0.3976f,0.0813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9885f,0.0187f,-0.0266f,0.01f,0.0321f,0.5023f,-0.8632f,1.0791f,-0.0028f,-0.8645f,-0.5021f,-0.2224f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9895f,0.0267f,-0.0186f,0.0196f,0.0321f,0.7675f,-0.6402f,1.355f,-0.0028f,-0.6404f,-0.768f,-0.4525f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.74f,0.1197f,0.5054f,-0.4628f,-0.4349f,-0.1059f,0.8501f,1.1113f,0.1379f,-0.9765f,-0.0312f,-0.1144f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8525f,0.4127f,0.2855f,-0.3174f,-0.4819f,0.5185f,0.6911f,1.2982f,0.1385f,-0.7355f,0.6473f,-0.3591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8511f,-0.0384f,0.2839f,0.4296f,-0.2587f,0.1055f,-0.9443f,1.074f,0.0088f,-0.9909f,-0.1027f,-0.1376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9408f,-0.2107f,0.2211f,0.3601f,-0.3053f,0.5784f,-0.7469f,1.2861f,0.0335f,-0.7872f,-0.6096f,-0.3834f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9943f,0.0912f,-0.0355f,-0.1529f,0.0879f,0.676f,-0.7304f,0.8547f,-0.0422f,-0.731f,-0.6807f,0.3969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9914f,0.098f,-0.075f,-0.1251f,0.0964f,0.2376f,-0.9657f,0.9124f,-0.0765f,-0.9664f,-0.2447f,0.1099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.7691629857795,"rx":14.437048005471153},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.1234433804197,"rx":14.313762753537523}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities