# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.0004f,-0.0318f,0.016f,-0.0203f,-0.0356f,0.8935f,-0.4499f,1.2755f,0f,-0.4502f,-0.894f,-0.3492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9894f,-0.0318f,0.016f,-0.1413f,-0.0352f,0.8926f,-0.4495f,1.4883f,0f,-0.4498f,-0.8932f,-0.1856f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9894f,-0.0318f,0.016f,-0.0202f,-0.0352f,0.8926f,-0.4495f,1.2734f,0f,-0.4498f,-0.8932f,-0.3534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9894f,-0.0318f,0.016f,0.085f,-0.0352f,0.8926f,-0.4495f,1.4955f,0f,-0.4498f,-0.8932f,-0.187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9894f,-0.0318f,0.016f,0.0956f,-0.0352f,0.8926f,-0.4495f,1.4982f,0f,-0.4498f,-0.8932f,-0.1934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9894f,-0.0672f,0.0163f,-0.0256f,-0.0352f,1.8884f,-0.4589f,1.4241f,0f,-0.9515f,-0.9119f,-0.424f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9894f,-0.0318f,0.016f,-0.0203f,-0.0352f,0.8926f,-0.4495f,1.2755f,0f,-0.4498f,-0.8932f,-0.3492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9894f,-0.0254f,0.016f,-0.1532f,-0.0352f,0.7141f,-0.4495f,1.5293f,0f,-0.3598f,-0.8932f,-0.1748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9893f,-0.0269f,0.016f,0.0942f,-0.0363f,0.714f,-0.4495f,1.5381f,0.0006f,-0.3598f,-0.8932f,-0.1748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9894f,-0.0318f,0.016f,-0.0217f,-0.0352f,0.8926f,-0.4495f,1.3156f,0f,-0.4498f,-0.8932f,-0.3693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9894f,-0.0318f,0.016f,-0.0209f,-0.0352f,0.8926f,-0.4495f,1.2925f,0f,-0.4498f,-0.8932f,-0.3577f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9894f,-0.0318f,0.016f,-0.0218f,-0.0352f,0.8926f,-0.4495f,1.3174f,0f,-0.4498f,-0.8932f,-0.3702f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9894f,-0.0318f,0.016f,-0.0213f,-0.0352f,0.8926f,-0.4495f,1.3035f,0f,-0.4498f,-0.8932f,-0.3632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9894f,-0.0379f,0.016f,0.0108f,-0.0352f,1.0631f,-0.4495f,1.3577f,0f,-0.5357f,-0.8932f,-0.18f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9894f,-0.0379f,0.016f,-0.0019f,-0.0352f,1.0631f,-0.4495f,1.368f,0f,-0.5357f,-0.8932f,-0.1855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9894f,-0.0318f,0.016f,-0.0203f,-0.0352f,0.8926f,-0.4495f,1.2755f,0f,-0.4498f,-0.8932f,-0.3492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9994f,-0.0318f,0.016f,-0.0203f,-0.0356f,0.8926f,-0.4495f,1.2755f,0f,-0.4498f,-0.8932f,-0.3492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9046f,-0.407f,-0.1195f,0.2159f,-0.2371f,0.719f,-0.652f,0.8189f,0.3514f,-0.563f,-0.7477f,0.4012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9349f,-0.3428f,0.0819f,0.1006f,-0.2096f,0.3548f,-0.9102f,0.9124f,0.283f,-0.8698f,-0.4035f,0.0896f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9885f,0.0135f,0.0273f,-0.0225f,-0.0175f,0.4744f,-0.8792f,1.035f,-0.0246f,-0.8802f,-0.4735f,-0.2249f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9895f,0.0034f,0.0303f,-0.0213f,-0.0175f,0.7468f,-0.6648f,1.3034f,-0.0246f,-0.665f,-0.7464f,-0.4639f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7559f,0.2358f,0.4284f,-0.5157f,-0.3881f,0.0037f,0.8852f,1.0625f,0.1838f,-0.9612f,0.1076f,-0.1114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8364f,0.4735f,0.234f,-0.35f,-0.4659f,0.4563f,0.7438f,1.2287f,0.2479f,-0.74f,0.6084f,-0.3581f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8094f,-0.0955f,0.3983f,0.4148f,-0.3548f,-0.0616f,-0.9078f,1.1227f,0.1044f,-0.99f,0.0272f,-0.0721f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9106f,-0.274f,0.2721f,0.3229f,-0.3777f,0.4825f,-0.7799f,1.3044f,0.0866f,-0.8311f,-0.544f,-0.3343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9943f,0.0517f,0.0823f,-0.141f,-0.0166f,0.7446f,-0.6661f,0.8249f,-0.0956f,-0.6653f,-0.7402f,0.4134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9981f,0.0085f,0.0413f,-0.1379f,-0.0377f,0.2638f,-0.963f,0.8903f,-0.0188f,-0.9645f,-0.2627f,0.1268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":204.0102183898626,"rx":9.919934535978994},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.76844170323693,"rx":13.767066855947633}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities