# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9972f,0.0849f,-0.0181f,0.0518f,0.0868f,0.9754f,-0.2075f,1.3002f,0f,-0.2082f,-0.9791f,-0.3553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9863f,0.0848f,-0.018f,-0.0371f,0.0858f,0.9744f,-0.2073f,1.4638f,0f,-0.208f,-0.9781f,-0.1391f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9863f,0.0848f,-0.018f,0.0517f,0.0858f,0.9744f,-0.2073f,1.2993f,0f,-0.208f,-0.9781f,-0.3599f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9863f,0.0848f,-0.018f,0.1786f,0.0858f,0.9744f,-0.2073f,1.4446f,0f,-0.208f,-0.9781f,-0.1409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9863f,0.0848f,-0.018f,0.19f,0.0858f,0.9744f,-0.2073f,1.4605f,0f,-0.208f,-0.9781f,-0.149f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9863f,0.0848f,-0.0181f,0.0678f,0.0858f,0.9744f,-0.2075f,1.4848f,0f,-0.208f,-0.9791f,-0.3947f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9863f,0.0848f,-0.018f,0.0518f,0.0858f,0.9744f,-0.2073f,1.3002f,0f,-0.208f,-0.9781f,-0.3553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9863f,0.0678f,-0.018f,-0.0531f,0.0858f,0.7796f,-0.2073f,1.5226f,0f,-0.1664f,-0.9781f,-0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9875f,0.0477f,-0.018f,0.1935f,0.0699f,0.7811f,-0.2073f,1.5012f,0.0034f,-0.1664f,-0.9781f,-0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9863f,0.0848f,-0.018f,0.0565f,0.0858f,0.9744f,-0.2073f,1.3544f,0f,-0.208f,-0.9781f,-0.3669f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9863f,0.0848f,-0.018f,0.0534f,0.0858f,0.9744f,-0.2073f,1.3185f,0f,-0.208f,-0.9781f,-0.3591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9863f,0.0848f,-0.018f,0.0558f,0.0858f,0.9744f,-0.2073f,1.3459f,0f,-0.208f,-0.9781f,-0.365f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9863f,0.0848f,-0.018f,0.0544f,0.0858f,0.9744f,-0.2073f,1.3307f,0f,-0.208f,-0.9781f,-0.3617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9863f,0.1009f,-0.018f,0.0887f,0.0858f,1.1596f,-0.2073f,1.3324f,0f,-0.2476f,-0.9781f,-0.1711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9863f,0.1009f,-0.018f,0.0764f,0.0858f,1.1596f,-0.2073f,1.3334f,0f,-0.2476f,-0.9781f,-0.1711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9863f,0.0848f,-0.018f,0.0518f,0.0858f,0.9744f,-0.2073f,1.3002f,0f,-0.208f,-0.9781f,-0.3553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9962f,0.0848f,-0.018f,0.0518f,0.0867f,0.9744f,-0.2073f,1.3002f,0f,-0.208f,-0.9781f,-0.3553f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9958f,-0.0215f,-0.0774f,0.1834f,0.0357f,0.7453f,-0.6645f,0.8038f,0.0718f,-0.6661f,-0.7422f,0.4096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9872f,-0.1414f,-0.0583f,0.133f,0.0055f,0.348f,-0.9365f,0.8942f,0.1527f,-0.9268f,-0.3428f,0.0803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9846f,0.0557f,-0.0767f,0.0263f,0.0933f,0.497f,-0.8617f,1.0581f,-0.0097f,-0.866f,-0.4995f,-0.2382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9855f,0.0786f,-0.0531f,0.0546f,0.0934f,0.7621f,-0.6406f,1.332f,-0.0098f,-0.6427f,-0.766f,-0.4692f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7583f,0.1291f,0.4664f,-0.4227f,-0.4221f,0.1154f,0.8572f,1.0996f,0.0504f,-0.9745f,0.1624f,-0.1218f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8429f,0.4043f,0.3234f,-0.2797f,-0.5086f,0.5332f,0.6601f,1.2912f,0.0954f,-0.7296f,0.6617f,-0.3643f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8729f,0.0587f,0.1798f,0.4345f,-0.1577f,0.0985f,-0.9723f,1.0569f,-0.0651f,-0.9904f,-0.0767f,-0.0933f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9628f,-0.1357f,0.182f,0.391f,-0.2289f,0.6073f,-0.7514f,1.2783f,-0.0046f,-0.7819f,-0.6169f,-0.3369f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9948f,0.019f,-0.0903f,-0.1307f,0.0786f,0.6847f,-0.7235f,0.8454f,0.0485f,-0.7284f,-0.6831f,0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9931f,0.0622f,-0.0891f,-0.1136f,0.1027f,0.2735f,-0.9555f,0.9138f,-0.0348f,-0.9598f,-0.2777f,0.1052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.13802150166026,"rx":14.176979427889027},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.85321855751903,"rx":14.383317669608722}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities