# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9976f,0.0812f,-0.0169f,0.0498f,0.083f,0.9766f,-0.2034f,1.3032f,0f,-0.2041f,-0.98f,-0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9866f,0.0812f,-0.0169f,-0.0381f,0.0821f,0.9756f,-0.2032f,1.4648f,0f,-0.2039f,-0.979f,-0.1358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9866f,0.0812f,-0.0169f,0.0497f,0.0821f,0.9756f,-0.2032f,1.3023f,0f,-0.2039f,-0.979f,-0.3573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9866f,0.0812f,-0.0169f,0.1777f,0.0821f,0.9756f,-0.2032f,1.4465f,0f,-0.2039f,-0.979f,-0.1376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9866f,0.0812f,-0.0169f,0.1872f,0.0821f,0.9756f,-0.2032f,1.4632f,0f,-0.2039f,-0.979f,-0.1457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9866f,0.0812f,-0.0169f,0.0654f,0.0821f,0.9756f,-0.2034f,1.4915f,0f,-0.2039f,-0.98f,-0.3921f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9866f,0.0812f,-0.0169f,0.0498f,0.0821f,0.9756f,-0.2032f,1.3032f,0f,-0.2039f,-0.979f,-0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9866f,0.0649f,-0.0169f,-0.056f,0.0821f,0.7805f,-0.2032f,1.5242f,0f,-0.1631f,-0.979f,-0.1191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9865f,0.0668f,-0.0169f,0.1906f,0.0835f,0.7803f,-0.2032f,1.5037f,-0.0003f,-0.1631f,-0.979f,-0.1191f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9866f,0.0812f,-0.0169f,0.0544f,0.0821f,0.9756f,-0.2032f,1.3593f,0f,-0.2039f,-0.979f,-0.3645f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9866f,0.0812f,-0.0169f,0.0513f,0.0821f,0.9756f,-0.2032f,1.3215f,0f,-0.2039f,-0.979f,-0.3565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9866f,0.0812f,-0.0169f,0.0536f,0.0821f,0.9756f,-0.2032f,1.349f,0f,-0.2039f,-0.979f,-0.3622f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9866f,0.0812f,-0.0169f,0.0523f,0.0821f,0.9756f,-0.2032f,1.3337f,0f,-0.2039f,-0.979f,-0.3591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9866f,0.0966f,-0.0169f,0.0865f,0.0821f,1.161f,-0.2032f,1.3347f,0f,-0.2426f,-0.979f,-0.1684f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9866f,0.0966f,-0.0169f,0.0742f,0.0821f,1.161f,-0.2032f,1.3358f,0f,-0.2426f,-0.979f,-0.1684f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9866f,0.0812f,-0.0169f,0.0498f,0.0821f,0.9756f,-0.2032f,1.3032f,0f,-0.2039f,-0.979f,-0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9966f,0.0812f,-0.0169f,0.0498f,0.0829f,0.9756f,-0.2032f,1.3032f,0f,-0.2039f,-0.979f,-0.3527f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9956f,-0.0307f,-0.0773f,0.1841f,0.0279f,0.7525f,-0.6567f,0.8037f,0.0781f,-0.6575f,-0.7492f,0.4094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9869f,-0.1459f,-0.0536f,0.1323f,-0.0014f,0.3534f,-0.9345f,0.8959f,0.1553f,-0.924f,-0.3489f,0.0809f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9861f,0.0308f,-0.0702f,0.0334f,0.0754f,0.4991f,-0.8623f,1.0608f,0.0084f,-0.866f,-0.4995f,-0.2355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9871f,0.053f,-0.0555f,0.0524f,0.0755f,0.7642f,-0.6404f,1.3355f,0.0084f,-0.6427f,-0.766f,-0.4665f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7609f,0.1233f,0.4626f,-0.4221f,-0.4165f,0.0888f,0.8639f,1.1091f,0.058f,-0.978f,0.1358f,-0.1146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8461f,0.3976f,0.3233f,-0.2814f,-0.5013f,0.5147f,0.6801f,1.2945f,0.105f,-0.7464f,0.6412f,-0.3632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.872f,0.0459f,0.1883f,0.4348f,-0.1646f,0.1265f,-0.9676f,1.0633f,-0.0591f,-0.9882f,-0.1061f,-0.0904f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9616f,-0.1413f,0.184f,0.3894f,-0.2339f,0.6035f,-0.7529f,1.2835f,-0.0007f,-0.7839f,-0.6144f,-0.3347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9947f,0.0311f,-0.0876f,-0.1338f,0.0851f,0.6805f,-0.7266f,0.848f,0.0375f,-0.7319f,-0.6801f,0.3919f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9923f,0.0702f,-0.0922f,-0.1143f,0.1075f,0.266f,-0.9571f,0.9142f,-0.0423f,-0.9614f,-0.2712f,0.1061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.17262299074832,"rx":14.33853026365958},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":202.89125507456896,"rx":15.30529055403471}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities