# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9993f,-0.058f,0.0073f,-0.038f,-0.0584f,0.9914f,-0.1252f,1.3549f,0f,-0.1254f,-0.9931f,-0.3029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.1457f,-0.0578f,0.9904f,-0.1251f,1.4853f,0f,-0.1253f,-0.9921f,-0.0744f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.038f,-0.0578f,0.9904f,-0.1251f,1.3543f,0f,-0.1253f,-0.9921f,-0.3075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9883f,-0.0579f,0.0073f,0.0705f,-0.0578f,0.9904f,-0.1251f,1.4977f,0f,-0.1253f,-0.9921f,-0.0763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9883f,-0.0579f,0.0073f,0.0766f,-0.0578f,0.9904f,-0.1251f,1.5156f,0f,-0.1253f,-0.9921f,-0.0829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.0493f,-0.0578f,0.9904f,-0.1252f,1.548f,0f,-0.1253f,-0.9931f,-0.3273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.038f,-0.0578f,0.9904f,-0.1251f,1.3549f,0f,-0.1253f,-0.9921f,-0.3029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9883f,-0.0463f,0.0073f,-0.1727f,-0.0578f,0.7923f,-0.1251f,1.5395f,0f,-0.1003f,-0.9921f,-0.0531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9885f,-0.0424f,0.0073f,0.0743f,-0.0546f,0.7926f,-0.1251f,1.554f,-0.0004f,-0.1003f,-0.9921f,-0.0531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.0414f,-0.0578f,0.9904f,-0.1251f,1.4127f,0f,-0.1253f,-0.9921f,-0.3102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.0391f,-0.0578f,0.9904f,-0.1251f,1.3735f,0f,-0.1253f,-0.9921f,-0.3052f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.0407f,-0.0578f,0.9904f,-0.1251f,1.4013f,0f,-0.1253f,-0.9921f,-0.3087f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.0398f,-0.0578f,0.9904f,-0.1251f,1.3858f,0f,-0.1253f,-0.9921f,-0.3067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9883f,-0.0689f,0.0073f,-0.0052f,-0.0578f,1.1786f,-0.1251f,1.3765f,0f,-0.1491f,-0.9921f,-0.1164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9883f,-0.0689f,0.0073f,-0.0175f,-0.0578f,1.1786f,-0.1251f,1.3758f,0f,-0.1491f,-0.9921f,-0.1164f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9883f,-0.0579f,0.0073f,-0.038f,-0.0578f,0.9904f,-0.1251f,1.3549f,0f,-0.1253f,-0.9921f,-0.3029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9983f,-0.0579f,0.0073f,-0.038f,-0.0584f,0.9904f,-0.1251f,1.3549f,0f,-0.1253f,-0.9921f,-0.3029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9145f,-0.3813f,-0.1289f,0.2081f,-0.2754f,0.8266f,-0.4891f,0.8154f,0.2931f,-0.4132f,-0.8618f,0.3893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9357f,-0.3363f,0.0982f,0.0956f,-0.2498f,0.4452f,-0.8589f,0.9416f,0.2451f,-0.8299f,-0.5006f,0.0884f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9864f,-0.0484f,0.0549f,-0.0173f,-0.071f,0.4979f,-0.8634f,1.1217f,0.0143f,-0.8659f,-0.4995f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9873f,-0.0643f,0.035f,-0.0404f,-0.071f,0.7635f,-0.6419f,1.3961f,0.0144f,-0.6426f,-0.766f,-0.4137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7704f,0.2286f,0.3977f,-0.5251f,-0.3897f,0.2053f,0.8604f,1.0793f,0.1021f,-0.9408f,0.2834f,-0.1055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8541f,0.4519f,0.2119f,-0.3671f,-0.4758f,0.6124f,0.6143f,1.2975f,0.1493f,-0.6331f,0.7455f,-0.3138f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7779f,-0.1826f,0.4432f,0.4166f,-0.4096f,0.0271f,-0.8808f,1.2162f,0.1384f,-0.9799f,-0.0989f,-0.0383f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.886f,-0.3287f,0.2924f,0.3059f,-0.4277f,0.4901f,-0.749f,1.4f,0.1071f,-0.8065f,-0.5759f,-0.2917f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9613f,0.2704f,0.0341f,-0.1982f,0.1502f,0.6305f,-0.7603f,0.8825f,-0.2269f,-0.7274f,-0.6473f,0.41f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.974f,0.1908f,-0.1144f,-0.1435f,0.1422f,0.1402f,-0.9789f,0.9114f,-0.1705f,-0.9715f,-0.1634f,0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":204.1914952280969,"rx":15.71901001752023},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.81930993746806,"rx":14.18316372525176}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities