# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9978f,0.058f,-0.0547f,0.0516f,0.0797f,0.7262f,-0.6843f,1.3509f,0f,-0.6865f,-0.7285f,-0.3061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9869f,0.058f,-0.0546f,-0.0402f,0.0788f,0.7255f,-0.6836f,1.6126f,0f,-0.6858f,-0.7278f,-0.2101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9869f,0.058f,-0.0546f,0.0513f,0.0788f,0.7255f,-0.6836f,1.3477f,0f,-0.6858f,-0.7278f,-0.3095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9869f,0.058f,-0.0546f,0.1799f,0.0788f,0.7255f,-0.6836f,1.5929f,0f,-0.6858f,-0.7278f,-0.2107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9869f,0.058f,-0.0546f,0.1952f,0.0788f,0.7255f,-0.6836f,1.5941f,0f,-0.6858f,-0.7278f,-0.219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9869f,0.058f,-0.0547f,0.0614f,0.0788f,0.7255f,-0.6843f,1.4742f,0f,-0.6858f,-0.7285f,-0.4226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9869f,0.058f,-0.0546f,0.0516f,0.0788f,0.7255f,-0.6836f,1.3509f,0f,-0.6858f,-0.7278f,-0.3061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9869f,0.0464f,-0.0546f,-0.0477f,0.0788f,0.5804f,-0.6836f,1.6622f,0f,-0.5487f,-0.7278f,-0.2175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9872f,0.0388f,-0.0546f,0.199f,0.0744f,0.581f,-0.6836f,1.6425f,0.0042f,-0.5486f,-0.7278f,-0.2175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9869f,0.058f,-0.0546f,0.0543f,0.0788f,0.7255f,-0.6836f,1.3842f,0f,-0.6858f,-0.7278f,-0.3376f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9869f,0.058f,-0.0546f,0.0527f,0.0788f,0.7255f,-0.6836f,1.3645f,0f,-0.6858f,-0.7278f,-0.3189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9869f,0.058f,-0.0546f,0.0543f,0.0788f,0.7255f,-0.6836f,1.3849f,0f,-0.6858f,-0.7278f,-0.3382f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9869f,0.058f,-0.0546f,0.0534f,0.0788f,0.7255f,-0.6836f,1.3736f,0f,-0.6858f,-0.7278f,-0.3275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9869f,0.069f,-0.0546f,0.0955f,0.0788f,0.8633f,-0.6836f,1.4736f,0f,-0.8161f,-0.7278f,-0.167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9869f,0.069f,-0.0546f,0.0832f,0.0788f,0.8633f,-0.6836f,1.4745f,0f,-0.8161f,-0.7278f,-0.167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9869f,0.058f,-0.0546f,0.0516f,0.0788f,0.7255f,-0.6836f,1.3509f,0f,-0.6858f,-0.7278f,-0.3061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9968f,0.058f,-0.0546f,0.0516f,0.0796f,0.7255f,-0.6836f,1.3509f,0f,-0.6858f,-0.7278f,-0.3061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9957f,-0.0298f,-0.0751f,0.184f,0.0154f,0.8429f,-0.5364f,0.7961f,0.0792f,-0.5367f,-0.8398f,0.417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9874f,-0.1446f,-0.0473f,0.1328f,-0.0183f,0.4223f,-0.9054f,0.913f,0.1509f,-0.8948f,-0.4196f,0.0963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9838f,0.0696f,-0.0755f,0.022f,0.0992f,0.4957f,-0.8618f,1.1181f,-0.0224f,-0.8657f,-0.4996f,-0.1863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9848f,0.0913f,-0.0472f,0.0548f,0.0993f,0.7609f,-0.6411f,1.3915f,-0.0224f,-0.6424f,-0.766f,-0.4171f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7588f,0.1409f,0.462f,-0.4254f,-0.4235f,0.1937f,0.8421f,1.1294f,0.0259f,-0.9603f,0.2368f,-0.0934f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.843f,0.412f,0.3134f,-0.2799f,-0.5132f,0.5909f,0.6052f,1.3401f,0.0648f,-0.6791f,0.7167f,-0.3179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8729f,0.0507f,0.182f,0.4426f,-0.1676f,-0.0602f,-0.9726f,1.1479f,-0.032f,-0.9931f,0.0783f,-0.0378f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9619f,-0.1514f,0.1737f,0.3941f,-0.2305f,0.5447f,-0.7965f,1.3497f,0.0301f,-0.824f,-0.5601f,-0.2969f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9626f,0.2197f,-0.1529f,-0.1701f,0.2533f,0.565f,-0.784f,0.9042f,-0.0854f,-0.7951f,-0.6001f,0.409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9496f,0.2015f,-0.2365f,-0.1138f,0.2639f,0.1226f,-0.9557f,0.9283f,-0.1633f,-0.9717f,-0.1693f,0.1215f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":201.9426383964962,"rx":18.53895695504423},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.65437268470896,"rx":12.113689318943145}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities