# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.9997f,0.0398f,-0.0324f,0.0334f,0.0513f,0.7757f,-0.6306f,1.3557f,0f,-0.6314f,-0.7767f,-0.3023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9887f,0.0398f,-0.0323f,-0.0661f,0.0508f,0.7749f,-0.6299f,1.6068f,0f,-0.6308f,-0.776f,-0.1879f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.9887f,0.0398f,-0.0323f,0.0333f,0.0508f,0.7749f,-0.6299f,1.3527f,0f,-0.6308f,-0.776f,-0.3059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9887f,0.0398f,-0.0323f,0.1536f,0.0508f,0.7749f,-0.6299f,1.5939f,0f,-0.6308f,-0.776f,-0.1889f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.9887f,0.0398f,-0.0323f,0.1696f,0.0508f,0.7749f,-0.6299f,1.5958f,0f,-0.6308f,-0.776f,-0.1968f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.9887f,0.0398f,-0.0324f,0.0402f,0.0508f,0.7749f,-0.6306f,1.4876f,0f,-0.6308f,-0.7767f,-0.4096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.9887f,0.0398f,-0.0323f,0.0334f,0.0508f,0.7749f,-0.6299f,1.3557f,0f,-0.6308f,-0.776f,-0.3023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9887f,0.0318f,-0.0323f,-0.075f,0.0508f,0.62f,-0.6299f,1.6568f,0f,-0.5046f,-0.776f,-0.1918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.989f,0.0192f,-0.0323f,0.1721f,0.0428f,0.6206f,-0.6299f,1.6441f,0.0064f,-0.5046f,-0.776f,-0.1918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.9887f,0.0398f,-0.0323f,0.0352f,0.0508f,0.7749f,-0.6299f,1.3914f,0f,-0.6308f,-0.776f,-0.3313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.9887f,0.0398f,-0.0323f,0.0342f,0.0508f,0.7749f,-0.6299f,1.3703f,0f,-0.6308f,-0.776f,-0.3141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.9887f,0.0398f,-0.0323f,0.0353f,0.0508f,0.7749f,-0.6299f,1.3921f,0f,-0.6308f,-0.776f,-0.3318f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.9887f,0.0398f,-0.0323f,0.0347f,0.0508f,0.7749f,-0.6299f,1.38f,0f,-0.6308f,-0.776f,-0.3219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.9887f,0.0473f,-0.0323f,0.0733f,0.0508f,0.9222f,-0.6299f,1.4691f,0f,-0.7506f,-0.776f,-0.1543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.9887f,0.0473f,-0.0323f,0.0609f,0.0508f,0.9222f,-0.6299f,1.4697f,0f,-0.7506f,-0.776f,-0.1543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.9887f,0.0398f,-0.0323f,0.0334f,0.0508f,0.7749f,-0.6299f,1.3557f,0f,-0.6308f,-0.776f,-0.3023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.9987f,0.0398f,-0.0323f,0.0334f,0.0513f,0.7749f,-0.6299f,1.3557f,0f,-0.6308f,-0.776f,-0.3023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9901f,-0.1032f,-0.0839f,0.1893f,-0.0453f,0.8552f,-0.5147f,0.7984f,0.1247f,-0.5074f,-0.8524f,0.4122f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9821f,-0.1827f,-0.0145f,0.126f,-0.0678f,0.4363f,-0.8964f,0.9204f,0.1701f,-0.8811f,-0.4408f,0.0956f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9863f,0.0531f,-0.0506f,0.0114f,0.0697f,0.4977f,-0.8636f,1.1227f,-0.0205f,-0.8657f,-0.4996f,-0.1822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9873f,0.0672f,-0.0295f,0.0355f,0.0697f,0.7633f,-0.6422f,1.397f,-0.0205f,-0.6425f,-0.766f,-0.4131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7622f,0.1584f,0.449f,-0.446f,-0.4162f,0.1956f,0.8464f,1.1234f,0.041f,-0.9572f,0.2464f,-0.0928f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8464f,0.4199f,0.293f,-0.2981f,-0.5051f,0.5953f,0.6078f,1.3356f,0.0816f,-0.6704f,0.7231f,-0.3142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.862f,0.0191f,0.2421f,0.4385f,-0.2195f,-0.0856f,-0.9578f,1.1669f,0.0052f,-0.9921f,0.0974f,-0.0341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9504f,-0.1892f,0.1983f,0.3768f,-0.2718f,0.5335f,-0.7911f,1.3651f,0.048f,-0.8236f,-0.5595f,-0.2932f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9612f,0.244f,-0.1221f,-0.1779f,0.2438f,0.5682f,-0.7848f,0.9038f,-0.1217f,-0.7857f,-0.6062f,0.4101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9518f,0.2063f,-0.223f,-0.1201f,0.2501f,0.1166f,-0.9602f,0.9261f,-0.1718f,-0.9715f,-0.1623f,0.1227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.4375000000000001,"py":1.6875,"pz":0.75,"ry":202.42719893871208,"rx":18.260680871807683},"camera3":{"px":-1.5000000000000004,"py":2,"pz":3.25,"ry":203.71508542512066,"rx":12.105386358094583}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities