# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.selena.animation.idle.playing] run function aj:selena/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.selena.animation.chat1.playing] run function aj:selena/animations/chat1/zzz/on_tick
execute if entity @s[tag=aj.selena.animation.death.playing] run function aj:selena/animations/death/zzz/on_tick