# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on vehicle run function monsters:chapter_2/abyss_soulcutter/state_machine/state/back
scoreboard players set 00000014-0000-0014-0000-000100000019 monster.abyss_soulcutter.state_machine.back 10