# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:fsc_fx/animations/pause_all
tag @s add aj.fsc_fx.animation.run.playing
scoreboard players set @s aj.run.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:fsc_fx/animations/run/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only