# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.boss_1.animation.spawn_loop.playing
tag @s remove aj.boss_1.animation.spawn.playing
tag @s remove aj.boss_1.animation.heavy_attack_1.playing
tag @s remove aj.boss_1.animation.attack_1.playing
tag @s remove aj.boss_1.animation.attack_2.playing
tag @s remove aj.boss_1.animation.back.playing
tag @s remove aj.boss_1.animation.idle.playing