# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.535f,0.058f,-0.8429f,-0.0508f,-0.0018f,0.9976f,0.0698f,1.3066f,0.845f,0.0389f,-0.5336f,0.0196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.535f,0.058f,-0.8429f,0.101f,-0.0018f,0.9976f,0.0698f,1.4425f,0.845f,0.0389f,-0.5336f,0.2456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.535f,0.058f,-0.8429f,-0.0587f,-0.0018f,0.9976f,0.0698f,1.3072f,0.845f,0.0389f,-0.5336f,0.0146f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.535f,0.058f,-0.8429f,0.2181f,-0.0018f,0.9976f,0.0698f,1.4429f,0.845f,0.0389f,-0.5336f,0.0607f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.535f,0.058f,-0.8429f,0.2195f,-0.0018f,0.9976f,0.0698f,1.4153f,0.845f,0.0389f,-0.5336f,0.0431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.535f,0.058f,-0.8429f,-0.0454f,-0.0018f,0.9976f,0.0698f,1.4001f,0.845f,0.0389f,-0.5336f,0.0233f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.535f,0.058f,-0.8429f,-0.0402f,-0.0018f,0.9976f,0.0698f,1.4976f,0.845f,0.0389f,-0.5336f,0.0267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.535f,0.058f,-0.8429f,-0.0508f,-0.0018f,0.9976f,0.0698f,1.3066f,0.845f,0.0389f,-0.5336f,0.0196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.535f,0.0435f,-0.8429f,0.1093f,-0.0018f,0.7482f,0.0698f,1.4784f,0.845f,0.0292f,-0.5336f,0.2694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.535f,0.0435f,-0.8429f,0.2431f,-0.0018f,0.7482f,0.0698f,1.4789f,0.845f,0.0292f,-0.5336f,0.0581f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(sad) {transformation: [-0.8561f,0.0183f,-0.8619f,0.0723f,-0.0029f,0.3146f,0.0714f,1.4195f,1.352f,0.0123f,-0.5456f,0.2909f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.535f,0.058f,-0.8429f,-0.0508f,-0.0018f,0.9976f,0.0698f,1.3066f,0.845f,0.0389f,-0.5336f,0.0196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.5331f,0.0981f,-0.8403f,0.0235f,-0.1323f,0.9714f,0.1973f,0.3608f,0.8357f,0.2163f,-0.5049f,-0.1284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.5331f,-0.4016f,-0.7446f,-0.1271f,-0.1323f,0.9089f,-0.3955f,0.7017f,0.8357f,-0.1124f,-0.5376f,-0.1705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.535f,-0.0162f,-0.8447f,-0.1845f,-0.0018f,0.9998f,-0.018f,1.0112f,0.8449f,-0.0081f,-0.5349f,-0.0657f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.535f,0.4083f,-0.7396f,-0.0314f,-0.0018f,0.8749f,0.4843f,1.3393f,0.8449f,0.2604f,-0.4673f,0.032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.2963f,0.6662f,-0.1402f,0.0999f,-0.5178f,0.3198f,0.4254f,0.9123f,0.4421f,-0.072f,0.5922f,0.5626f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.1869f,-0.3951f,0.8883f,-0.2764f,-0.5672f,0.6903f,0.4264f,0.9516f,-0.7896f,-0.5894f,-0.096f,0.4453f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.1869f,0.102f,0.9668f,-0.2353f,-0.5672f,0.8111f,0.0241f,1.2306f,-0.7896f,-0.5585f,0.2116f,0.2546f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.4416f,-0.8142f,0.377f,0.3286f,-0.4774f,-0.1426f,-0.867f,0.9892f,0.7597f,-0.5629f,-0.3257f,-0.3097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.4416f,-0.7593f,-0.478f,0.0439f,-0.4774f,0.65f,-0.5913f,1.2329f,0.7597f,-0.0329f,-0.6495f,-0.3221f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.5952f,0.6314f,-0.4971f,-0.253f,0.1934f,0.713f,0.674f,0.3791f,0.78f,0.3051f,-0.5464f,0.1196f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.5952f,0.1641f,-0.7866f,-0.2337f,0.1934f,0.9794f,0.058f,0.6876f,0.78f,-0.1176f,-0.6147f,0.0579f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":0.1938288671874998,"py":1.45850033203125,"pz":1.575839365234375,"ry":166.836381953125,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:oceanid/root/on_tick/transform_floating_entities