# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.919f,0.0097f,-0.3943f,0.0113f,-0.0533f,0.9874f,0.1487f,1.3375f,0.3908f,0.1577f,-0.9069f,0.2338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.919f,0.0097f,-0.3943f,0.0065f,-0.0533f,0.9874f,0.1487f,1.4474f,0.3908f,0.1577f,-0.9069f,0.5175f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.919f,0.0097f,-0.3943f,0.0076f,-0.0533f,0.9874f,0.1487f,1.3389f,0.3908f,0.1577f,-0.9069f,0.2253f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.919f,0.0097f,-0.3943f,0.2075f,-0.0533f,0.9874f,0.1487f,1.459f,0.3908f,0.1577f,-0.9069f,0.432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.919f,0.0097f,-0.3943f,0.2191f,-0.0533f,0.9874f,0.1487f,1.433f,0.3908f,0.1577f,-0.9069f,0.4158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.919f,0.0097f,-0.3943f,0.0122f,-0.0533f,0.9874f,0.1487f,1.4301f,0.3908f,0.1577f,-0.9069f,0.2486f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.919f,0.0097f,-0.3943f,0.0131f,-0.0533f,0.9874f,0.1487f,1.5536f,0.3908f,0.1577f,-0.9069f,0.2677f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.919f,0.0097f,-0.3943f,0.0113f,-0.0533f,0.9874f,0.1487f,1.3375f,0.3908f,0.1577f,-0.9069f,0.2338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9164f,-0.0528f,-0.3943f,-0.0005f,-0.1392f,0.7343f,0.1487f,1.5011f,0.3756f,0.1433f,-0.9069f,0.5483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9147f,0.0673f,-0.3943f,0.2292f,0.0329f,0.7413f,0.1487f,1.5144f,0.403f,0.0923f,-0.9069f,0.4506f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(sad) {transformation: [0f,0f,0f,-0.0614f,0f,0f,0f,0.848f,0f,0f,0f,0.4504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.919f,0.0097f,-0.3943f,0.0113f,-0.0533f,0.9874f,0.1487f,1.3375f,0.3908f,0.1577f,-0.9069f,0.2338f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9011f,-0.1253f,-0.4152f,0.2359f,-0.1833f,0.9777f,0.1027f,0.4042f,0.3931f,0.1687f,-0.9039f,0.2169f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9011f,-0.3407f,-0.2684f,0.1082f,-0.1833f,0.86f,-0.4762f,0.7267f,0.3931f,-0.3799f,-0.8374f,0.0745f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.919f,-0.0925f,-0.3834f,-0.0246f,-0.0533f,0.9923f,-0.1115f,1.0291f,0.3907f,-0.082f,-0.9168f,0.1074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.919f,0.1118f,-0.3782f,0.0173f,-0.0533f,0.9149f,0.4f,1.3722f,0.3907f,0.3878f,-0.8348f,0.2528f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [-0.5119f,0.4609f,-0.2771f,-0.5397f,-0.3001f,0.0726f,0.6753f,1.0431f,0.4463f,0.5776f,0.1362f,0.7676f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.3695f,0.6592f,0.6396f,-0.5748f,-0.9003f,0.3963f,0.1117f,1.1073f,-0.1816f,-0.6233f,0.7474f,0.3782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.3695f,0.8908f,0.2239f,-0.2672f,-0.9003f,0.399f,-0.1016f,1.2438f,-0.1816f,-0.1657f,0.959f,0.3272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.7902f,0.3439f,0.5073f,0.5174f,-0.6094f,-0.3534f,-0.7097f,1.0682f,-0.0648f,-0.87f,0.4888f,0.2386f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.8111f,-0.5515f,0.1949f,0.3106f,-0.5189f,0.5248f,-0.6748f,1.265f,0.2699f,-0.6485f,-0.7118f,-0.0045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9474f,0.2825f,-0.1504f,-0.1333f,0.1345f,0.7778f,0.6139f,0.3945f,0.2904f,0.5614f,-0.7749f,0.2627f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9474f,0.1196f,-0.2969f,-0.108f,0.1345f,0.9905f,-0.0301f,0.7028f,0.2904f,-0.0685f,-0.9544f,0.2026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":0.02749999999999974,"py":1.46625,"pz":2.136875,"ry":180.0243198816471,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:oceanid/root/on_tick/transform_floating_entities