# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.5971f,0.0678f,-0.7994f,-0.1564f,-0.0057f,0.996f,0.0887f,1.3468f,0.8023f,0.0575f,-0.5942f,-0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.5971f,0.0678f,-0.7994f,-0.0202f,-0.0057f,0.996f,0.0887f,1.4775f,0.8023f,0.0575f,-0.5942f,0.2203f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.5971f,0.0678f,-0.7994f,-0.1639f,-0.0057f,0.996f,0.0887f,1.3477f,0.8023f,0.0575f,-0.5942f,-0.0239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.5971f,0.0678f,-0.7994f,0.1104f,-0.0057f,0.996f,0.0887f,1.4788f,0.8023f,0.0575f,-0.5942f,0.0448f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.5971f,0.0678f,-0.7994f,0.1128f,-0.0057f,0.996f,0.0887f,1.4514f,0.8023f,0.0575f,-0.5942f,0.0269f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.5971f,0.0678f,-0.7994f,-0.15f,-0.0057f,0.996f,0.0887f,1.4402f,0.8023f,0.0575f,-0.5942f,-0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.5971f,0.0678f,-0.7994f,-0.146f,-0.0057f,0.996f,0.0887f,1.5065f,0.8023f,0.0575f,-0.5942f,-0.0095f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.5971f,0.0678f,-0.7994f,-0.1564f,-0.0057f,0.996f,0.0887f,1.3468f,0.8023f,0.0575f,-0.5942f,-0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.597f,0.0512f,-0.7994f,-0.0148f,-0.005f,0.747f,0.0887f,1.4898f,0.8023f,0.0427f,-0.5942f,0.2439f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.5971f,0.0505f,-0.7994f,0.1344f,-0.0065f,0.747f,0.0887f,1.4912f,0.8023f,0.0436f,-0.5942f,0.0433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(sad) {transformation: [-0.4473f,0.0541f,-0.7994f,-0.0616f,-0.0043f,0.7954f,0.0887f,1.4368f,0.6011f,0.0459f,-0.5942f,0.2726f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.5971f,0.0678f,-0.7994f,-0.1564f,-0.0057f,0.996f,0.0887f,1.3468f,0.8023f,0.0575f,-0.5942f,-0.0183f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.5814f,-0.0165f,-0.8134f,0.0233f,-0.1356f,0.9878f,0.0768f,0.4067f,0.8022f,0.155f,-0.5766f,-0.0947f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.5814f,-0.4801f,-0.6568f,-0.1568f,-0.1356f,0.8532f,-0.5036f,0.7267f,0.8022f,-0.2038f,-0.5612f,-0.1711f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.597f,-0.115f,-0.7939f,-0.2528f,-0.0057f,0.9902f,-0.1392f,1.0344f,0.8022f,-0.0786f,-0.5918f,-0.0923f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.597f,0.2973f,-0.7451f,-0.1413f,-0.0057f,0.9272f,0.3746f,1.3821f,0.8022f,0.2279f,-0.5518f,-0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0.3107f,0.6346f,-0.2281f,-0.0103f,-0.4557f,0.3827f,0.4441f,1.0047f,0.4971f,-0.0458f,0.5496f,0.5602f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.3041f,-0.4143f,0.8462f,-0.3783f,-0.5921f,0.6076f,0.5103f,0.9971f,-0.7328f,-0.6628f,-0.0611f,0.4136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.3041f,0.0643f,0.9399f,-0.3503f,-0.5921f,0.7813f,0.1381f,1.2665f,-0.7328f,-0.6046f,0.2785f,0.2075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.3329f,0.1421f,0.9322f,0.2869f,-0.9194f,-0.2686f,-0.2873f,1.1886f,0.2096f,-0.9527f,0.2201f,-0.163f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.3325f,-0.8144f,0.4755f,-0.0185f,-0.9219f,0.1746f,-0.3457f,1.254f,0.1986f,-0.5534f,-0.8089f,-0.3705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.6712f,0.53f,-0.5183f,-0.2718f,0.1752f,0.7928f,0.5837f,0.4111f,0.7203f,0.301f,-0.625f,0.1303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.6712f,0.0728f,-0.7377f,-0.2791f,0.1752f,0.9825f,-0.0625f,0.7156f,0.7203f,-0.1712f,-0.6723f,0.0495f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":0.21793490740740717,"py":1.5297723842592592,"pz":1.7466579976851855,"ry":155.59036740740743,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:oceanid/root/on_tick/transform_floating_entities