# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(l_1) {transformation: [-0.99f,0f,0f,-0.108f,0f,1f,0f,1.5278f,0f,0f,-1f,0.2108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.99f,0f,0f,0.108f,0f,1f,0f,1.5278f,0f,0f,-1f,0.2106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.5723f,0f,0f,-1.001f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,0.0037f,0f,-0.1238f,0.003f,0.8f,0f,1.5656f,0f,0f,-1f,0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.99f,-0.0037f,0f,0.1237f,-0.003f,0.8f,0f,1.5656f,0f,0f,-1f,0.2406f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4502f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.427f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0f,1.4544f,0f,0f,-1f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.0332f,0f,1f,0f,1.4063f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1f,0f,1.4054f,0f,0f,-1f,0.1563f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}