# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.7143f,-0.292f,0.6361f,0f,0.082f,0.8676f,0.4904f,1.4219f,-0.6951f,0.4024f,-0.5958f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.7143f,-0.292f,0.6361f,-0.2745f,0.082f,0.8676f,0.4904f,1.4229f,-0.6951f,0.4024f,-0.5958f,-0.0002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.7143f,-0.292f,0.6361f,0f,0.082f,0.8676f,0.4904f,1.4219f,-0.6951f,0.4024f,-0.5958f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.7143f,-0.292f,0.6361f,-0.1182f,0.082f,0.8676f,0.4904f,1.405f,-0.6951f,0.4024f,-0.5958f,0.1519f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.7143f,-0.292f,0.6361f,-0.1013f,0.082f,0.8676f,0.4904f,1.4013f,-0.6951f,0.4024f,-0.5958f,0.1565f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.7143f,-0.292f,0.6361f,-0.052f,0.082f,0.8676f,0.4904f,1.5764f,-0.6951f,0.4024f,-0.5958f,-0.0533f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.7143f,-0.292f,0.6361f,0f,0.082f,0.8676f,0.4904f,1.4219f,-0.6951f,0.4024f,-0.5958f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.7143f,-0.292f,0.6361f,-0.3119f,0.082f,0.8676f,0.4904f,1.4466f,-0.6951f,0.4024f,-0.5958f,0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.7143f,-0.292f,0.6361f,-0.1334f,0.082f,0.8676f,0.4904f,1.4261f,-0.6951f,0.4024f,-0.5958f,0.1924f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.7143f,-0.292f,0.6361f,-0.0155f,0.082f,0.8676f,0.4904f,1.468f,-0.6951f,0.4024f,-0.5958f,-0.1036f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.7143f,-0.292f,0.6361f,-0.0055f,0.082f,0.8676f,0.4904f,1.4381f,-0.6951f,0.4024f,-0.5958f,-0.1174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.7143f,-0.292f,0.6361f,-0.0137f,0.082f,0.8676f,0.4904f,1.4625f,-0.6951f,0.4024f,-0.5958f,-0.1061f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.7143f,-0.292f,0.6361f,-0.0092f,0.082f,0.8676f,0.4904f,1.449f,-0.6951f,0.4024f,-0.5958f,-0.1124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.7143f,-0.292f,0.6361f,-0.0947f,0.082f,0.8676f,0.4904f,1.3271f,-0.6951f,0.4024f,-0.5958f,0.0106f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.7143f,-0.292f,0.6361f,-0.1036f,0.082f,0.8676f,0.4904f,1.3281f,-0.6951f,0.4024f,-0.5958f,0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.7143f,-0.292f,0.6361f,0f,0.082f,0.8676f,0.4904f,1.4219f,-0.6951f,0.4024f,-0.5958f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.7143f,-0.292f,0.6361f,0f,0.082f,0.8676f,0.4904f,1.4219f,-0.6951f,0.4024f,-0.5958f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9726f,-0.0271f,0.2269f,0.0931f,-0.0196f,0.9992f,0.0352f,0.3803f,-0.2275f,0.0298f,-0.9733f,-0.0045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9735f,0.0227f,0.2274f,0.1002f,-0.0196f,0.9831f,-0.1819f,0.6875f,-0.2277f,-0.1816f,-0.9567f,-0.0612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.8425f,0.0933f,0.5291f,0.0378f,0f,0.9848f,-0.1736f,1.0635f,-0.5368f,-0.1465f,-0.8306f,-0.1844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.8434f,-0.0933f,0.5291f,0f,0f,0.9848f,0.1736f,1.3906f,-0.5373f,0.1465f,-0.8306f,-0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.4648f,0.6561f,-0.5941f,-0.2984f,-0.7536f,0.6451f,0.1216f,1.1995f,0.4626f,0.3916f,0.7951f,-0.5617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.4653f,0.1207f,-0.8769f,-0.2899f,-0.7544f,0.5724f,-0.3215f,1.3594f,0.4631f,0.8111f,0.3574f,-0.3097f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.0259f,0.4821f,0.8757f,0.3473f,-0.7785f,0.5389f,-0.3197f,1.1644f,-0.6255f,-0.6907f,0.3618f,0.3f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.0259f,-0.0639f,0.9976f,0.2899f,-0.7793f,0.6263f,0.0199f,1.3594f,-0.6261f,-0.777f,-0.066f,0.0597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.7608f,-0.0146f,0.6479f,-0.2777f,0.0614f,0.9936f,0.0947f,0.5097f,-0.6445f,0.1119f,-0.7558f,-0.0449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.7616f,0.4269f,0.4875f,-0.1403f,0.0615f,0.7965f,-0.6015f,0.733f,-0.6451f,-0.4281f,-0.6329f,-0.1858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(glass) {transformation: [0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blackhole) {transformation: [0f,0f,0f,-0.3125f,0f,0f,0f,0.0625f,0f,0f,0f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display) {transformation: [0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.43615852264375,"py":0.625,"pz":0.6986867122499998,"ry":245,"rx":-10.000000000000002},"camera3":{"px":-1.43615852264375,"py":0.625,"pz":0.6986867122499998,"ry":245,"rx":-10.000000000000002}},"locators":{"locator_guide":{"px":0,"py":0,"pz":0,"ry":0,"rx":0}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities