# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0003f,0.0824f,0.8576f,0.5077f,1.4193f,-0.6369f,0.4371f,-0.635f,-0.1244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.7665f,-0.271f,0.5822f,-0.2644f,0.0824f,0.8576f,0.5077f,1.4147f,-0.6369f,0.4371f,-0.635f,0.021f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0003f,0.0824f,0.8576f,0.5077f,1.4193f,-0.6369f,0.4371f,-0.635f,-0.1244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0967f,0.0824f,0.8576f,0.5077f,1.3967f,-0.6369f,0.4371f,-0.635f,0.1604f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0794f,0.0824f,0.8576f,0.5077f,1.3932f,-0.6369f,0.4371f,-0.635f,0.1636f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0486f,0.0824f,0.8576f,0.5077f,1.572f,-0.6369f,0.4371f,-0.635f,-0.0466f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0003f,0.0824f,0.8576f,0.5077f,1.4193f,-0.6369f,0.4371f,-0.635f,-0.1244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.7665f,-0.271f,0.5822f,-0.3006f,0.0824f,0.8576f,0.5077f,1.4376f,-0.6369f,0.4371f,-0.635f,0.0431f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.7665f,-0.271f,0.5822f,-0.109f,0.0824f,0.8576f,0.5077f,1.417f,-0.6369f,0.4371f,-0.635f,0.2023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0147f,0.0824f,0.8576f,0.5077f,1.4648f,-0.6369f,0.4371f,-0.635f,-0.1012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0054f,0.0824f,0.8576f,0.5077f,1.4353f,-0.6369f,0.4371f,-0.635f,-0.1162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.7665f,-0.271f,0.5822f,-0.013f,0.0824f,0.8576f,0.5077f,1.4594f,-0.6369f,0.4371f,-0.635f,-0.1039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0088f,0.0824f,0.8576f,0.5077f,1.446f,-0.6369f,0.4371f,-0.635f,-0.1107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0831f,0.0824f,0.8576f,0.5077f,1.3212f,-0.6369f,0.4371f,-0.635f,0.0165f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0927f,0.0824f,0.8576f,0.5077f,1.3223f,-0.6369f,0.4371f,-0.635f,0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0003f,0.0824f,0.8576f,0.5077f,1.4193f,-0.6369f,0.4371f,-0.635f,-0.1244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.7665f,-0.271f,0.5822f,-0.0003f,0.0824f,0.8576f,0.5077f,1.4193f,-0.6369f,0.4371f,-0.635f,-0.1244f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9874f,-0.0247f,0.1502f,0.1017f,-0.0196f,0.9992f,0.0352f,0.3803f,-0.1508f,0.0318f,-0.988f,-0.0088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9883f,0.0101f,0.1519f,0.1048f,-0.0196f,0.9811f,-0.1927f,0.6868f,-0.151f,-0.1934f,-0.9694f,-0.0692f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.8819f,0.0849f,0.462f,0.0348f,0f,0.9835f,-0.1808f,1.0623f,-0.4693f,-0.1596f,-0.8682f,-0.1903f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.8828f,-0.0849f,0.462f,0.0004f,0f,0.9835f,0.1808f,1.3875f,-0.4698f,0.1596f,-0.8682f,-0.1257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.5146f,0.6979f,-0.4975f,-0.3334f,-0.7516f,0.6463f,0.1275f,1.1958f,0.4101f,0.3086f,0.858f,-0.5355f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.5152f,0.1981f,-0.8339f,-0.3006f,-0.7524f,0.5705f,-0.3292f,1.3549f,0.4105f,0.797f,0.443f,-0.285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.0709f,0.45f,0.8902f,0.3794f,-0.7759f,0.5351f,-0.3324f,1.1608f,-0.6253f,-0.715f,0.3115f,0.2682f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.071f,-0.1151f,0.9908f,0.3062f,-0.7767f,0.6297f,0.0175f,1.3562f,-0.6259f,-0.7683f,-0.1341f,0.0341f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.805f,0.0117f,0.5921f,-0.2761f,0.0676f,0.9951f,0.0723f,0.5247f,-0.5877f,0.0983f,-0.8026f,-0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.8057f,0.4163f,0.4214f,-0.1425f,0.0644f,0.7687f,-0.6363f,0.7368f,-0.5889f,-0.4856f,-0.6461f,-0.1753f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blackhole) {transformation: [-0.0106f,0.0017f,-0.1135f,-0.3486f,-0.0568f,-0.0987f,0.0038f,0.0769f,-0.0982f,0.057f,0.01f,0.0384f,0f,0f,0f,1f],start_interpolation: -1,interpolation_duration: 0}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-1.3153163232169827,"py":0.6621720116618076,"pz":0.8876609479155976,"ry":238.68804664723035,"rx":-9.008746355685131},"camera3":{"px":-1.3153163232169827,"py":0.6621720116618076,"pz":0.8876609479155976,"ry":238.68804664723035,"rx":-9.008746355685131}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities