# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0007f,0.0836f,0.8252f,0.5586f,1.4114f,-0.4384f,0.5338f,-0.7231f,-0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.2237f,0.0836f,0.8252f,0.5586f,1.39f,-0.4384f,0.5338f,-0.7231f,0.0793f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0007f,0.0836f,0.8252f,0.5586f,1.4114f,-0.4384f,0.5338f,-0.7231f,-0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0279f,0.0836f,0.8252f,0.5586f,1.3718f,-0.4384f,0.5338f,-0.7231f,0.1752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0103f,0.0836f,0.8252f,0.5586f,1.3688f,-0.4384f,0.5338f,-0.7231f,0.1742f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0335f,0.0836f,0.8252f,0.5586f,1.5584f,-0.4384f,0.5338f,-0.7231f,-0.0274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0007f,0.0836f,0.8252f,0.5586f,1.4114f,-0.4384f,0.5338f,-0.7231f,-0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.2544f,0.0836f,0.8252f,0.5586f,1.4105f,-0.4384f,0.5338f,-0.7231f,0.1102f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0307f,0.0836f,0.8252f,0.5586f,1.3896f,-0.4384f,0.5338f,-0.7231f,0.2198f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0105f,0.0836f,0.8252f,0.5586f,1.4552f,-0.4384f,0.5338f,-0.7231f,-0.0941f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0041f,0.0836f,0.8252f,0.5586f,1.4268f,-0.4384f,0.5338f,-0.7231f,-0.1124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0093f,0.0836f,0.8252f,0.5586f,1.45f,-0.4384f,0.5338f,-0.7231f,-0.0974f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0064f,0.0836f,0.8252f,0.5586f,1.4371f,-0.4384f,0.5338f,-0.7231f,-0.1057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0461f,0.0836f,0.8252f,0.5586f,1.3038f,-0.4384f,0.5338f,-0.7231f,0.0282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0573f,0.0836f,0.8252f,0.5586f,1.3048f,-0.4384f,0.5338f,-0.7231f,0.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0007f,0.0836f,0.8252f,0.5586f,1.4114f,-0.4384f,0.5338f,-0.7231f,-0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.8949f,-0.1845f,0.4064f,-0.0007f,0.0836f,0.8252f,0.5586f,1.4114f,-0.4384f,0.5338f,-0.7231f,-0.1225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9952f,-0.0165f,-0.086f,0.1269f,-0.0196f,0.9992f,0.0352f,0.3804f,0.0852f,0.0367f,-0.9957f,-0.0258f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9962f,-0.0382f,-0.0788f,0.115f,-0.0196f,0.9742f,-0.225f,0.6849f,0.0853f,-0.2226f,-0.9712f,-0.0954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9674f,0.0505f,0.2442f,0.0215f,0f,0.9793f,-0.2024f,1.0593f,-0.2491f,-0.1961f,-0.9484f,-0.2073f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9684f,-0.0505f,0.2442f,0.0011f,0f,0.9793f,0.2024f,1.3785f,-0.2494f,0.1961f,-0.9484f,-0.1284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.6289f,0.7579f,-0.1711f,-0.4246f,-0.7435f,0.6514f,0.1475f,1.1841f,0.223f,0.0345f,0.9742f,-0.4394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.6295f,0.4193f,-0.6541f,-0.3205f,-0.7442f,0.5673f,-0.3526f,1.3415f,0.2232f,0.7088f,0.6692f,-0.2081f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.208f,0.3428f,0.9161f,0.4596f,-0.7683f,0.5213f,-0.3699f,1.1507f,-0.6037f,-0.7815f,0.1551f,0.1575f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.2082f,-0.2657f,0.9413f,0.3415f,-0.769f,0.6391f,0.0103f,1.347f,-0.6044f,-0.7217f,-0.3374f,-0.0517f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9111f,0.0776f,0.4028f,-0.2512f,0.0868f,0.9962f,0.0047f,0.5725f,-0.4005f,0.0393f,-0.9153f,0.0693f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9129f,0.3419f,0.2232f,-0.1434f,0.0737f,0.6756f,-0.7336f,0.7475f,-0.4016f,-0.6532f,-0.6419f,-0.1437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(blackhole) {transformation: [-0.2203f,0.0962f,-0.4016f,-0.274f,-0.409f,-0.113f,0.1973f,0.0084f,-0.0564f,0.4439f,0.1372f,0.1334f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-0.9433072949513851,"py":0.7791545189504373,"pz":1.4873012475048102,"ry":219.06705539358603,"rx":-5.889212827988336},"camera3":{"px":-0.9433072949513851,"py":0.7791545189504373,"pz":1.4873012475048102,"ry":219.06705539358603,"rx":-5.889212827988336}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities