# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string with entity @s
data modify entity @s data.bones.data_data set from storage aj:uuid main.out
summon item_display ~ ~ ~ {Tags:['aj.new', 'aj.global.camera', 'aj.screen_sneak.camera', 'aj.screen_sneak.camera'], teleport_duration: 2}
execute as @e[type=item_display,tag=aj.new,tag=aj.global.camera,limit=1,distance=..0.01] run function animated_java:screen_sneak/zzz/2
data modify entity @s data.cameras.camera.uuid set from storage aj:uuid main.out