# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute \
    as $(uuid) run function animated_java:yibb_tstll/remove/zzz/this/recursively_kill_passengers