# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.

execute on passengers \
    if entity @s[tag=aj.isokla.node.layer] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.l_1] run data merge entity @s { transformation: [-1f,0f,0f,-0.1094f,0f,1f,0f,1.625f,0f,0f,-1f,0.1234f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.eye_l] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.r_1] run data merge entity @s { transformation: [-1f,0f,0f,0.1094f,0f,1f,0f,1.625f,0f,0f,-1f,0.1234f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.eye_r] run data merge entity @s { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,1.6406f,0f,0f,-1f,0.1172f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.eyes_down] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5469f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.eyes_up] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.7344f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.bone] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.l] run data merge entity @s { transformation: [-1f,0f,0f,-0.125f,0f,1f,0f,1.7266f,0f,0f,-1f,0.1312f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.r] run data merge entity @s { transformation: [-1f,0f,0f,0.125f,0f,1f,0f,1.7266f,0f,0f,-1f,0.1312f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.eyebrow] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.face] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.sad] run data merge entity @s { transformation: [-1f,0f,0f,-0.0781f,0f,1f,0f,1.5781f,0f,0f,-1f,0.1406f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.6] run data merge entity @s { transformation: [-1f,0f,0f,0.1188f,0f,1f,0f,0.3906f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.12] run data merge entity @s { transformation: [-1f,0f,0f,0.1188f,0f,1f,0f,0.7656f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.leftleg1] run data merge entity @s { transformation: [-1f,0f,0f,0.1188f,0f,1f,0f,0.7656f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.10] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.1406f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.9] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.2] run data merge entity @s { transformation: [1f,0f,0f,-0.375f,0f,1f,0f,1.1406f,0f,0f,1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.1] run data merge entity @s { transformation: [1f,0f,0f,-0.375f,0f,1f,0f,1.5156f,0f,0f,1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.rightarm] run data merge entity @s { transformation: [1f,0f,0f,-0.375f,0f,1f,0f,1.5156f,0f,0f,1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.bone1] run data merge entity @s { transformation: [-1f,0f,0f,0.3306f,0f,1f,0f,0.6627f,0f,0f,-1f,-0.0452f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.4] run data merge entity @s { transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1.1406f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.3] run data merge entity @s { transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.leftarm] run data merge entity @s { transformation: [-1f,0f,0f,0.375f,0f,1f,0f,1.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.8] run data merge entity @s { transformation: [-1f,0f,0f,-0.1312f,0f,1f,0f,0.3906f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.7] run data merge entity @s { transformation: [-1f,0f,0f,-0.1312f,0f,1f,0f,0.7656f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.rightleg] run data merge entity @s { transformation: [-1f,0f,0f,-0.1312f,0f,1f,0f,0.7656f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }

execute on passengers \
    if entity @s[tag=aj.isokla.node.group] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,0.5156f,0f,0f,-1f,-0.125f,0f,0f,0f,1f], start_interpolation: -1 }