# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.6499f,-0.0309f,0.7607f,0.1663f,-0.2248f,0.9634f,-0.1528f,1.2141f,-0.7274f,-0.27f,-0.6324f,-0.2104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.6427f,-0.0309f,0.76f,-0.0946f,-0.2223f,0.9624f,-0.1527f,1.3388f,-0.7194f,-0.2698f,-0.6318f,-0.1686f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.6427f,-0.0309f,0.76f,0.1699f,-0.2223f,0.9624f,-0.1527f,1.2134f,-0.7194f,-0.2698f,-0.6318f,-0.2134f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.6427f,-0.0309f,0.76f,0.0474f,-0.2223f,0.9624f,-0.1527f,1.3871f,-0.7194f,-0.2698f,-0.6318f,-0.0124f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.6427f,-0.0309f,0.76f,0.0623f,-0.2223f,0.9624f,-0.1527f,1.3985f,-0.7194f,-0.2698f,-0.6318f,-0.0042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.6427f,-0.0309f,0.7607f,0.161f,-0.2223f,0.9624f,-0.1528f,1.3803f,-0.7194f,-0.2698f,-0.6324f,-0.257f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6427f,-0.0309f,0.76f,0.1663f,-0.2223f,0.9624f,-0.1527f,1.2141f,-0.7194f,-0.2698f,-0.6318f,-0.2104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.6427f,-0.0247f,0.76f,-0.1256f,-0.2223f,0.7699f,-0.1527f,1.3813f,-0.7194f,-0.2158f,-0.6318f,-0.1716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.6427f,-0.0249f,0.76f,0.0351f,-0.2225f,0.7699f,-0.1527f,1.4368f,-0.7194f,-0.216f,-0.6318f,0.0083f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.6427f,-0.0309f,0.76f,0.1648f,-0.2223f,0.9624f,-0.1527f,1.2596f,-0.7194f,-0.2698f,-0.6318f,-0.2232f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.6427f,-0.0309f,0.76f,0.1657f,-0.2223f,0.9624f,-0.1527f,1.2322f,-0.7194f,-0.2698f,-0.6318f,-0.2154f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.6427f,-0.0309f,0.76f,0.1648f,-0.2223f,0.9624f,-0.1527f,1.2593f,-0.7194f,-0.2698f,-0.6318f,-0.223f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.6427f,-0.0309f,0.76f,0.1653f,-0.2223f,0.9624f,-0.1527f,1.2442f,-0.7194f,-0.2698f,-0.6318f,-0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.6427f,-0.0368f,0.76f,0.046f,-0.2223f,1.1453f,-0.1527f,1.2467f,-0.7194f,-0.321f,-0.6318f,-0.0662f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.6427f,-0.0368f,0.76f,0.038f,-0.2223f,1.1453f,-0.1527f,1.2439f,-0.7194f,-0.321f,-0.6318f,-0.0752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.6427f,-0.0309f,0.76f,0.1663f,-0.2223f,0.9624f,-0.1527f,1.2141f,-0.7194f,-0.2698f,-0.6318f,-0.2104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6492f,-0.0309f,0.76f,0.1663f,-0.2245f,0.9624f,-0.1527f,1.2141f,-0.7267f,-0.2698f,-0.6318f,-0.2104f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9813f,0.0476f,0.1813f,0.0394f,-0.1062f,0.6553f,-0.7466f,0.7438f,-0.1543f,-0.7535f,-0.639f,0.617f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9813f,0.1319f,0.1332f,0.0889f,-0.1062f,0.1942f,-0.9742f,0.7801f,-0.1543f,-0.9721f,-0.1766f,0.2773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9111f,0.3022f,0.2448f,0.1033f,-0.0133f,0.6047f,-0.7955f,1.0074f,-0.3846f,-0.7369f,-0.5525f,-0.054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.912f,0.3022f,0.2451f,0.2119f,-0.0133f,0.6047f,-0.7963f,1.2247f,-0.385f,-0.7369f,-0.553f,-0.3188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.6698f,0.6093f,-0.1632f,-0.302f,-0.2462f,0.5574f,0.7684f,0.8856f,0.4965f,-0.5455f,0.6013f,-0.3167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.7389f,0.4645f,-0.4657f,-0.1481f,-0.3256f,0.8678f,0.3472f,1.1883f,0.5711f,-0.1061f,0.8005f,-0.3432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.4196f,0.7033f,0.52f,0.3265f,-0.6944f,-0.0508f,-0.6178f,1.0764f,-0.3644f,-0.7056f,0.5748f,0.3068f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.49f,0.3119f,0.8034f,0.4127f,-0.7893f,0.2122f,-0.5593f,1.1656f,-0.3409f,-0.9254f,0.1411f,-0.0011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.8695f,0.448f,0.2052f,-0.264f,0.053f,0.4989f,-0.8639f,0.7525f,-0.4891f,-0.7417f,-0.4581f,0.4042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.8695f,0.4905f,-0.0463f,-0.1205f,0.053f,0.0001f,-0.9976f,0.7401f,-0.4891f,-0.8714f,-0.0259f,0.1479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera3":{"px":-0.879687125,"py":1.125,"pz":-0.22421831250000013,"ry":324.0971122595074,"rx":-7.867837490356317}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities