# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.6162f,-0.1444f,0.7755f,0.1115f,-0.3171f,0.9464f,-0.0757f,1.2292f,-0.7223f,-0.2923f,-0.6284f,-0.2208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.6094f,-0.1443f,0.7747f,-0.1619f,-0.3136f,0.9455f,-0.0756f,1.322f,-0.7144f,-0.292f,-0.6277f,-0.1811f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.6094f,-0.1443f,0.7747f,0.1152f,-0.3136f,0.9455f,-0.0756f,1.2289f,-0.7144f,-0.292f,-0.6277f,-0.2237f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.6094f,-0.1443f,0.7747f,-0.0271f,-0.3136f,0.9455f,-0.0756f,1.3905f,-0.7144f,-0.292f,-0.6277f,-0.026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.6094f,-0.1443f,0.7747f,-0.0143f,-0.3136f,0.9455f,-0.0756f,1.4046f,-0.7144f,-0.292f,-0.6277f,-0.0189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.6094f,-0.1443f,0.7755f,0.0864f,-0.3136f,0.9455f,-0.0757f,1.3938f,-0.7144f,-0.292f,-0.6284f,-0.2716f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6094f,-0.1443f,0.7747f,0.1115f,-0.3136f,0.9455f,-0.0756f,1.2292f,-0.7144f,-0.292f,-0.6277f,-0.2208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.6094f,-0.1154f,0.7747f,-0.1983f,-0.3136f,0.7564f,-0.0756f,1.3613f,-0.7144f,-0.2336f,-0.6277f,-0.1859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.6088f,-0.1189f,0.7747f,-0.0459f,-0.3179f,0.7546f,-0.0756f,1.4397f,-0.7131f,-0.2376f,-0.6277f,-0.0074f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.6094f,-0.1443f,0.7747f,0.1046f,-0.3136f,0.9455f,-0.0756f,1.2746f,-0.7144f,-0.292f,-0.6277f,-0.2348f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.6094f,-0.1443f,0.7747f,0.1088f,-0.3136f,0.9455f,-0.0756f,1.247f,-0.7144f,-0.292f,-0.6277f,-0.2262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.6094f,-0.1443f,0.7747f,0.1047f,-0.3136f,0.9455f,-0.0756f,1.2735f,-0.7144f,-0.292f,-0.6277f,-0.2344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.6094f,-0.1443f,0.7747f,0.107f,-0.3136f,0.9455f,-0.0756f,1.2588f,-0.7144f,-0.292f,-0.6277f,-0.2299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.6094f,-0.1717f,0.7747f,-0.0122f,-0.3136f,1.1251f,-0.0756f,1.2505f,-0.7144f,-0.3474f,-0.6277f,-0.0774f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.6094f,-0.1717f,0.7747f,-0.0199f,-0.3136f,1.1251f,-0.0756f,1.2466f,-0.7144f,-0.3474f,-0.6277f,-0.0863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.6094f,-0.1443f,0.7747f,0.1115f,-0.3136f,0.9455f,-0.0756f,1.2292f,-0.7144f,-0.292f,-0.6277f,-0.2208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6156f,-0.1443f,0.7747f,0.1115f,-0.3168f,0.9455f,-0.0756f,1.2292f,-0.7216f,-0.292f,-0.6277f,-0.2208f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9612f,-0.0283f,0.2708f,0.0388f,-0.2257f,0.6389f,-0.7341f,0.7662f,-0.1523f,-0.7685f,-0.6214f,0.6172f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9612f,0.1109f,0.2487f,0.0847f,-0.2257f,0.1862f,-0.9552f,0.8004f,-0.1523f,-0.9762f,-0.154f,0.2768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9018f,0.2305f,0.3395f,0.073f,-0.1304f,0.6193f,-0.7732f,1.0201f,-0.3846f,-0.7505f,-0.5338f,-0.0596f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9027f,0.2305f,0.3398f,0.1559f,-0.1305f,0.6193f,-0.774f,1.2426f,-0.385f,-0.7505f,-0.5343f,-0.3293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.6927f,0.5404f,-0.2554f,-0.314f,-0.1533f,0.6133f,0.7571f,0.845f,0.5023f,-0.5579f,0.5833f,-0.3197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.7705f,0.3583f,-0.5062f,-0.1972f,-0.2223f,0.9142f,0.3075f,1.1631f,0.5788f,-0.126f,0.792f,-0.3531f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.3665f,0.6609f,0.6157f,0.2853f,-0.7744f,-0.0755f,-0.4835f,1.1234f,-0.2409f,-0.7428f,0.6077f,0.2995f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.3916f,0.2874f,0.8638f,0.3613f,-0.8496f,0.2265f,-0.4564f,1.2151f,-0.3228f,-0.9299f,0.1544f,-0.0103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.8681f,0.3878f,0.3079f,-0.2628f,-0.062f,0.5315f,-0.8436f,0.7339f,-0.4906f,-0.7528f,-0.4379f,0.4041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.8681f,0.4898f,0.0727f,-0.118f,-0.062f,0.0385f,-0.9964f,0.7327f,-0.4906f,-0.8709f,-0.0028f,0.1482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera3":{"px":-0.7558186250000001,"py":1.125,"pz":-0.07970506250000013,"ry":331.5354117081596,"rx":-7.770198497778969}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities