# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.6249f,-0.1463f,0.7682f,0.1041f,-0.2489f,0.9694f,-0.0178f,1.2931f,-0.7413f,-0.2021f,-0.6415f,-0.1764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.618f,-0.1462f,0.7674f,-0.1702f,-0.2462f,0.9684f,-0.0178f,1.384f,-0.7332f,-0.2019f,-0.6409f,-0.127f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.618f,-0.1462f,0.7674f,0.1077f,-0.2462f,0.9684f,-0.0178f,1.293f,-0.7332f,-0.2019f,-0.6409f,-0.1794f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.618f,-0.1462f,0.7674f,-0.0336f,-0.2462f,0.9684f,-0.0178f,1.4378f,-0.7332f,-0.2019f,-0.6409f,0.0322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.618f,-0.1462f,0.7674f,-0.0192f,-0.2462f,0.9684f,-0.0178f,1.4492f,-0.7332f,-0.2019f,-0.6409f,0.0422f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.618f,-0.1462f,0.7682f,0.0791f,-0.2462f,0.9684f,-0.0178f,1.4584f,-0.7332f,-0.2019f,-0.6415f,-0.2109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.618f,-0.1462f,0.7674f,0.1041f,-0.2462f,0.9684f,-0.0178f,1.2931f,-0.7332f,-0.2019f,-0.6409f,-0.1764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.618f,-0.1169f,0.7674f,-0.2051f,-0.2462f,0.7747f,-0.0178f,1.4215f,-0.7332f,-0.1615f,-0.6409f,-0.126f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.6156f,-0.1289f,0.7674f,-0.0506f,-0.2611f,0.7698f,-0.0178f,1.4831f,-0.7299f,-0.1757f,-0.6409f,0.0573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.618f,-0.1462f,0.7674f,0.0973f,-0.2462f,0.9684f,-0.0178f,1.3379f,-0.7332f,-0.2019f,-0.6409f,-0.1858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.618f,-0.1462f,0.7674f,0.1013f,-0.2462f,0.9684f,-0.0178f,1.3113f,-0.7332f,-0.2019f,-0.6409f,-0.1802f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.618f,-0.1462f,0.7674f,0.0972f,-0.2462f,0.9684f,-0.0178f,1.3385f,-0.7332f,-0.2019f,-0.6409f,-0.1858f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.618f,-0.1462f,0.7674f,0.0994f,-0.2462f,0.9684f,-0.0178f,1.3234f,-0.7332f,-0.2019f,-0.6409f,-0.1827f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.618f,-0.174f,0.7674f,-0.018f,-0.2462f,1.1524f,-0.0178f,1.3012f,-0.7332f,-0.2403f,-0.6409f,-0.0303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.618f,-0.174f,0.7674f,-0.0258f,-0.2462f,1.1524f,-0.0178f,1.2981f,-0.7332f,-0.2403f,-0.6409f,-0.0394f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.618f,-0.1462f,0.7674f,0.1041f,-0.2462f,0.9684f,-0.0178f,1.2931f,-0.7332f,-0.2019f,-0.6409f,-0.1764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6242f,-0.1462f,0.7674f,0.1041f,-0.2486f,0.9684f,-0.0178f,1.2931f,-0.7406f,-0.2019f,-0.6409f,-0.1764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9632f,-0.0361f,0.2626f,0.0402f,-0.2103f,0.707f,-0.6739f,0.7549f,-0.1614f,-0.7059f,-0.6895f,0.6161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9632f,0.1001f,0.2455f,0.0823f,-0.2103f,0.2754f,-0.9371f,0.8202f,-0.1614f,-0.9561f,-0.2442f,0.2798f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9063f,0.2229f,0.3322f,0.0671f,-0.094f,0.6858f,-0.7208f,1.07f,-0.3846f,-0.6928f,-0.6066f,-0.0348f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9072f,0.2229f,0.3325f,0.1472f,-0.0941f,0.6858f,-0.7216f,1.3165f,-0.385f,-0.6928f,-0.6072f,-0.2838f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.6982f,0.535f,-0.2476f,-0.3232f,-0.1993f,0.6619f,0.7002f,0.9198f,0.4781f,-0.5052f,0.6535f,-0.3054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.7767f,0.3582f,-0.4967f,-0.2062f,-0.275f,0.9218f,0.2335f,1.2396f,0.547f,-0.0453f,0.8227f,-0.3107f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.3609f,0.697f,0.5787f,0.2836f,-0.7386f,-0.0067f,-0.5547f,1.1397f,-0.3404f,-0.7126f,0.5835f,0.3299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.3965f,0.2771f,0.8648f,0.3562f,-0.8161f,0.3111f,-0.469f,1.2596f,-0.3952f,-0.9083f,0.1017f,0.029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.8737f,0.38f,0.3016f,-0.2639f,-0.0162f,0.5985f,-0.7998f,0.7424f,-0.4842f,-0.705f,-0.5173f,0.4044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.8737f,0.4799f,0.0712f,-0.122f,-0.0162f,0.1184f,-0.9919f,0.7648f,-0.4842f,-0.8692f,-0.0954f,0.1479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera3":{"px":-1.032548,"py":1.125,"pz":-0.40255600000000014,"ry":314.9153733891104,"rx":-7.976065195626253}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities