# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.611f,-0.1948f,0.7686f,0.077f,-0.2837f,0.9598f,0.0177f,1.3006f,-0.7404f,-0.207f,-0.641f,-0.179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.6043f,-0.1946f,0.7678f,-0.2013f,-0.2806f,0.9588f,0.0177f,1.3777f,-0.7323f,-0.2068f,-0.6404f,-0.13f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.6043f,-0.1946f,0.7678f,0.0806f,-0.2806f,0.9588f,0.0177f,1.3007f,-0.7323f,-0.2068f,-0.6404f,-0.182f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.6043f,-0.1946f,0.7678f,-0.0677f,-0.2806f,0.9588f,0.0177f,1.4391f,-0.7323f,-0.2068f,-0.6404f,0.029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.6043f,-0.1946f,0.7678f,-0.0541f,-0.2806f,0.9588f,0.0177f,1.4514f,-0.7323f,-0.2068f,-0.6404f,0.0388f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.6043f,-0.1946f,0.7686f,0.0438f,-0.2806f,0.9588f,0.0177f,1.4646f,-0.7323f,-0.2068f,-0.641f,-0.2143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6043f,-0.1946f,0.7678f,0.077f,-0.2806f,0.9588f,0.0177f,1.3006f,-0.7323f,-0.2068f,-0.6404f,-0.179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.6043f,-0.1557f,0.7678f,-0.2383f,-0.2806f,0.7671f,0.0177f,1.4136f,-0.7323f,-0.1654f,-0.6404f,-0.1294f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.6007f,-0.1688f,0.7678f,-0.0872f,-0.2972f,0.7608f,0.0177f,1.4837f,-0.7285f,-0.1813f,-0.6404f,0.0537f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.6043f,-0.1946f,0.7678f,0.068f,-0.2806f,0.9588f,0.0177f,1.3452f,-0.7323f,-0.2068f,-0.6404f,-0.1886f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.6043f,-0.1946f,0.7678f,0.0733f,-0.2806f,0.9588f,0.0177f,1.3186f,-0.7323f,-0.2068f,-0.6404f,-0.1828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.6043f,-0.1946f,0.7678f,0.0679f,-0.2806f,0.9588f,0.0177f,1.3456f,-0.7323f,-0.2068f,-0.6404f,-0.1886f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.6043f,-0.1946f,0.7678f,0.0709f,-0.2806f,0.9588f,0.0177f,1.3306f,-0.7323f,-0.2068f,-0.6404f,-0.1854f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.6043f,-0.2315f,0.7678f,-0.0454f,-0.2806f,1.141f,0.0177f,1.3032f,-0.7323f,-0.2461f,-0.6404f,-0.0329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.6043f,-0.2315f,0.7678f,-0.053f,-0.2806f,1.141f,0.0177f,1.2997f,-0.7323f,-0.2461f,-0.6404f,-0.0421f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.6043f,-0.1946f,0.7678f,0.077f,-0.2806f,0.9588f,0.0177f,1.3006f,-0.7323f,-0.2068f,-0.6404f,-0.179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6104f,-0.1946f,0.7678f,0.077f,-0.2834f,0.9588f,0.0177f,1.3006f,-0.7397f,-0.2068f,-0.6404f,-0.179f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9513f,-0.071f,0.2967f,0.0398f,-0.2593f,0.7008f,-0.6632f,0.7638f,-0.1608f,-0.7095f,-0.686f,0.6162f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9513f,0.0868f,0.2925f,0.0788f,-0.2593f,0.2753f,-0.9247f,0.8295f,-0.1608f,-0.9574f,-0.2394f,0.2796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9001f,0.1886f,0.3685f,0.0512f,-0.1414f,0.6927f,-0.7062f,1.0767f,-0.3846f,-0.6961f,-0.6029f,-0.0363f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.901f,0.1886f,0.3689f,0.119f,-0.1415f,0.6927f,-0.7069f,1.3256f,-0.385f,-0.6961f,-0.6035f,-0.2864f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.707f,0.5014f,-0.283f,-0.3308f,-0.1615f,0.6855f,0.6901f,0.9057f,0.4794f,-0.5082f,0.6499f,-0.3063f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.7892f,0.3114f,-0.5085f,-0.2301f,-0.2329f,0.9384f,0.2122f,1.2309f,0.5488f,-0.0497f,0.8213f,-0.3131f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.3346f,0.6509f,0.6475f,0.2637f,-0.7708f,0.0111f,-0.4978f,1.1589f,-0.2933f,-0.7551f,0.5613f,0.3282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.3546f,0.2618f,0.8872f,0.3304f,-0.8369f,0.3202f,-0.4244f,1.2808f,-0.3914f,-0.9097f,0.1045f,0.0267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.8714f,0.35f,0.3419f,-0.2631f,-0.0625f,0.6134f,-0.7862f,0.735f,-0.4846f,-0.7078f,-0.5131f,0.4044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.8714f,0.474f,0.1211f,-0.1224f,-0.0625f,0.1381f,-0.9875f,0.7632f,-0.4846f,-0.8696f,-0.0905f,0.1478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera3":{"px":-1.009140875,"py":1.125,"pz":-0.3752476875000001,"ry":316.3215112940164,"rx":-7.960474005183444}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities