# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0f,0f,0f,0f,1.001f,0.0004f,1.4039f,0f,0.0004f,-1.001f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-1.0059f,0f,0f,-0.1069f,0f,1.0161f,0.0004f,1.523f,0f,0.0004f,-1.0161f,0.2202f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4039f,0f,0.0004f,-1f,-0.0266f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-1.0059f,0f,0f,0.1069f,0f,1.0161f,0.0004f,1.523f,0f,0.0004f,-1.0161f,0.22f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0f,0f,0.1237f,0f,1f,0.0004f,1.5288f,0f,0.0004f,-1f,0.2156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,2.3188f,0.0004f,1.6266f,0f,0.001f,-1.0247f,-0.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4039f,0f,0.0004f,-1f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9899f,0.0117f,0f,-0.1238f,0.0094f,0.7999f,0.0004f,1.5574f,0f,0.0003f,-1f,0.2492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,-0.0117f,0f,0.1237f,-0.0094f,0.7999f,0.0004f,1.5574f,0f,0.0003f,-1f,0.2492f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4485f,0f,0.0004f,-1f,-0.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4243f,0f,0.0004f,-1f,-0.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4541f,0f,0.0004f,-1f,-0.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4351f,0f,0.0004f,-1f,-0.0227f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.0319f,0f,1.1042f,0.0004f,1.4016f,0f,0.0005f,-1f,0.1647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1.1042f,0.0004f,1.3992f,0f,0.0005f,-1f,0.1647f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4039f,0f,0.0004f,-1f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0004f,1.4039f,0f,0.0004f,-1f,-0.0228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9977f,-0.0371f,-0.034f,0.1372f,-0.0494f,0.8482f,0.5273f,0.4658f,0.0093f,0.5278f,-0.8481f,-0.1012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9977f,-0.0495f,-0.0091f,0.1201f,-0.0494f,0.9988f,-0.0038f,0.8091f,0.0093f,-0.0034f,-0.999f,-0.1023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,0.9988f,0.0484f,1.1596f,0f,0.0485f,-0.9978f,-0.0943f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.984f,0.1784f,1.5132f,0f,0.1784f,-0.984f,-0.0302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9804f,0.0305f,0.1189f,-0.3962f,-0.0221f,0.9871f,-0.0691f,1.1085f,-0.1205f,0.0667f,0.9796f,-0.1771f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9814f,0.0778f,0.0949f,-0.3685f,-0.0221f,0.8654f,-0.4798f,1.4024f,-0.1207f,0.4745f,0.8596f,-0.0062f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9844f,-0.0103f,0.0908f,0.3743f,-0.0442f,0.9452f,-0.3216f,1.0403f,-0.0826f,-0.3204f,-0.932f,-0.0066f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9854f,-0.0408f,0.0818f,0.3588f,-0.0443f,0.9981f,0.0222f,1.3704f,-0.0827f,0.0187f,-0.9854f,0.0242f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9986f,0.0186f,0.0223f,-0.1395f,0.0157f,0.9938f,-0.1099f,0.4463f,-0.0242f,-0.1094f,-0.9927f,0.0478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9986f,0.0241f,0.0161f,-0.1312f,0.0157f,0.9216f,-0.3878f,0.7631f,-0.0242f,-0.3871f,-0.9207f,-0.0853f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-9.950255243072244e-17,"py":1.59375,"pz":0.8125,"ry":180.23919624455027,"rx":-0.2391962445502846}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities