# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0f,0f,0f,0f,1.001f,0.0004f,1.396f,0f,0.0004f,-1.001f,-0.007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-1.0062f,0f,0f,-0.1069f,0f,1.0164f,0.0004f,1.5151f,0f,0.0004f,-1.0164f,0.2359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.396f,0f,0.0004f,-1f,-0.0109f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-1.0062f,0f,0f,0.1069f,0f,1.0164f,0.0004f,1.5151f,0f,0.0004f,-1.0164f,0.2358f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0f,0f,0.1237f,0f,1f,0.0004f,1.5209f,0f,0.0004f,-1f,0.2314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,2.3574f,0.0004f,1.6195f,0f,0.0009f,-1.0254f,-0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.396f,0f,0.0004f,-1f,-0.007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9899f,0.0115f,0f,-0.1238f,0.0093f,0.7999f,0.0004f,1.5494f,0f,0.0003f,-1f,0.2649f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,-0.0115f,0f,0.1237f,-0.0093f,0.7999f,0.0004f,1.5494f,0f,0.0003f,-1f,0.2649f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4406f,0f,0.0004f,-1f,-0.007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4166f,0f,0.0004f,-1f,-0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.446f,0f,0.0004f,-1f,-0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.4272f,0f,0.0004f,-1f,-0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.032f,0f,1.1059f,0.0004f,1.3936f,0f,0.0004f,-1f,0.1805f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1.1059f,0.0004f,1.3913f,0f,0.0004f,-1f,0.1805f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0f,0f,0f,0f,1f,0.0004f,1.396f,0f,0.0004f,-1f,-0.007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0004f,1.396f,0f,0.0004f,-1f,-0.007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9975f,-0.0426f,-0.0344f,0.1387f,-0.0541f,0.8639f,0.5007f,0.4562f,0.0083f,0.5013f,-0.8641f,-0.0824f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9975f,-0.0542f,-0.0075f,0.12f,-0.0541f,0.9984f,-0.0151f,0.7994f,0.0083f,-0.0146f,-0.9989f,-0.0875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,0.9989f,0.0478f,1.1517f,0f,0.0478f,-0.9979f,-0.0782f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.9841f,0.1778f,1.5054f,0f,0.1778f,-0.9841f,-0.0143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9808f,0.041f,0.112f,-0.3951f,-0.0346f,0.9875f,-0.0567f,1.1002f,-0.1139f,0.0532f,0.9812f,-0.1573f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9818f,0.0845f,0.0841f,-0.3652f,-0.0347f,0.871f,-0.4688f,1.3958f,-0.114f,0.4628f,0.8668f,0.0101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9839f,-0.0111f,0.0956f,0.3759f,-0.0463f,0.9459f,-0.3191f,1.038f,-0.087f,-0.3181f,-0.9324f,0.0069f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9849f,-0.0438f,0.0857f,0.3593f,-0.0464f,0.9978f,0.0316f,1.3677f,-0.0871f,0.0278f,-0.9848f,0.0408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9984f,0.0234f,0.026f,-0.1414f,0.02f,0.9934f,-0.1127f,0.4388f,-0.0285f,-0.112f,-0.9923f,0.0591f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9984f,0.0295f,0.0188f,-0.1312f,0.02f,0.9268f,-0.375f,0.7574f,-0.0285f,-0.3741f,-0.9259f,-0.0695f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-9.950255243072244e-17,"py":1.59375,"pz":0.8125,"ry":180.18498985099893,"rx":-0.18498985099891926}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities