# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0f,0f,0f,0f,1.0008f,0.0184f,1.4063f,0f,0.0184f,-1.0008f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-1.0078f,0f,0f,-0.1073f,0f,1.0178f,0.0187f,1.5217f,0f,0.0187f,-1.0178f,0.2139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0f,0f,0f,0f,0.9998f,0.0184f,1.4063f,0f,0.0184f,-0.9998f,-0.0349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-1.0078f,0f,0f,0.1083f,0f,1.0178f,0.0187f,1.5236f,0f,0.0187f,-1.0178f,0.2139f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0f,0f,0.1237f,0f,0.9998f,0.0184f,1.5268f,0f,0.0184f,-0.9998f,0.2096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,2.7193f,0.019f,1.6217f,0f,0.05f,-1.0317f,-0.0273f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0f,0f,0f,0f,0.9998f,0.0184f,1.4063f,0f,0.0184f,-0.9998f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9899f,0.0105f,0f,-0.1238f,0.0085f,0.7998f,0.0184f,1.5486f,0.0002f,0.0147f,-0.9998f,0.2433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,-0.0105f,0f,0.1237f,-0.0085f,0.7998f,0.0184f,1.5486f,-0.0002f,0.0147f,-0.9998f,0.2433f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,0.9998f,0.0184f,1.4502f,0f,0.0184f,-0.9998f,-0.0304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,0.9998f,0.0184f,1.4277f,0f,0.0184f,-0.9998f,-0.0308f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,0.9998f,0.0184f,1.4538f,0f,0.0184f,-0.9998f,-0.0303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0f,0f,0f,0f,0.9998f,0.0184f,1.4375f,0f,0.0184f,-0.9998f,-0.0306f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.0336f,0f,1.1163f,0.0184f,1.4f,0f,0.0205f,-0.9998f,0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1.1163f,0.0184f,1.3995f,0f,0.0205f,-0.9998f,0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0f,0f,0f,0f,0.9998f,0.0184f,1.4063f,0f,0.0184f,-0.9998f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0184f,1.4063f,0f,0.0184f,-0.9998f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}