# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0f,0f,0f,0f,0.9992f,0.0605f,1.4063f,0f,0.0605f,-0.9992f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-1.0078f,0f,0f,-0.1079f,0f,1.0161f,0.0615f,1.5124f,0f,0.0615f,-1.0161f,0.2189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0f,0f,0f,0f,0.9982f,0.0604f,1.4065f,0f,0.0604f,-0.9982f,-0.0346f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-1.0078f,0f,0f,0.1083f,0f,1.0161f,0.0615f,1.5132f,0f,0.0615f,-1.0161f,0.2189f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0f,0f,0.1237f,0f,0.9982f,0.0604f,1.5166f,0f,0.0604f,-0.9982f,0.2147f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,3.0265f,0.0627f,1.5909f,0f,0.1831f,-1.0355f,-0.0201f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0f,0f,0f,0f,0.9982f,0.0604f,1.4063f,0f,0.0604f,-0.9982f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9899f,0.0105f,0f,-0.1238f,0.0085f,0.7985f,0.0604f,1.5252f,0.0005f,0.0483f,-0.9982f,0.2483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,-0.0105f,0f,0.1237f,-0.0085f,0.7985f,0.0604f,1.5252f,-0.0005f,0.0483f,-0.9982f,0.2483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,0.9982f,0.0604f,1.4499f,0f,0.0604f,-0.9982f,-0.0286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,0.9982f,0.0604f,1.4268f,0f,0.0604f,-0.9982f,-0.0299f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,0.9982f,0.0604f,1.453f,0f,0.0604f,-0.9982f,-0.0284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0f,0f,0f,0f,0.9982f,0.0604f,1.4374f,0f,0.0604f,-0.9982f,-0.0293f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.034f,0f,1.1145f,0.0604f,1.3924f,0f,0.0674f,-0.9982f,0.1558f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1.1145f,0.0604f,1.3924f,0f,0.0674f,-0.9982f,0.1558f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0f,0f,0f,0f,0.9982f,0.0604f,1.4063f,0f,0.0604f,-0.9982f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9982f,0.0604f,1.4063f,0f,0.0604f,-0.9982f,-0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}