# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0f,0f,0f,0f,1.0009f,-0.0126f,1.3698f,0f,-0.0126f,-1.0009f,0.0117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9939f,0f,0f,-0.1073f,0f,1.0039f,-0.0126f,1.4932f,0f,-0.0126f,-1.0039f,0.2535f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0126f,1.3697f,0f,-0.0126f,-0.9999f,0.007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9939f,0f,0f,0.1073f,0f,1.0039f,-0.0126f,1.4931f,0f,-0.0126f,-1.0039f,0.2523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0f,0f,0.1237f,0f,0.9999f,-0.0126f,1.4978f,0f,-0.0126f,-0.9999f,0.2476f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,0.9954f,-0.0126f,1.5507f,0f,-0.0125f,-1.0008f,0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0126f,1.3698f,0f,-0.0126f,-0.9999f,0.0117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9899f,0.015f,0f,-0.1238f,0.0121f,0.7998f,-0.0126f,1.5335f,-0.0002f,-0.0101f,-0.9999f,0.2815f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,-0.015f,0f,0.1237f,-0.0121f,0.7998f,-0.0126f,1.5335f,0.0002f,-0.0101f,-0.9999f,0.2815f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0126f,1.4144f,0f,-0.0126f,-0.9999f,0.0111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0126f,1.3883f,0f,-0.0126f,-0.9999f,0.0115f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0126f,1.4172f,0f,-0.0126f,-0.9999f,0.0112f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0126f,1.401f,0f,-0.0126f,-0.9999f,0.0114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.0312f,0f,1.0257f,-0.0126f,1.3745f,0f,-0.0129f,-0.9999f,0.1991f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1.0257f,-0.0126f,1.3716f,0f,-0.0129f,-0.9999f,0.1992f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0126f,1.3698f,0f,-0.0126f,-0.9999f,0.0117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9999f,-0.0126f,1.3698f,0f,-0.0126f,-0.9999f,0.0117f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9977f,-0.001f,-0.0512f,0.1226f,-0.014f,0.9672f,0.2538f,0.4292f,0.0493f,0.2537f,-0.965f,-0.0322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9977f,-0.0194f,-0.0474f,0.1159f,-0.014f,0.9935f,-0.1125f,0.7707f,0.0493f,-0.1118f,-0.9915f,-0.0706f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,0.9999f,-0.0108f,1.1224f,0f,-0.0108f,-0.9989f,-0.02f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.9928f,0.1198f,1.4792f,0f,0.1198f,-0.9928f,0.023f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9827f,0.0179f,0.1009f,-0.3512f,-0.0386f,0.9675f,0.2062f,1.0729f,-0.0948f,-0.2084f,0.9622f,-0.0481f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9837f,0.0589f,0.0839f,-0.33f,-0.0387f,0.964f,-0.222f,1.3928f,-0.0949f,0.2178f,0.9601f,0.042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9835f,-0.0868f,0.0435f,0.3818f,-0.0976f,0.9757f,-0.1935f,1.0472f,-0.0263f,-0.192f,-0.97f,-0.1057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9845f,-0.0967f,0.0087f,0.3495f,-0.0977f,0.9789f,0.1766f,1.3671f,-0.0263f,0.1759f,-0.9731f,-0.0231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.999f,-0.0034f,-0.0088f,-0.1289f,-0.007f,0.9099f,0.4147f,0.3966f,0.0065f,0.4147f,-0.9089f,-0.0339f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.999f,-0.007f,-0.0063f,-0.1312f,-0.007f,0.9993f,-0.0359f,0.7401f,0.0065f,-0.0354f,-0.9984f,-0.0461f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-9.950255243072244e-17,"py":1.59375,"pz":0.8125,"ry":182.89441147582232,"rx":-2.8944114758223063}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities