# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0f,0f,0f,0f,1.0009f,-0.0128f,1.3567f,0f,-0.0128f,-1.0009f,0.0286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9948f,0f,0f,-0.1072f,0f,1.0047f,-0.0128f,1.4798f,0f,-0.0128f,-1.0047f,0.2704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0127f,1.3566f,0f,-0.0127f,-0.9999f,0.024f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9948f,0f,0f,0.1072f,0f,1.0047f,-0.0128f,1.4798f,0f,-0.0128f,-1.0047f,0.2692f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0f,0f,0.1237f,0f,0.9999f,-0.0127f,1.4847f,0f,-0.0127f,-0.9999f,0.2646f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,1.015f,-0.0128f,1.5406f,0f,-0.0129f,-1.0012f,0.0263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0127f,1.3567f,0f,-0.0127f,-0.9999f,0.0286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.9899f,0.0114f,0f,-0.1238f,0.0092f,0.7999f,-0.0127f,1.5203f,-0.0001f,-0.0102f,-0.9999f,0.2984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.9899f,-0.0114f,0f,0.1237f,-0.0092f,0.7999f,-0.0127f,1.5203f,0.0001f,-0.0102f,-0.9999f,0.2984f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0127f,1.4013f,0f,-0.0127f,-0.9999f,0.028f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0127f,1.3748f,0f,-0.0127f,-0.9999f,0.0284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0127f,1.4046f,0f,-0.0127f,-0.9999f,0.0281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0127f,1.3879f,0f,-0.0127f,-0.9999f,0.0283f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.031f,0f,1.0311f,-0.0127f,1.3614f,0f,-0.0131f,-0.9999f,0.2161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1.0311f,-0.0127f,1.3582f,0f,-0.0131f,-0.9999f,0.2161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0f,0f,0f,0f,0.9999f,-0.0127f,1.3567f,0f,-0.0127f,-0.9999f,0.0286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,0.9999f,-0.0127f,1.3567f,0f,-0.0127f,-0.9999f,0.0286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.997f,0.0028f,-0.0634f,0.1189f,-0.0047f,0.9931f,0.117f,0.4103f,0.0633f,0.1167f,-0.9902f,-0.0041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.997f,-0.0149f,-0.0617f,0.1138f,-0.0047f,0.9867f,-0.1623f,0.7495f,0.0633f,-0.1619f,-0.9838f,-0.0597f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,1f,-0.0041f,1.1095f,0f,-0.0041f,-0.999f,-0.0022f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.992f,0.1265f,1.466f,0f,0.1265f,-0.992f,0.0432f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9839f,0.0218f,0.0871f,-0.3328f,-0.0486f,0.9366f,0.3171f,1.0569f,-0.0753f,-0.3196f,0.9329f,0.007f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9849f,0.0566f,0.0697f,-0.3126f,-0.0487f,0.9828f,-0.1084f,1.3862f,-0.0754f,0.1047f,0.9806f,0.0581f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9809f,-0.118f,0.0232f,0.3853f,-0.1236f,0.9815f,-0.1424f,1.0453f,-0.0068f,-0.139f,-0.9795f,-0.1132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9819f,-0.118f,-0.0234f,0.3468f,-0.1238f,0.962f,0.2409f,1.3579f,-0.0068f,0.2433f,-0.959f,-0.0086f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9989f,0.0013f,-0.0177f,-0.1287f,-0.0096f,0.8109f,0.585f,0.3861f,0.015f,0.585f,-0.8098f,-0.0708f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9989f,-0.0075f,-0.0161f,-0.1312f,-0.0096f,0.9937f,0.111f,0.7276f,0.015f,0.1116f,-0.9927f,-0.0325f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-9.950255243072244e-17,"py":1.59375,"pz":0.8125,"ry":183.01853624340848,"rx":-3.018536243408482}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities