# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0f,0f,0f,0f,1.001f,-0.0058f,1.3662f,0f,-0.0058f,-1.001f,0.0332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9989f,0f,0f,-0.1069f,0f,1.009f,-0.0058f,1.487f,0f,-0.0058f,-1.009f,0.2756f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0058f,1.3662f,0f,-0.0058f,-1f,0.0288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9989f,0f,0f,0.1069f,0f,1.009f,-0.0058f,1.487f,0f,-0.0058f,-1.009f,0.2748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0f,0f,0.1237f,0f,1f,-0.0058f,1.4926f,0f,-0.0058f,-1f,0.2703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,1.3444f,-0.0058f,1.565f,0f,-0.0078f,-1.0072f,0.0321f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0058f,1.3662f,0f,-0.0058f,-1f,0.0332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,0.0031f,0f,-0.1238f,0.0025f,0.8f,-0.0058f,1.5262f,0f,-0.0046f,-1f,0.3042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.99f,-0.0031f,0f,0.1237f,-0.0025f,0.8f,-0.0058f,1.5262f,0f,-0.0046f,-1f,0.3042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0058f,1.4111f,0f,-0.0058f,-1f,0.0329f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0058f,1.384f,0f,-0.0058f,-1f,0.0332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0058f,1.4171f,0f,-0.0058f,-1f,0.033f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0058f,1.3975f,0f,-0.0058f,-1f,0.0331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.0304f,0f,1.0582f,-0.0058f,1.3686f,0f,-0.0061f,-1f,0.2207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1.0582f,-0.0058f,1.3648f,0f,-0.0061f,-1f,0.2207f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0058f,1.3662f,0f,-0.0058f,-1f,0.0332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0058f,1.3662f,0f,-0.0058f,-1f,0.0332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9979f,-0.032f,-0.0337f,0.1356f,-0.0451f,0.8424f,0.537f,0.4384f,0.0113f,0.5374f,-0.8421f,-0.0483f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9979f,-0.0451f,-0.0113f,0.1201f,-0.0451f,0.999f,0.0002f,0.7818f,0.0113f,0.0007f,-0.9989f,-0.048f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,0.9997f,0.0259f,1.1206f,0f,0.0259f,-0.9987f,-0.0159f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.9877f,0.1562f,1.4756f,0f,0.1562f,-0.9877f,0.0402f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.98f,0.023f,0.1233f,-0.3954f,-0.0144f,0.9873f,-0.0685f,1.0834f,-0.1244f,0.0669f,0.9791f,-0.1224f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.981f,0.073f,0.102f,-0.3695f,-0.0144f,0.8659f,-0.4793f,1.3742f,-0.1246f,0.4744f,0.8591f,0.0478f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9848f,-0.0122f,0.0863f,0.3592f,-0.0444f,0.946f,-0.319f,1.0224f,-0.0778f,-0.3178f,-0.9333f,-0.0261f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9858f,-0.0408f,0.077f,0.3438f,-0.0445f,0.9982f,0.021f,1.3526f,-0.0779f,0.0178f,-0.9858f,0.0045f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9988f,0.0139f,0.0192f,-0.1378f,0.0118f,0.9958f,-0.0902f,0.4172f,-0.0203f,-0.0899f,-0.9947f,0.101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9988f,0.0191f,0.0141f,-0.1312f,0.0118f,0.9226f,-0.3855f,0.7344f,-0.0203f,-0.3849f,-0.9217f,-0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera1":{"px":-9.950255243072244e-17,"py":1.59375,"pz":0.8125,"ry":182.5,"rx":-2.5000000000000155}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function aj:stellar/root/on_tick/transform_floating_entities