# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage aj:chain_lock rig_hash set value '5d1728327da49653b238fdd52c9acc223c8195075f23afed8f5d1301b266c063'
scoreboard objectives add aj.lock.frame dummy
scoreboard objectives add aj.unlock.frame dummy