# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:fsc_fx rig_hash set value 'ddaf28339bcac856ae9909e0f314017f139a5554b5aa356531eefd5cd97acd86'
scoreboard objectives add aj.run.frame dummy