# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data merge value {"locators":{},"cameras":{"camera2":{"posx":0.12500000000000033,"posy":2.8125,"posz":-2.6875,"roty":0,"rotx":22.499999999999996}}}

execute on vehicle \
    unless entity @s[tag=aj.transforms_only] at @s run function animated_java:ruins_of_the_finality_skill/animations/skills/zzz/frames/zzz/1