# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide13] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide13 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide14] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide14 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide8] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide8 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide9] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide9 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide10] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide10 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide21] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide21 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide22] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide22 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide23] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide23 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide24] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide24 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide25] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide25 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide26] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide26 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide27] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide27 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide28] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide28 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide29] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide29 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide30] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide30 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide46] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide46 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide94] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide94 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide15] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide15 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide19] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide19 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide43] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide43 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide44] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide44 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide45] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide45 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide47] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide47 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide48] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide48 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide42] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide42 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide41] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide41 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide40] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide40 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide91] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide91 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide61] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide61 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide90] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide90 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide92] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide92 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide93] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide93 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide56] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide56 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide57] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide57 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide58] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide58 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide59] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide59 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide17] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide17 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide89] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide89 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide11] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide11 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide60] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide60 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide12] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide12 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide124] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide124 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide5] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide5 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide7] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide7 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide6] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide6 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide31] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide31 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide32] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide32 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide33] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide33 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide116] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide116 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide117] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide117 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide118] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide118 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide49] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide49 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide50] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide50 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide39] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide39 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide51] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide51 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide52] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide52 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide38] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide38 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide34] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide34 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide37] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide37 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide95] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide95 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide36] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide36 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide35] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide35 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide53] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide53 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide54] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide54 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide55] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide55 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide119] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide119 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.guide97] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_guide97 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.layer] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_layer set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.6] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_6 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.12] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_12 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.10] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_10 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.9] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_9 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.item_display] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.8] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_8 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.segrina.node.7] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_7 set from storage animated_java:gu out