# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.yibb_tstll.root] run return 0
execute on passengers if entity @s[tag=aj.yibb_tstll.data] unless data entity @s {data:{rigHash: '94a538ab0184280835924e3e34dd0d1a25d3c032a4cba7fbaa79afacfd932524'}} on vehicle run function animated_java:yibb_tstll/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1