# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.7305f,-0.0667f,0.6811f,0.0787f,-0.2116f,0.9695f,-0.1319f,1.2333f,-0.6508f,-0.2402f,-0.7216f,-0.2281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.7225f,-0.0667f,0.6804f,-0.1783f,-0.2092f,0.9685f,-0.1318f,1.3586f,-0.6437f,-0.24f,-0.7209f,-0.1556f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.7225f,-0.0667f,0.6804f,0.0819f,-0.2092f,0.9685f,-0.1318f,1.2327f,-0.6437f,-0.24f,-0.7209f,-0.2316f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.7225f,-0.0667f,0.6804f,-0.0125f,-0.2092f,0.9685f,-0.1318f,1.4061f,-0.6437f,-0.24f,-0.7209f,-0.01f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.7225f,-0.0667f,0.6804f,-0.0009f,-0.2092f,0.9685f,-0.1318f,1.4118f,-0.6437f,-0.24f,-0.7209f,-0.0065f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.7225f,-0.0577f,0.6795f,0.0676f,-0.2092f,0.8386f,-0.1316f,1.3942f,-0.6437f,-0.2078f,-0.7199f,-0.268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.7225f,-0.0667f,0.6804f,0.0787f,-0.2092f,0.9685f,-0.1318f,1.2333f,-0.6437f,-0.24f,-0.7209f,-0.2281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.7225f,-0.0533f,0.6804f,-0.2074f,-0.2092f,0.7748f,-0.1318f,1.3996f,-0.6437f,-0.192f,-0.7209f,-0.1514f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.7217f,-0.0633f,0.6804f,-0.0268f,-0.2199f,0.7718f,-0.1318f,1.4519f,-0.641f,-0.2008f,-0.7209f,0.0096f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.7225f,-0.0667f,0.6804f,0.0757f,-0.2092f,0.9685f,-0.1318f,1.2762f,-0.6437f,-0.24f,-0.7209f,-0.2387f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.7225f,-0.0667f,0.6804f,0.0774f,-0.2092f,0.9685f,-0.1318f,1.2517f,-0.6437f,-0.24f,-0.7209f,-0.2326f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.7225f,-0.0667f,0.6804f,0.0755f,-0.2092f,0.9685f,-0.1318f,1.2787f,-0.6437f,-0.24f,-0.7209f,-0.2393f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.7225f,-0.0667f,0.6804f,0.0766f,-0.2092f,0.9685f,-0.1318f,1.2636f,-0.6437f,-0.24f,-0.7209f,-0.2356f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.7225f,-0.0794f,0.6804f,-0.0238f,-0.2092f,1.1529f,-0.1318f,1.2617f,-0.6437f,-0.2857f,-0.7209f,-0.0699f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.7225f,-0.0794f,0.6804f,-0.0332f,-0.2092f,1.1529f,-0.1318f,1.2642f,-0.6437f,-0.2857f,-0.7209f,-0.0792f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.7225f,-0.0667f,0.6804f,0.0787f,-0.2092f,0.9685f,-0.1318f,1.2333f,-0.6437f,-0.24f,-0.7209f,-0.2281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.7298f,-0.0667f,0.6804f,0.0787f,-0.2114f,0.9685f,-0.1318f,1.2333f,-0.6502f,-0.24f,-0.7209f,-0.2281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9922f,-0.0447f,0.1075f,0.0527f,-0.1094f,0.6738f,-0.7294f,0.742f,-0.0398f,-0.7372f,-0.6744f,0.5964f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9922f,0.015f,0.1154f,0.0614f,-0.1094f,0.2188f,-0.9686f,0.787f,-0.0398f,-0.9756f,-0.2155f,0.2543f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9501f,0.2103f,0.181f,0.0355f,-0.0104f,0.6247f,-0.78f,1.0223f,-0.2743f,-0.752f,-0.5973f,-0.0705f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9511f,0.2103f,0.1812f,0.1111f,-0.0104f,0.6247f,-0.7808f,1.2468f,-0.2746f,-0.752f,-0.5979f,-0.3408f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.736f,0.5134f,-0.1177f,-0.3933f,-0.1838f,0.5281f,0.8106f,0.8527f,0.4247f,-0.6611f,0.5548f,-0.2574f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.8169f,0.4122f,-0.3757f,-0.2563f,-0.2546f,0.8695f,0.3985f,1.1566f,0.4959f,-0.2327f,0.8235f,-0.3271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.8077f,0.3338f,0.2476f,0.3927f,-0.2764f,-0.1257f,-0.9343f,0.9913f,-0.2497f,-0.9301f,0.2259f,0.2136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9033f,0.046f,0.4023f,0.4035f,-0.3384f,0.4678f,-0.8061f,1.1685f,-0.2212f,-0.8819f,-0.4081f,-0.067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.9215f,0.3549f,0.1531f,-0.2739f,0.0587f,0.5201f,-0.851f,0.7537f,-0.3813f,-0.7767f,-0.5007f,0.4213f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.9215f,0.3839f,-0.0449f,-0.1617f,0.0587f,0.0249f,-0.997f,0.7486f,-0.3813f,-0.923f,-0.0452f,0.1496f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.9792361111111113,"py":1.375,"pz":0.564699074074074,"ry":248.64481481481482,"rx":5.00000000000002}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities