# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.6418f,-0.0812f,0.7639f,0.1385f,-0.2745f,0.9539f,-0.1293f,1.2113f,-0.7175f,-0.2924f,-0.6338f,-0.2231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.6347f,-0.0811f,0.7631f,-0.1301f,-0.2715f,0.9529f,-0.1291f,1.3266f,-0.7096f,-0.2921f,-0.6332f,-0.1855f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.6347f,-0.0811f,0.7631f,0.1421f,-0.2715f,0.9529f,-0.1291f,1.2107f,-0.7096f,-0.2921f,-0.6332f,-0.226f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.6347f,-0.0811f,0.7631f,0.0147f,-0.2715f,0.9529f,-0.1291f,1.3878f,-0.7096f,-0.2921f,-0.6332f,-0.026f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.6347f,-0.0811f,0.7631f,0.0265f,-0.2715f,0.9529f,-0.1291f,1.395f,-0.7096f,-0.2921f,-0.6332f,-0.0205f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.6347f,-0.0794f,0.7636f,0.125f,-0.2715f,0.9331f,-0.1292f,1.3705f,-0.7096f,-0.286f,-0.6336f,-0.2719f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6347f,-0.0811f,0.7631f,0.1385f,-0.2715f,0.9529f,-0.1291f,1.2113f,-0.7096f,-0.2921f,-0.6332f,-0.2231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.6347f,-0.0649f,0.7631f,-0.1612f,-0.2715f,0.7624f,-0.1291f,1.3647f,-0.7096f,-0.2337f,-0.6332f,-0.1863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.6335f,-0.0758f,0.7631f,-0.0026f,-0.2846f,0.7576f,-0.1291f,1.4326f,-0.7055f,-0.2458f,-0.6332f,-0.0089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.6347f,-0.0811f,0.7631f,0.1349f,-0.2715f,0.9529f,-0.1291f,1.2538f,-0.7096f,-0.2921f,-0.6332f,-0.2361f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.6347f,-0.0811f,0.7631f,0.137f,-0.2715f,0.9529f,-0.1291f,1.2292f,-0.7096f,-0.2921f,-0.6332f,-0.2285f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.6347f,-0.0811f,0.7631f,0.1347f,-0.2715f,0.9529f,-0.1291f,1.256f,-0.7096f,-0.2921f,-0.6332f,-0.2367f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.6347f,-0.0811f,0.7631f,0.1359f,-0.2715f,0.9529f,-0.1291f,1.2411f,-0.7096f,-0.2921f,-0.6332f,-0.2322f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.6347f,-0.0965f,0.7631f,0.0176f,-0.2715f,1.1341f,-0.1291f,1.2412f,-0.7096f,-0.3476f,-0.6332f,-0.0788f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.6347f,-0.0965f,0.7631f,0.0095f,-0.2715f,1.1341f,-0.1291f,1.2389f,-0.7096f,-0.3476f,-0.6332f,-0.088f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.6347f,-0.0811f,0.7631f,0.1385f,-0.2715f,0.9529f,-0.1291f,1.2113f,-0.7096f,-0.2921f,-0.6332f,-0.2231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6411f,-0.0811f,0.7631f,0.1385f,-0.2743f,0.9529f,-0.1291f,1.2113f,-0.7168f,-0.2921f,-0.6332f,-0.2231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9755f,0.0101f,0.2152f,0.0403f,-0.1592f,0.6387f,-0.7515f,0.755f,-0.1451f,-0.769f,-0.6225f,0.616f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9755f,0.1164f,0.1813f,0.086f,-0.1592f,0.1774f,-0.9702f,0.7857f,-0.1451f,-0.9772f,-0.1545f,0.2752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9114f,0.2671f,0.2817f,0.0869f,-0.0684f,0.6015f,-0.7951f,1.0054f,-0.3779f,-0.7529f,-0.5353f,-0.0614f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9123f,0.2671f,0.282f,0.1829f,-0.0685f,0.6015f,-0.7959f,1.2216f,-0.3783f,-0.7529f,-0.5358f,-0.332f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.6879f,0.5677f,-0.2092f,-0.3105f,-0.1649f,0.5542f,0.7983f,0.8319f,0.5054f,-0.5917f,0.5455f,-0.3037f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.7625f,0.4058f,-0.4821f,-0.177f,-0.234f,0.886f,0.3741f,1.1411f,0.5848f,-0.1745f,0.7783f,-0.354f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.6266f,0.527f,0.4662f,0.3806f,-0.559f,-0.1463f,-0.7575f,1.0502f,-0.294f,-0.8329f,0.4393f,0.2918f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.6983f,0.1455f,0.687f,0.416f,-0.6247f,0.3217f,-0.6986f,1.1781f,-0.3185f,-0.9349f,-0.1348f,-0.0125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.8738f,0.4179f,0.246f,-0.2644f,-0.0026f,0.5031f,-0.8631f,0.7433f,-0.4842f,-0.7563f,-0.439f,0.4051f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.8738f,0.485f,0.0041f,-0.1219f,-0.0026f,0.0041f,-0.999f,0.732f,-0.4842f,-0.8745f,-0.0021f,0.1482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-0.9521477517361113,"py":1.375,"pz":0.564127589699074,"ry":245.09886856481478,"rx":5.000000000000019}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities