# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.6227f,-0.1547f,0.7684f,0.0994f,-0.2545f,0.968f,-0.0113f,1.2949f,-0.7413f,-0.2024f,-0.6415f,-0.1766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.6158f,-0.1546f,0.7676f,-0.1756f,-0.2517f,0.9671f,-0.0113f,1.3834f,-0.7331f,-0.2022f,-0.6408f,-0.1272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.6158f,-0.1546f,0.7676f,0.103f,-0.2517f,0.9671f,-0.0113f,1.2948f,-0.7331f,-0.2022f,-0.6408f,-0.1796f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.6158f,-0.1546f,0.7676f,-0.0395f,-0.2517f,0.9671f,-0.0113f,1.4384f,-0.7331f,-0.2022f,-0.6408f,0.032f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.6158f,-0.1546f,0.7676f,-0.0253f,-0.2517f,0.9671f,-0.0113f,1.4499f,-0.7331f,-0.2022f,-0.6408f,0.042f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.6158f,-0.1546f,0.7684f,0.073f,-0.2517f,0.9671f,-0.0113f,1.4599f,-0.7331f,-0.2022f,-0.6415f,-0.2111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6158f,-0.1546f,0.7676f,0.0994f,-0.2517f,0.9671f,-0.0113f,1.2949f,-0.7331f,-0.2022f,-0.6408f,-0.1766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.6158f,-0.1237f,0.7676f,-0.2109f,-0.2517f,0.7736f,-0.0113f,1.4206f,-0.7331f,-0.1618f,-0.6408f,-0.1262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.6132f,-0.1359f,0.7676f,-0.057f,-0.2671f,0.7685f,-0.0113f,1.4835f,-0.7298f,-0.1763f,-0.6408f,0.0571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.6158f,-0.1546f,0.7676f,0.0922f,-0.2517f,0.9671f,-0.0113f,1.3396f,-0.7331f,-0.2022f,-0.6408f,-0.1859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.6158f,-0.1546f,0.7676f,0.0964f,-0.2517f,0.9671f,-0.0113f,1.313f,-0.7331f,-0.2022f,-0.6408f,-0.1803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.6158f,-0.1546f,0.7676f,0.0921f,-0.2517f,0.9671f,-0.0113f,1.3402f,-0.7331f,-0.2022f,-0.6408f,-0.186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.6158f,-0.1546f,0.7676f,0.0945f,-0.2517f,0.9671f,-0.0113f,1.3251f,-0.7331f,-0.2022f,-0.6408f,-0.1829f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.6158f,-0.1839f,0.7676f,-0.0228f,-0.2517f,1.1508f,-0.0113f,1.3019f,-0.7331f,-0.2407f,-0.6408f,-0.0304f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.6158f,-0.1839f,0.7676f,-0.0305f,-0.2517f,1.1508f,-0.0113f,1.2987f,-0.7331f,-0.2407f,-0.6408f,-0.0396f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.6158f,-0.1546f,0.7676f,0.0994f,-0.2517f,0.9671f,-0.0113f,1.2949f,-0.7331f,-0.2022f,-0.6408f,-0.1766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.622f,-0.1546f,0.7676f,0.0994f,-0.2543f,0.9671f,-0.0113f,1.2949f,-0.7405f,-0.2022f,-0.6408f,-0.1766f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9613f,-0.0422f,0.2685f,0.0402f,-0.2187f,0.7064f,-0.6718f,0.7563f,-0.1613f,-0.7062f,-0.6893f,0.6161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9613f,0.0977f,0.2536f,0.0817f,-0.2187f,0.2759f,-0.935f,0.822f,-0.1613f,-0.9562f,-0.2439f,0.2798f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9054f,0.2169f,0.3385f,0.0643f,-0.102f,0.6875f,-0.7181f,1.0715f,-0.3846f,-0.6931f,-0.6064f,-0.0349f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9063f,0.2169f,0.3388f,0.1423f,-0.1021f,0.6875f,-0.7189f,1.3185f,-0.385f,-0.6931f,-0.607f,-0.2839f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.6999f,0.5292f,-0.2537f,-0.3246f,-0.1931f,0.6664f,0.6983f,0.9178f,0.4782f,-0.5054f,0.6533f,-0.3054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.7791f,0.3502f,-0.4988f,-0.2104f,-0.2681f,0.9249f,0.2294f,1.2386f,0.5471f,-0.0456f,0.8226f,-0.3108f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.3566f,0.6848f,0.5963f,0.2802f,-0.7441f,0.0017f,-0.5456f,1.1432f,-0.3329f,-0.7245f,0.5741f,0.3298f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.3894f,0.2745f,0.8688f,0.3518f,-0.8196f,0.3132f,-0.4615f,1.2636f,-0.395f,-0.9084f,0.1019f,0.0288f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.8735f,0.3748f,0.3086f,-0.2638f,-0.0239f,0.6015f,-0.7973f,0.7412f,-0.4842f,-0.7052f,-0.517f,0.4044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.8735f,0.4789f,0.0798f,-0.1221f,-0.0239f,0.1223f,-0.9913f,0.7647f,-0.4842f,-0.8692f,-0.0951f,0.1479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera3":{"px":-1.029442625,"py":1.125,"pz":-0.3989330625000001,"ry":315.10192612179765,"rx":-7.974018355100317}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities