# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-0.6205f,-0.1628f,0.7685f,0.0949f,-0.2601f,0.9666f,-0.0052f,1.2964f,-0.7412f,-0.2029f,-0.6414f,-0.1768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.6137f,-0.1626f,0.7677f,-0.1808f,-0.2572f,0.9656f,-0.0052f,1.3826f,-0.7331f,-0.2027f,-0.6408f,-0.1274f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.6137f,-0.1626f,0.7677f,0.0985f,-0.2572f,0.9656f,-0.0052f,1.2964f,-0.7331f,-0.2027f,-0.6408f,-0.1798f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.6137f,-0.1626f,0.7677f,-0.0452f,-0.2572f,0.9656f,-0.0052f,1.4389f,-0.7331f,-0.2027f,-0.6408f,0.0317f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.6137f,-0.1626f,0.7677f,-0.0311f,-0.2572f,0.9656f,-0.0052f,1.4505f,-0.7331f,-0.2027f,-0.6408f,0.0417f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.6137f,-0.1626f,0.7685f,0.0671f,-0.2572f,0.9656f,-0.0052f,1.4613f,-0.7331f,-0.2027f,-0.6414f,-0.2114f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.6137f,-0.1626f,0.7677f,0.0949f,-0.2572f,0.9656f,-0.0052f,1.2964f,-0.7331f,-0.2027f,-0.6408f,-0.1768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.6137f,-0.1301f,0.7677f,-0.2165f,-0.2572f,0.7725f,-0.0052f,1.4196f,-0.7331f,-0.1621f,-0.6408f,-0.1265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.6109f,-0.1426f,0.7677f,-0.0631f,-0.2729f,0.7671f,-0.0052f,1.4839f,-0.7296f,-0.1771f,-0.6408f,0.0567f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.6137f,-0.1626f,0.7677f,0.0873f,-0.2572f,0.9656f,-0.0052f,1.3411f,-0.7331f,-0.2027f,-0.6408f,-0.1862f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.6137f,-0.1626f,0.7677f,0.0918f,-0.2572f,0.9656f,-0.0052f,1.3145f,-0.7331f,-0.2027f,-0.6408f,-0.1806f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.6137f,-0.1626f,0.7677f,0.0872f,-0.2572f,0.9656f,-0.0052f,1.3417f,-0.7331f,-0.2027f,-0.6408f,-0.1863f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.6137f,-0.1626f,0.7677f,0.0897f,-0.2572f,0.9656f,-0.0052f,1.3266f,-0.7331f,-0.2027f,-0.6408f,-0.1831f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.6137f,-0.1935f,0.7677f,-0.0273f,-0.2572f,1.1491f,-0.0052f,1.3025f,-0.7331f,-0.2412f,-0.6408f,-0.0307f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.6137f,-0.1935f,0.7677f,-0.035f,-0.2572f,1.1491f,-0.0052f,1.2993f,-0.7331f,-0.2412f,-0.6408f,-0.0398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.6137f,-0.1626f,0.7677f,0.0949f,-0.2572f,0.9656f,-0.0052f,1.2964f,-0.7331f,-0.2027f,-0.6408f,-0.1768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-0.6198f,-0.1626f,0.7677f,0.0949f,-0.2598f,0.9656f,-0.0052f,1.2964f,-0.7405f,-0.2027f,-0.6408f,-0.1768f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9595f,-0.048f,0.2741f,0.0401f,-0.2267f,0.7057f,-0.6698f,0.7578f,-0.1613f,-0.7065f,-0.689f,0.6161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9595f,0.0955f,0.2614f,0.0811f,-0.2267f,0.2763f,-0.933f,0.8236f,-0.1613f,-0.9563f,-0.2434f,0.2798f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.9045f,0.2112f,0.3445f,0.0617f,-0.1097f,0.6889f,-0.7156f,1.0728f,-0.3846f,-0.6934f,-0.606f,-0.035f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.9054f,0.2112f,0.3448f,0.1376f,-0.1098f,0.6889f,-0.7163f,1.3204f,-0.385f,-0.6934f,-0.6067f,-0.2842f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.7014f,0.5237f,-0.2595f,-0.3259f,-0.187f,0.6705f,0.6964f,0.9158f,0.4783f,-0.5057f,0.653f,-0.3055f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.7813f,0.3425f,-0.5007f,-0.2145f,-0.2613f,0.9277f,0.2256f,1.2375f,0.5473f,-0.046f,0.8225f,-0.3111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.3523f,0.6738f,0.6117f,0.2769f,-0.7495f,0.0083f,-0.5365f,1.1465f,-0.3256f,-0.7349f,0.5661f,0.3296f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.3825f,0.2719f,0.8727f,0.3476f,-0.823f,0.3151f,-0.4542f,1.2673f,-0.3946f,-0.9086f,0.1022f,0.0286f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.8732f,0.3698f,0.3152f,-0.2637f,-0.0314f,0.6043f,-0.795f,0.74f,-0.4843f,-0.7055f,-0.5166f,0.4044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.8732f,0.4779f,0.0881f,-0.1222f,-0.0314f,0.1259f,-0.9906f,0.7646f,-0.4843f,-0.8693f,-0.0947f,0.1479f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera3":{"px":-1.026254,"py":1.125,"pz":-0.3952130000000001,"ry":315.29347897606704,"rx":-7.97190972094262}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities