# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(layer) {transformation: [-1.001f,0f,0f,0f,0f,1.001f,-0.0087f,1.3882f,0f,-0.0087f,-1.001f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l_1) {transformation: [-0.9976f,0f,0f,-0.1069f,0f,1.0077f,-0.0087f,1.5098f,0f,-0.0087f,-1.0077f,0.228f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_l) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0086f,1.3881f,0f,-0.0086f,-1f,-0.0186f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r_1) {transformation: [-0.9976f,0f,0f,0.1069f,0f,1.0077f,-0.0087f,1.5098f,0f,-0.0087f,-1.0077f,0.2271f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eye_r) {transformation: [-0.99f,0f,0f,0.1237f,0f,1f,-0.0086f,1.5152f,0f,-0.0086f,-1f,0.2225f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_up) {transformation: [-0.99f,0f,0f,0f,0f,1.2104f,-0.0087f,1.5824f,0f,-0.0105f,-1.0047f,-0.0158f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0086f,1.3882f,0f,-0.0086f,-1f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(l) {transformation: [-0.99f,0.0031f,0f,-0.1238f,0.0025f,0.8f,-0.0086f,1.5497f,0f,-0.0069f,-1f,0.2564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(r) {transformation: [-0.99f,-0.0031f,0f,0.1237f,-0.0025f,0.8f,-0.0086f,1.5497f,0f,-0.0069f,-1f,0.2564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(eyes_down) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0086f,1.433f,0f,-0.0086f,-1f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(up) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0086f,1.406f,0f,-0.0086f,-1f,-0.0142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(down) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0086f,1.4383f,0f,-0.0086f,-1f,-0.0145f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mowse) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0086f,1.4194f,0f,-0.0086f,-1f,-0.0143f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_r) {transformation: [-0.99f,0f,0f,0.0305f,0f,1.0497f,-0.0086f,1.3916f,0f,-0.0091f,-1f,0.1734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(mouse_l) {transformation: [-0.99f,0f,0f,0.0217f,0f,1.0497f,-0.0086f,1.3878f,0f,-0.0091f,-1f,0.1734f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(face) {transformation: [-0.99f,0f,0f,0f,0f,1f,-0.0086f,1.3882f,0f,-0.0086f,-1f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(head) {transformation: [-1f,0f,0f,0f,0f,1f,-0.0086f,1.3882f,0f,-0.0086f,-1f,-0.0141f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(6) {transformation: [-0.9981f,-0.0192f,-0.0383f,0.1305f,-0.0334f,0.9076f,0.4184f,0.4555f,0.0267f,0.4188f,-0.9066f,-0.0828f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(12) {transformation: [-0.9981f,-0.0347f,-0.0251f,0.1185f,-0.0334f,0.9982f,-0.0491f,0.7986f,0.0267f,-0.0483f,-0.9975f,-0.0994f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(10) {transformation: [-0.989f,0f,0f,0f,0f,0.9998f,0.0173f,1.1421f,0f,0.0174f,-0.9988f,-0.0551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(9) {transformation: [-0.99f,0f,0f,0f,0f,0.989f,0.1477f,1.4976f,0f,0.1477f,-0.989f,-0.002f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(2) {transformation: [0.9812f,0.0243f,0.1139f,-0.3773f,-0.0298f,0.9882f,0.0479f,1.0954f,-0.1124f,-0.0502f,0.9814f,-0.1315f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(1) {transformation: [0.9821f,0.0702f,0.093f,-0.3524f,-0.0299f,0.9159f,-0.3743f,1.4025f,-0.1125f,0.3692f,0.9107f,0.0044f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(4) {transformation: [-0.9849f,-0.0428f,0.0725f,0.3668f,-0.0654f,0.9609f,-0.2669f,1.0523f,-0.0586f,-0.2665f,-0.9507f,-0.099f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(3) {transformation: [-0.9859f,-0.0656f,0.0528f,0.3437f,-0.0655f,0.9934f,0.0881f,1.3791f,-0.0586f,0.0849f,-0.9837f,-0.0463f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(8) {transformation: [-0.999f,0.0031f,0.011f,-0.1336f,0.0041f,0.9924f,0.1226f,0.424f,-0.0106f,0.1227f,-0.9914f,0.0039f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(7) {transformation: [-0.999f,0.0069f,0.0092f,-0.1312f,0.0041f,0.9703f,-0.2415f,0.7576f,-0.0106f,-0.2411f,-0.9694f,-0.0789f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify storage animated_java:temp entry.data merge value {"cameras":{"camera":{"px":-9.950255243072244e-17,"py":1.59375,"pz":0.8125,"ry":182.8156397628907,"rx":-2.8156397628906498}}}
# Data Manager: Prepare for Read / Write
execute store result storage animated_java:temp args.id int 1 run scoreboard players get @s aj.id
# Data Manager: Write
function animated_java:global/data_manager/write with storage animated_java:temp args
function animated_java:stellar/root/on_tick/transform_floating_entities