# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.amysis.animation.idle.playing
tag @s remove aj.amysis.animation.cutscene_opening_1.playing